/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.wiktionary;

public final class R {
    public static final class anim {
        public static final int slide_in=0x7f040000;
        public static final int slide_out=0x7f040001;
    }
    public static final class array {
        public static final int month_names=0x7f070000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
        public static final int ic_menu_shuffle=0x7f020001;
        public static final int logo_overlay=0x7f020002;
        public static final int lookup_bg=0x7f020003;
        public static final int progress_spin=0x7f020004;
        public static final int star_logo=0x7f020005;
        public static final int widget_bg=0x7f020006;
        public static final int widget_bg_normal=0x7f020007;
        public static final int widget_bg_pressed=0x7f020008;
        public static final int widget_bg_selected=0x7f020009;
    }
    public static final class id {
        public static final int about_credits=0x7f0a0000;
        public static final int bullet=0x7f0a000a;
        public static final int definition=0x7f0a000b;
        public static final int icon=0x7f0a0007;
        public static final int lookup_about=0x7f0a000e;
        public static final int lookup_random=0x7f0a000d;
        public static final int lookup_search=0x7f0a000c;
        public static final int message=0x7f0a0006;
        public static final int progress=0x7f0a0002;
        public static final int title=0x7f0a0003;
        public static final int title_bar=0x7f0a0001;
        public static final int webview=0x7f0a0004;
        public static final int widget=0x7f0a0005;
        public static final int word_title=0x7f0a0008;
        public static final int word_type=0x7f0a0009;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int lookup=0x7f030001;
        public static final int widget_message=0x7f030002;
        public static final int widget_word=0x7f030003;
    }
    public static final class menu {
        public static final int lookup=0x7f090000;
    }
    public static final class string {
        public static final int app_credits=0x7f060002;
        public static final int app_descrip=0x7f060001;
        public static final int app_name=0x7f060000;
        public static final int empty_result=0x7f06000e;
        public static final int lookup_about=0x7f06000d;
        public static final int lookup_random=0x7f06000c;
        public static final int lookup_search=0x7f06000b;
        public static final int search_hint=0x7f06000a;
        public static final int search_label=0x7f060009;
        public static final int template_define_url=0x7f060005;
        public static final int template_user_agent=0x7f060003;
        public static final int template_wotd_title=0x7f060004;
        public static final int widget_error=0x7f060008;
        public static final int widget_loading=0x7f060007;
        public static final int widget_name=0x7f060006;
    }
    public static final class style {
        public static final int BulletPoint=0x7f080001;
        public static final int LookupProgress=0x7f080007;
        public static final int LookupTheme=0x7f080009;
        public static final int LookupTitle=0x7f080008;
        public static final int Text=0x7f080002;
        public static final int Text_Definition=0x7f080006;
        public static final int Text_Loading=0x7f080003;
        public static final int Text_WordTitle=0x7f080004;
        public static final int Text_WordType=0x7f080005;
        public static final int WidgetBackground=0x7f080000;
    }
    public static final class xml {
        public static final int searchable=0x7f050000;
        public static final int widget_word=0x7f050001;
    }
}
