/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.skeletonapp;

public final class R {
    public static final class attr {
    }
    public static final class color {
        /**  Retrieved via Resources.getColor() and friends. 
         */
        public static final int red=0x7f040000;
    }
    public static final class drawable {
        /**  Retrieved via Resources.getDrawable() and friends. 
         */
        public static final int semi_black=0x7f020001;
        public static final int violet=0x7f020000;
    }
    public static final class id {
        public static final int back=0x7f070001;
        public static final int clear=0x7f070003;
        public static final int editor=0x7f070000;
        public static final int image=0x7f070002;
    }
    public static final class layout {
        public static final int skeleton_activity=0x7f030000;
    }
    public static final class string {
        public static final int back=0x7f050001;
        public static final int clear=0x7f050002;
        /**  This is a complex string containing style runs. 
         */
        public static final int main_label=0x7f050003;
        /**  Simple strings. 
         */
        public static final int skeleton_app=0x7f050000;
    }
    public static final class style {
        public static final int ActionButton=0x7f060000;
        public static final int TextAppearance=0x7f060001;
        public static final int TextAppearance_ActionButton=0x7f060002;
    }
}
