/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.wifidirect;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int layout_border_color=0x7f040001;
        public static final int status_bar_color=0x7f040000;
    }
    public static final class dimen {
        public static final int phone_list_height=0x7f050001;
        public static final int tablet_list_width=0x7f050000;
    }
    public static final class drawable {
        public static final int details_view=0x7f020000;
        public static final int ic_action_discover=0x7f020001;
        public static final int ic_action_on_off=0x7f020002;
        public static final int ic_launcher=0x7f020003;
        public static final int icon=0x7f020004;
        public static final int machine=0x7f020005;
        public static final int section_header=0x7f020006;
    }
    public static final class id {
        public static final int atn_direct_discover=0x7f080012;
        public static final int atn_direct_enable=0x7f080011;
        public static final int btn_connect=0x7f080000;
        public static final int btn_disconnect=0x7f080001;
        public static final int btn_start_client=0x7f080002;
        public static final int device_address=0x7f080003;
        public static final int device_details=0x7f080010;
        public static final int device_info=0x7f080004;
        public static final int device_name=0x7f08000f;
        public static final int frag_detail=0x7f08000e;
        public static final int frag_list=0x7f08000d;
        public static final int group_ip=0x7f080006;
        public static final int group_owner=0x7f080005;
        public static final int icon=0x7f080009;
        public static final int linearLayout1=0x7f08000c;
        public static final int my_name=0x7f08000a;
        public static final int my_status=0x7f08000b;
        public static final int status_bar=0x7f080007;
        public static final int status_text=0x7f080008;
    }
    public static final class layout {
        public static final int device_detail=0x7f030000;
        public static final int device_list=0x7f030001;
        public static final int main=0x7f030002;
        public static final int row_devices=0x7f030003;
    }
    public static final class menu {
        public static final int action_items=0x7f070000;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int client_text=0x7f060009;
        public static final int connect_peer_button=0x7f060003;
        public static final int disconnect_peer_button=0x7f060004;
        public static final int discover_peers_button=0x7f060002;
        public static final int empty=0x7f060006;
        public static final int empty_message=0x7f06000a;
        public static final int enable_p2p_button=0x7f060001;
        public static final int get_file_button=0x7f060005;
        public static final int group_owner_text=0x7f06000c;
        public static final int label_me=0x7f06000d;
        public static final int label_peers=0x7f06000e;
        public static final int no=0x7f060008;
        public static final int p2p_off_warning=0x7f06000b;
        public static final int yes=0x7f060007;
    }
}
