/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.hcgallery;

public final class R {
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int listDragShadowBackground=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int menuIconCamera=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int menuIconShare=0x7f010003;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int menuIconToggle=0x7f010002;
    }
    public static final class color {
        public static final int actionbar_background_dark=0x7f040001;
        public static final int actionbar_background_light=0x7f040000;
        public static final int drag_active_color=0x7f040002;
    }
    public static final class dimen {
        public static final int titles_size=0x7f050000;
    }
    public static final class drawable {
        public static final int big_droid=0x7f020000;
        public static final int blue_balloon=0x7f020001;
        public static final int blue_bike=0x7f020002;
        public static final int btn_notification_ic_example=0x7f020003;
        public static final int btn_notification_ic_example_default=0x7f020004;
        public static final int btn_notification_ic_example_pressed=0x7f020005;
        public static final int chrome_wheel=0x7f020006;
        public static final int cupcake=0x7f020007;
        public static final int donut=0x7f020008;
        public static final int eclair=0x7f020009;
        public static final int froyo=0x7f02000a;
        public static final int green_balloon=0x7f02000b;
        public static final int ic_menu_camera_holo_dark=0x7f02000c;
        public static final int ic_menu_camera_holo_light=0x7f02000d;
        public static final int ic_menu_share_holo_dark=0x7f02000e;
        public static final int ic_menu_share_holo_light=0x7f02000f;
        public static final int ic_menu_toggle_holo_dark=0x7f020010;
        public static final int ic_menu_toggle_holo_light=0x7f020011;
        public static final int ic_stat_notify_example=0x7f020012;
        public static final int icon=0x7f020013;
        public static final int logo=0x7f020014;
        public static final int notification_default_largeicon=0x7f020015;
        public static final int picture_frame=0x7f020016;
        public static final int picture_frame_default=0x7f020017;
        public static final int picture_frame_pressed=0x7f020018;
        public static final int picture_frame_selected=0x7f020019;
        public static final int punk_droid=0x7f02001a;
        public static final int rainbow_bike=0x7f02001b;
        public static final int red_balloon=0x7f02001c;
        public static final int stargazer_droid=0x7f02001d;
    }
    public static final class id {
        public static final int camera_frag=0x7f090000;
        public static final int content_frag=0x7f090001;
        public static final int frags=0x7f090004;
        public static final int image=0x7f090002;
        public static final int menu_camera=0x7f09000a;
        public static final int menu_share=0x7f090010;
        public static final int menu_showCustomNotification=0x7f09000f;
        public static final int menu_showDialog=0x7f09000d;
        public static final int menu_showStandardNotification=0x7f09000e;
        public static final int menu_switch_cam=0x7f090009;
        public static final int menu_toggleTheme=0x7f09000c;
        public static final int menu_toggleTitles=0x7f09000b;
        public static final int notification_button=0x7f090008;
        public static final int notification_subtitle=0x7f090007;
        public static final int notification_title=0x7f090006;
        public static final int notificationbg=0x7f090005;
        public static final int titles_frag=0x7f090003;
    }
    public static final class layout {
        public static final int camera_sample=0x7f030000;
        public static final int content_activity=0x7f030001;
        public static final int content_welcome=0x7f030002;
        public static final int main=0x7f030003;
        public static final int notification=0x7f030004;
        public static final int title_list_item=0x7f030005;
    }
    public static final class menu {
        public static final int camera_menu=0x7f080000;
        public static final int main_menu=0x7f080001;
        public static final int photo_context_menu=0x7f080002;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int app_widget_name=0x7f060003;
        public static final int basic_notification=0x7f06000c;
        public static final int camera=0x7f060008;
        public static final int camera_sample=0x7f060001;
        public static final int clip_label=0x7f060002;
        public static final int custom_notification=0x7f06000d;
        public static final int day_night=0x7f06000a;
        public static final int notification_text=0x7f060005;
        public static final int photo_selection_cab_title=0x7f060006;
        /**  Menu strings 
         */
        public static final int share=0x7f060007;
        public static final int show_dialog=0x7f06000b;
        public static final int switch_camera=0x7f06000e;
        public static final int toggle_titles=0x7f060009;
        public static final int widget_empty_view_text=0x7f060004;
    }
    public static final class style {
        public static final int ActionBar=0x7f070000;
        public static final int ActionBar_Dark=0x7f070002;
        public static final int ActionBar_Light=0x7f070001;
        public static final int AppTheme_Dark=0x7f070004;
        public static final int AppTheme_Light=0x7f070003;
    }
    public static final class styleable {
        /** Attributes that can be used with a AppTheme.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #AppTheme_listDragShadowBackground com.example.android.hcgallery:listDragShadowBackground}</code></td><td></td></tr>
           <tr><td><code>{@link #AppTheme_menuIconCamera com.example.android.hcgallery:menuIconCamera}</code></td><td></td></tr>
           <tr><td><code>{@link #AppTheme_menuIconShare com.example.android.hcgallery:menuIconShare}</code></td><td></td></tr>
           <tr><td><code>{@link #AppTheme_menuIconToggle com.example.android.hcgallery:menuIconToggle}</code></td><td></td></tr>
           </table>
           @see #AppTheme_listDragShadowBackground
           @see #AppTheme_menuIconCamera
           @see #AppTheme_menuIconShare
           @see #AppTheme_menuIconToggle
         */
        public static final int[] AppTheme = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003
        };
        /**
          <p>This symbol is the offset where the {@link com.example.android.hcgallery.R.attr#listDragShadowBackground}
          attribute's value can be found in the {@link #AppTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android:listDragShadowBackground
        */
        public static final int AppTheme_listDragShadowBackground = 0;
        /**
          <p>This symbol is the offset where the {@link com.example.android.hcgallery.R.attr#menuIconCamera}
          attribute's value can be found in the {@link #AppTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android:menuIconCamera
        */
        public static final int AppTheme_menuIconCamera = 1;
        /**
          <p>This symbol is the offset where the {@link com.example.android.hcgallery.R.attr#menuIconShare}
          attribute's value can be found in the {@link #AppTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android:menuIconShare
        */
        public static final int AppTheme_menuIconShare = 3;
        /**
          <p>This symbol is the offset where the {@link com.example.android.hcgallery.R.attr#menuIconToggle}
          attribute's value can be found in the {@link #AppTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android:menuIconToggle
        */
        public static final int AppTheme_menuIconToggle = 2;
    };
}
