/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.xmladapters;

public final class R {
    public static final class attr {
        /**  The type of binding. If this value is not specified, the type will be
             inferred from the type of the "to" target view. Mandatory.

             The type can be one of:
             <ul>
             <li>string, The content of the column is interpreted as a string.</li>
             <li>image, The content of the column is interpreted as a blob describing an image.</li>
             <li>image-uri, The content of the column is interpreted as a URI to an image.</li>
             <li>drawable, The content of the column is interpreted as a resource id to a drawable.</li>
             <li>A fully qualified class name, corresponding to an implementation of
                 android.widget.Adapters.CursorBinder.</li>
             </ul>
         
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int as=0x7f010006;
        /**  The name of the column to select. Mandatory. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int column=0x7f010007;
        /**  The name of the column to bind from. Mandatory. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int from=0x7f010004;
        /**  The original value from the column. Mandatory. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fromValue=0x7f010008;
        /**  Layout resource used to display each row from the cursor. Mandatory. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int layout=0x7f010003;
        /**  Selection statement for the query. Optional. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int selection=0x7f010001;
        /**  Sort order statement for the query. Optional. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int sortOrder=0x7f010002;
        /**  The resource id of the view to bind to. Mandatory. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int to=0x7f010005;
        /**  The new value from the column. Mandatory. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int toValue=0x7f010009;
        /**  URI to get the cursor from. Optional. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uri=0x7f010000;
        /**  The transformation class, an implementation of
             android.widget.Adapters.CursorTransformation. Mandatory if "withExpression"
             is not specified. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int withClass=0x7f01000b;
        /**  The transformation expression. Mandatory if "withClass" is not specified. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int withExpression=0x7f01000a;
    }
    public static final class drawable {
        public static final int ic_contact_picture=0x7f020000;
    }
    public static final class id {
        public static final int date=0x7f060005;
        public static final int description=0x7f060007;
        public static final int image=0x7f060006;
        public static final int item_layout=0x7f060004;
        public static final int name=0x7f060000;
        public static final int photo=0x7f060002;
        public static final int star=0x7f060001;
        public static final int title=0x7f060003;
    }
    public static final class layout {
        public static final int contact_item=0x7f030000;
        public static final int contacts_list=0x7f030001;
        public static final int photo_item=0x7f030002;
        public static final int photos_list=0x7f030003;
        public static final int rss_feed_item=0x7f030004;
        public static final int rss_feeds_list=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int contacts_list_activity=0x7f050001;
        public static final int no_contacts=0x7f050004;
        public static final int no_photos=0x7f050005;
        public static final int no_rss_feed=0x7f050006;
        public static final int photos_list_activity=0x7f050002;
        public static final int rss_reader_activity=0x7f050003;
    }
    public static final class xml {
        public static final int contacts=0x7f040000;
        public static final int photos=0x7f040001;
        public static final int rss_feed=0x7f040002;
    }
    public static final class styleable {
        /**  Adapter used to bind cursors. 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CursorAdapter_layout com.example.android.xmladapters:layout}</code></td><td> Layout resource used to display each row from the cursor.</td></tr>
           <tr><td><code>{@link #CursorAdapter_selection com.example.android.xmladapters:selection}</code></td><td> Selection statement for the query.</td></tr>
           <tr><td><code>{@link #CursorAdapter_sortOrder com.example.android.xmladapters:sortOrder}</code></td><td> Sort order statement for the query.</td></tr>
           <tr><td><code>{@link #CursorAdapter_uri com.example.android.xmladapters:uri}</code></td><td> URI to get the cursor from.</td></tr>
           </table>
           @see #CursorAdapter_layout
           @see #CursorAdapter_selection
           @see #CursorAdapter_sortOrder
           @see #CursorAdapter_uri
         */
        public static final int[] CursorAdapter = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003
        };
        /**
          <p>
          @attr description
           Layout resource used to display each row from the cursor. Mandatory. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name android:layout
        */
        public static final int CursorAdapter_layout = 3;
        /**
          <p>
          @attr description
           Selection statement for the query. Optional. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:selection
        */
        public static final int CursorAdapter_selection = 1;
        /**
          <p>
          @attr description
           Sort order statement for the query. Optional. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:sortOrder
        */
        public static final int CursorAdapter_sortOrder = 2;
        /**
          <p>
          @attr description
           URI to get the cursor from. Optional. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:uri
        */
        public static final int CursorAdapter_uri = 0;
        /**  Attributes used in bind items for XML cursor adapters. 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CursorAdapter_BindItem_as com.example.android.xmladapters:as}</code></td><td> The type of binding.</td></tr>
           <tr><td><code>{@link #CursorAdapter_BindItem_from com.example.android.xmladapters:from}</code></td><td> The name of the column to bind from.</td></tr>
           <tr><td><code>{@link #CursorAdapter_BindItem_to com.example.android.xmladapters:to}</code></td><td> The resource id of the view to bind to.</td></tr>
           </table>
           @see #CursorAdapter_BindItem_as
           @see #CursorAdapter_BindItem_from
           @see #CursorAdapter_BindItem_to
         */
        public static final int[] CursorAdapter_BindItem = {
            0x7f010004, 0x7f010005, 0x7f010006
        };
        /**
          <p>
          @attr description
           The type of binding. If this value is not specified, the type will be
             inferred from the type of the "to" target view. Mandatory.

             The type can be one of:
             <ul>
             <li>string, The content of the column is interpreted as a string.</li>
             <li>image, The content of the column is interpreted as a blob describing an image.</li>
             <li>image-uri, The content of the column is interpreted as a URI to an image.</li>
             <li>drawable, The content of the column is interpreted as a resource id to a drawable.</li>
             <li>A fully qualified class name, corresponding to an implementation of
                 android.widget.Adapters.CursorBinder.</li>
             </ul>
         


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:as
        */
        public static final int CursorAdapter_BindItem_as = 2;
        /**
          <p>
          @attr description
           The name of the column to bind from. Mandatory. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:from
        */
        public static final int CursorAdapter_BindItem_from = 0;
        /**
          <p>
          @attr description
           The resource id of the view to bind to. Mandatory. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name android:to
        */
        public static final int CursorAdapter_BindItem_to = 1;
        /**  Attributes used to map values to new values in XML cursor adapters' bind items. 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CursorAdapter_MapItem_fromValue com.example.android.xmladapters:fromValue}</code></td><td> The original value from the column.</td></tr>
           <tr><td><code>{@link #CursorAdapter_MapItem_toValue com.example.android.xmladapters:toValue}</code></td><td> The new value from the column.</td></tr>
           </table>
           @see #CursorAdapter_MapItem_fromValue
           @see #CursorAdapter_MapItem_toValue
         */
        public static final int[] CursorAdapter_MapItem = {
            0x7f010008, 0x7f010009
        };
        /**
          <p>
          @attr description
           The original value from the column. Mandatory. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:fromValue
        */
        public static final int CursorAdapter_MapItem_fromValue = 0;
        /**
          <p>
          @attr description
           The new value from the column. Mandatory. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:toValue
        */
        public static final int CursorAdapter_MapItem_toValue = 1;
        /**  Attributes used in select items for XML cursor adapters.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CursorAdapter_SelectItem_column com.example.android.xmladapters:column}</code></td><td> The name of the column to select.</td></tr>
           </table>
           @see #CursorAdapter_SelectItem_column
         */
        public static final int[] CursorAdapter_SelectItem = {
            0x7f010007
        };
        /**
          <p>
          @attr description
           The name of the column to select. Mandatory. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:column
        */
        public static final int CursorAdapter_SelectItem_column = 0;
        /**  Attributes used to map values to new values in XML cursor adapters' bind items. 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CursorAdapter_TransformItem_withClass com.example.android.xmladapters:withClass}</code></td><td> The transformation class, an implementation of
             android.</td></tr>
           <tr><td><code>{@link #CursorAdapter_TransformItem_withExpression com.example.android.xmladapters:withExpression}</code></td><td> The transformation expression.</td></tr>
           </table>
           @see #CursorAdapter_TransformItem_withClass
           @see #CursorAdapter_TransformItem_withExpression
         */
        public static final int[] CursorAdapter_TransformItem = {
            0x7f01000a, 0x7f01000b
        };
        /**
          <p>
          @attr description
           The transformation class, an implementation of
             android.widget.Adapters.CursorTransformation. Mandatory if "withExpression"
             is not specified. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:withClass
        */
        public static final int CursorAdapter_TransformItem_withClass = 1;
        /**
          <p>
          @attr description
           The transformation expression. Mandatory if "withClass" is not specified. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:withExpression
        */
        public static final int CursorAdapter_TransformItem_withExpression = 0;
    };
}
