/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.rs.test;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int test_pattern=0x7f020000;
    }
    public static final class raw {
        public static final int alloc=0x7f030000;
        public static final int foreach=0x7f030001;
        public static final int fp_mad=0x7f030002;
        public static final int math=0x7f030003;
        public static final int primitives=0x7f030004;
        public static final int refcount=0x7f030005;
        public static final int rsdebug=0x7f030006;
        public static final int rslist=0x7f030007;
        public static final int rstime=0x7f030008;
        public static final int rstypes=0x7f030009;
        public static final int test_root=0x7f03000a;
        public static final int vector=0x7f03000b;
    }
}
