/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.dumprendertree2;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int folder=0x7f020000;
        public static final int runtest=0x7f020001;
    }
    public static final class id {
        public static final int icon=0x7f070000;
        public static final int label=0x7f070001;
        public static final int run_all=0x7f070002;
    }
    public static final class layout {
        public static final int dirlist_row=0x7f030000;
    }
    public static final class menu {
        public static final int gui_menu=0x7f060000;
    }
    public static final class string {
        public static final int dialog_progress_msg=0x7f040005;
        public static final int dialog_progress_title=0x7f040004;
        public static final int dialog_run_abort_dir_abort_button=0x7f040003;
        public static final int dialog_run_abort_dir_msg=0x7f040001;
        public static final int dialog_run_abort_dir_ok_button=0x7f040002;
        public static final int dialog_run_abort_dir_title_prefix=0x7f040000;
        public static final int run_all_tests=0x7f040007;
        public static final int runner_preloading_title=0x7f040006;
    }
    public static final class style {
        public static final int WhiteBackground=0x7f050000;
    }
}
