/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.helloactivity;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int text=0x7f040000;
    }
    public static final class layout {
        public static final int hello_activity=0x7f020000;
    }
    public static final class string {
        public static final int hello_activity_text_text=0x7f030000;
    }
}
