/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.providers.applications;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int icon1=0x7f050000;
        public static final int text1=0x7f050001;
    }
    public static final class layout {
        public static final int application_list_item=0x7f020000;
    }
    public static final class string {
        /**  [CHAR LIMIT=25] Label of this application. 
         */
        public static final int app_label=0x7f040000;
        /**  Description line displayed for an application entry in the search suggest list. 
         */
        public static final int application_desc=0x7f040002;
        /**  Search label for applications. 
         */
        public static final int search_label=0x7f040001;
        /**  Description line displayed for 'apps' as a searchable item within system search
         settings. 
         */
        public static final int settings_description=0x7f040003;
    }
    public static final class xml {
        public static final int searchable=0x7f030000;
    }
}
