/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.jetboy;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int asteroid01=0x7f020000;
        public static final int asteroid02=0x7f020001;
        public static final int asteroid03=0x7f020002;
        public static final int asteroid04=0x7f020003;
        public static final int asteroid05=0x7f020004;
        public static final int asteroid06=0x7f020005;
        public static final int asteroid07=0x7f020006;
        public static final int asteroid08=0x7f020007;
        public static final int asteroid09=0x7f020008;
        public static final int asteroid10=0x7f020009;
        public static final int asteroid11=0x7f02000a;
        public static final int asteroid12=0x7f02000b;
        public static final int asteroid_explode1=0x7f02000c;
        public static final int asteroid_explode2=0x7f02000d;
        public static final int asteroid_explode3=0x7f02000e;
        public static final int asteroid_explode4=0x7f02000f;
        public static final int background_a=0x7f020010;
        public static final int background_b=0x7f020011;
        public static final int icon=0x7f020012;
        public static final int int_timer=0x7f020013;
        public static final int intbeam_1=0x7f020014;
        public static final int intbeam_2=0x7f020015;
        public static final int intbeam_3=0x7f020016;
        public static final int intbeam_4=0x7f020017;
        public static final int laser=0x7f020018;
        public static final int ship2_1=0x7f020019;
        public static final int ship2_2=0x7f02001a;
        public static final int ship2_3=0x7f02001b;
        public static final int ship2_4=0x7f02001c;
        public static final int ship2_hit_1=0x7f02001d;
        public static final int ship2_hit_2=0x7f02001e;
        public static final int ship2_hit_3=0x7f02001f;
        public static final int ship2_hit_4=0x7f020020;
        public static final int title_bg_hori=0x7f020021;
        public static final int title_hori=0x7f020022;
    }
    public static final class id {
        public static final int Button01=0x7f070002;
        public static final int Button02=0x7f070003;
        public static final int JetBoyView=0x7f070000;
        public static final int text=0x7f070001;
        public static final int timer=0x7f070004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int level1=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int helpText=0x7f050004;
        public static final int loseText=0x7f050006;
        public static final int restart=0x7f050003;
        public static final int retry=0x7f050002;
        public static final int start=0x7f050001;
        public static final int timer=0x7f050007;
        public static final int winText=0x7f050005;
    }
    public static final class style {
        public static final int ButtonText=0x7f060000;
        public static final int helpText=0x7f060001;
        public static final int timerText=0x7f060002;
    }
}
