/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.lowstoragetest;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int button_run=0x7f040003;
        public static final int freesize=0x7f040001;
        public static final int status=0x7f040002;
        public static final int totalsize=0x7f040000;
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class string {
        public static final int available_storage=0x7f030001;
        public static final int eat_up_storage=0x7f030002;
        public static final int run_text=0x7f030004;
        public static final int status=0x7f030003;
        public static final int total_storage=0x7f030000;
    }
}
