/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.batterywaster;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int checkbox=0x7f040000;
        public static final int checkbox_wake=0x7f040001;
        public static final int log=0x7f040003;
        public static final int scroll=0x7f040002;
    }
    public static final class layout {
        public static final int battery_waster=0x7f020000;
    }
    public static final class string {
        public static final int wake_away=0x7f030001;
        public static final int waste_away=0x7f030000;
    }
}
