/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package android.deviceadmin.cts;

public final class R {
    public static final class attr {
    }
    public static final class xml {
        public static final int device_admin=0x7f020000;
        public static final int device_admin_2=0x7f020001;
    }
}
