/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.musicvis;

public final class R {
    public static final class array {
        /**  start,end point index tuples of the lines defining the object 
         */
        public static final int lines=0x7f070001;
        /**  x,y,z tuples for the points defining the object 
 stored as strings for easier human readability 
         */
        public static final int points=0x7f070000;
    }
    public static final class attr {
    }
    public static final class bool {
        public static final int config_enable_vis1=0x7f050000;
        public static final int config_enable_vis2=0x7f050001;
        public static final int config_enable_vis3=0x7f050002;
        public static final int config_enable_vis4=0x7f050003;
        public static final int config_enable_vis5=0x7f050004;
    }
    public static final class drawable {
        public static final int albumart=0x7f020000;
        public static final int background=0x7f020001;
        public static final int black=0x7f020002;
        public static final int fire=0x7f020003;
        public static final int frame=0x7f020004;
        public static final int ic_launcher_wallpaper=0x7f020005;
        public static final int ice=0x7f020006;
        public static final int needle=0x7f020007;
        public static final int peak_off=0x7f020008;
        public static final int peak_on=0x7f020009;
        public static final int vis2=0x7f02000a;
        public static final int vis3=0x7f02000b;
        public static final int vis4=0x7f02000c;
        public static final int vis5=0x7f02000d;
    }
    public static final class raw {
        public static final int many=0x7f040000;
        public static final int vu=0x7f040001;
        public static final int waveform=0x7f040002;
    }
    public static final class string {
        public static final int author=0x7f060006;
        public static final int vis2_desc=0x7f060007;
        public static final int vis3_desc=0x7f060008;
        public static final int vis4_desc=0x7f060009;
        public static final int vis5_desc=0x7f06000a;
        /**  Wallpapers showing a music visualizer 
         */
        public static final int wallpaper_vis1=0x7f060000;
        public static final int wallpaper_vis2=0x7f060001;
        public static final int wallpaper_vis3=0x7f060002;
        public static final int wallpaper_vis4=0x7f060003;
        public static final int wallpaper_vis5=0x7f060004;
        /**  Application name 
         */
        public static final int wallpapers=0x7f060005;
    }
    public static final class xml {
        public static final int vis2=0x7f030000;
        public static final int vis3=0x7f030001;
        public static final int vis4=0x7f030002;
        public static final int vis5=0x7f030003;
    }
}
