/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.wallpaper.holospiral;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int points_red_green=0x7f020000;
        public static final int wallpaper_thumb=0x7f020001;
    }
    public static final class raw {
        public static final int fragment_background=0x7f040000;
        public static final int fragment_geometry=0x7f040001;
        public static final int holo_spiral=0x7f040002;
        public static final int vertex_background=0x7f040003;
        public static final int vertex_geometry=0x7f040004;
    }
    public static final class string {
        public static final int wallpaper_author=0x7f050001;
        public static final int wallpaper_description=0x7f050002;
        public static final int wallpaper_label=0x7f050000;
    }
    public static final class xml {
        public static final int wallpaper=0x7f030000;
    }
}
