/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.development;

public final class R {
    public static final class array {
        public static final int glstester_services=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int box=0x7f020000;
        public static final int stat_sample=0x7f020001;
    }
    public static final class id {
        public static final int accounts_tester_account_name=0x7f080008;
        public static final int accounts_tester_account_type_icon=0x7f080007;
        public static final int accounts_tester_account_types_spinner=0x7f08000a;
        public static final int accounts_tester_account_types_spinner_label=0x7f080009;
        public static final int accounts_tester_accounts_list=0x7f080013;
        public static final int accounts_tester_add_account=0x7f08000d;
        public static final int accounts_tester_auth_token_type=0x7f08005f;
        public static final int accounts_tester_clear_password=0x7f080003;
        public static final int accounts_tester_confirm_credentials=0x7f080006;
        public static final int accounts_tester_desiredFeatures=0x7f080010;
        public static final int accounts_tester_desired_authtokentype=0x7f080012;
        public static final int accounts_tester_desired_features=0x7f080011;
        public static final int accounts_tester_edit_properties=0x7f08000e;
        public static final int accounts_tester_features=0x7f080061;
        public static final int accounts_tester_get_accounts_by_type=0x7f08000b;
        public static final int accounts_tester_get_all_accounts=0x7f08000c;
        public static final int accounts_tester_get_auth_token=0x7f080001;
        public static final int accounts_tester_get_auth_token_by_type_and_feature=0x7f08000f;
        public static final int accounts_tester_get_auth_token_dialog_message=0x7f08005e;
        public static final int accounts_tester_get_features_dialog_message=0x7f080060;
        public static final int accounts_tester_invalidate_auth_token=0x7f080004;
        public static final int accounts_tester_remove_account=0x7f080000;
        public static final int accounts_tester_test_has_features=0x7f080002;
        public static final int accounts_tester_update_credentials=0x7f080005;
        public static final int activities=0x7f08007a;
        public static final int add_default_route=0x7f08003f;
        public static final int always_finish=0x7f080052;
        public static final int attr_five_way_nav=0x7f08001f;
        public static final int attr_five_way_nav_label=0x7f08001e;
        public static final int attr_gles_version=0x7f080021;
        public static final int attr_gles_version_label=0x7f080020;
        public static final int attr_hard_keyboard=0x7f08001b;
        public static final int attr_hard_keyboard_label=0x7f08001a;
        public static final int attr_input_method=0x7f080019;
        public static final int attr_input_method_label=0x7f080018;
        public static final int attr_navigation=0x7f08001d;
        public static final int attr_navigation_label=0x7f08001c;
        public static final int attr_package=0x7f080015;
        public static final int attr_package_label=0x7f080014;
        public static final int attr_touchscreen=0x7f080017;
        public static final int attr_touchscreen_label=0x7f080016;
        public static final int bad_behavior_anr=0x7f080027;
        public static final int bad_behavior_anr_activity=0x7f080028;
        public static final int bad_behavior_anr_broadcast=0x7f080029;
        public static final int bad_behavior_anr_service=0x7f08002a;
        public static final int bad_behavior_anr_system=0x7f08002b;
        public static final int bad_behavior_crash_main=0x7f080022;
        public static final int bad_behavior_crash_native=0x7f080024;
        public static final int bad_behavior_crash_system=0x7f080025;
        public static final int bad_behavior_crash_thread=0x7f080023;
        public static final int bad_behavior_wedge_system=0x7f08002c;
        public static final int bad_behavior_wtf=0x7f080026;
        public static final int bind_button=0x7f08009c;
        public static final int bound_adapter_text_view=0x7f08009e;
        public static final int bound_http_request=0x7f080043;
        public static final int bound_socket_request=0x7f080044;
        public static final int cancel_sync_button=0x7f0800a0;
        public static final int classView=0x7f08006c;
        public static final int clearOnBackground=0x7f080098;
        public static final int compatibility_mode=0x7f08004f;
        public static final int crash=0x7f08003e;
        public static final int data=0x7f080079;
        public static final int dc_wifi_cycles_done=0x7f080034;
        public static final int dc_wifi_off_duration=0x7f080033;
        public static final int dc_wifi_on_duration=0x7f080032;
        public static final int debug_app=0x7f080048;
        public static final int debug_app_label=0x7f080047;
        public static final int debuggable=0x7f080070;
        public static final int default_request=0x7f080041;
        public static final int default_socket=0x7f080042;
        public static final int description=0x7f08006a;
        public static final int disableWifi=0x7f08002f;
        public static final int disabled=0x7f08006e;
        public static final int display_edit_text=0x7f08005d;
        public static final int enableWifi=0x7f08002e;
        public static final int enable_gl=0x7f080054;
        public static final int font_hinting=0x7f080059;
        public static final int icon=0x7f080068;
        public static final int initialActivity=0x7f080065;
        public static final int insertbutton=0x7f080064;
        public static final int instrumentation=0x7f08007e;
        public static final int label=0x7f08006d;
        public static final int launch=0x7f080094;
        public static final int max_procs=0x7f080050;
        public static final int multiprocess=0x7f080097;
        public static final int name=0x7f080069;
        public static final int nocode=0x7f080071;
        public static final int numberOfEvents=0x7f080066;
        public static final int numsongs=0x7f080063;
        public static final int packageView=0x7f08006b;
        public static final int package_list=0x7f080093;
        public static final int package_list_header=0x7f080092;
        public static final int perm_desc=0x7f080082;
        public static final int perm_desc_label=0x7f080081;
        public static final int perm_group=0x7f080084;
        public static final int perm_group_label=0x7f080083;
        public static final int perm_list_header=0x7f08008e;
        public static final int perm_name=0x7f080080;
        public static final int perm_name_label=0x7f08007f;
        public static final int perm_protection=0x7f080086;
        public static final int perm_protection_label=0x7f080085;
        public static final int perm_source=0x7f080088;
        public static final int perm_source_label=0x7f080087;
        public static final int permission=0x7f080096;
        public static final int persistent=0x7f080072;
        public static final int pkg_name=0x7f08008f;
        public static final int pointer_location=0x7f08004b;
        public static final int process=0x7f080074;
        public static final int process_name=0x7f080091;
        public static final int process_name_header=0x7f080090;
        public static final int providers=0x7f08007d;
        public static final int receivers=0x7f08007b;
        public static final int remove_default_route=0x7f080040;
        public static final int restart=0x7f080073;
        public static final int routed_http_request=0x7f080045;
        public static final int routed_socket_request=0x7f080046;
        public static final int sc_wifi_cycles_done=0x7f080039;
        public static final int sc_wifi_off_duration=0x7f080038;
        public static final int sc_wifi_on_duration=0x7f080037;
        public static final int separator=0x7f08004a;
        public static final int separator2=0x7f080051;
        public static final int services=0x7f08007c;
        public static final int shared_pkgs=0x7f08008d;
        public static final int shared_pkgs_label=0x7f08008c;
        public static final int shared_pkgs_panel=0x7f08008b;
        public static final int show_background=0x7f080055;
        public static final int show_cpu=0x7f080053;
        public static final int show_load=0x7f08004c;
        public static final int show_sleep=0x7f080056;
        public static final int show_updates=0x7f08004d;
        public static final int show_xmpp=0x7f08005a;
        public static final int source=0x7f080078;
        public static final int source_uid=0x7f08008a;
        public static final int source_uid_label=0x7f080089;
        public static final int start=0x7f080067;
        public static final int startDelayedCycle=0x7f080030;
        public static final int startScreenCycle=0x7f080035;
        public static final int start_hipri=0x7f08003c;
        public static final int start_mms=0x7f08003a;
        public static final int start_sync_button=0x7f08009f;
        public static final int stateNotNeeded=0x7f080099;
        public static final int status_text_view=0x7f0800a1;
        public static final int stopDelayedCycle=0x7f080031;
        public static final int stopScreenCycle=0x7f080036;
        public static final int stop_hipri=0x7f08003d;
        public static final int stop_mms=0x7f08003b;
        public static final int strictmode_visual=0x7f08004e;
        public static final int sync_adapters_spinner=0x7f08009b;
        public static final int sync_adapters_spinner_label=0x7f08009a;
        public static final int system=0x7f08006f;
        public static final int task=0x7f080076;
        public static final int taskAffinity=0x7f080095;
        public static final int text=0x7f08002d;
        public static final int title=0x7f080062;
        public static final int transition_animation_scale=0x7f080058;
        public static final int uid=0x7f080075;
        public static final int unbind_button=0x7f08009d;
        public static final int url_edit_text=0x7f08005c;
        public static final int version=0x7f080077;
        public static final int wait_for_debugger=0x7f080049;
        public static final int window_animation_scale=0x7f080057;
        public static final int window_orientation_listener_log=0x7f08005b;
    }
    public static final class layout {
        public static final int account_list_context_menu=0x7f040000;
        public static final int account_list_item=0x7f040001;
        public static final int account_list_view=0x7f040002;
        public static final int accounts_tester=0x7f040003;
        public static final int application_hw_pref=0x7f040004;
        public static final int bad_behavior=0x7f040005;
        public static final int configuration_viewer=0x7f040006;
        public static final int connectivity=0x7f040007;
        public static final int development_settings=0x7f040008;
        public static final int enter_url=0x7f040009;
        public static final int get_auth_token_view=0x7f04000a;
        public static final int get_features_view=0x7f04000b;
        public static final int log_viewer=0x7f04000c;
        public static final int media_scanner_activity=0x7f04000d;
        public static final int monkey_screen=0x7f04000e;
        public static final int package_item=0x7f04000f;
        public static final int package_list_item=0x7f040010;
        public static final int package_summary=0x7f040011;
        public static final int permission_details=0x7f040012;
        public static final int pkg_list_item=0x7f040013;
        public static final int process_info=0x7f040014;
        public static final int show_activity=0x7f040015;
        public static final int sync_adapter_driver=0x7f040016;
        public static final int sync_adapter_item=0x7f040017;
        public static final int url_list=0x7f040018;
    }
    public static final class mipmap {
        public static final int ic_launcher_devtools=0x7f030000;
    }
    public static final class string {
        public static final int accounts_tester_account_context_menu_title=0x7f060085;
        public static final int accounts_tester_add_account=0x7f06007d;
        /**  AccountsTester 
         */
        public static final int accounts_tester_app_name=0x7f06007a;
        public static final int accounts_tester_clear_password=0x7f06008b;
        public static final int accounts_tester_confirm_credentials=0x7f06008a;
        public static final int accounts_tester_desired_authtokentype_label=0x7f06008d;
        public static final int accounts_tester_desired_features_label=0x7f06008e;
        public static final int accounts_tester_edit_properties=0x7f06008c;
        public static final int accounts_tester_enter_auth_token_type=0x7f060087;
        public static final int accounts_tester_enter_features=0x7f060088;
        public static final int accounts_tester_get_accounts_by_type=0x7f06007b;
        public static final int accounts_tester_get_all_accounts=0x7f06007c;
        public static final int accounts_tester_get_auth_token=0x7f060081;
        public static final int accounts_tester_get_auth_token_by_type_and_feature=0x7f060082;
        public static final int accounts_tester_invalidate_auth_token=0x7f060084;
        public static final int accounts_tester_ok_button=0x7f060086;
        public static final int accounts_tester_process_name_header=0x7f06007f;
        public static final int accounts_tester_remove_account=0x7f060080;
        public static final int accounts_tester_select_account_type=0x7f06007e;
        public static final int accounts_tester_test_has_features=0x7f060083;
        public static final int accounts_tester_update_credentials=0x7f060089;
        public static final int add_default_route=0x7f060010;
        public static final int bad_behavior_anr_activity_label=0x7f0600a8;
        public static final int bad_behavior_anr_broadcast_label=0x7f0600a9;
        public static final int bad_behavior_anr_label=0x7f0600a7;
        public static final int bad_behavior_anr_service_label=0x7f0600aa;
        public static final int bad_behavior_anr_system_label=0x7f0600ab;
        /**  BadBehaviorActivity 
         */
        public static final int bad_behavior_crash_main_label=0x7f0600a2;
        public static final int bad_behavior_crash_native_label=0x7f0600a4;
        public static final int bad_behavior_crash_system_label=0x7f0600a5;
        public static final int bad_behavior_crash_thread_label=0x7f0600a3;
        public static final int bad_behavior_wedge_system_label=0x7f0600ac;
        public static final int bad_behavior_wtf_label=0x7f0600a6;
        /**  SyncAdapterDriver 
         */
        public static final int bind_button=0x7f06008f;
        public static final int binding_bind_failed=0x7f06009f;
        public static final int binding_connected_format=0x7f06009d;
        public static final int binding_not_connected=0x7f06009e;
        public static final int binding_waiting_for_connection=0x7f0600a0;
        public static final int bound_http_request=0x7f060014;
        public static final int bound_socket_request=0x7f060015;
        public static final int build_date_label=0x7f06001d;
        public static final int build_host_label=0x7f060021;
        public static final int build_id_label=0x7f06001c;
        public static final int build_product_label=0x7f06001f;
        public static final int build_type_label=0x7f06001e;
        public static final int build_user_label=0x7f060020;
        public static final int cancel_sync_button=0x7f060092;
        public static final int crash=0x7f06000f;
        public static final int debuggable=0x7f06002c;
        public static final int default_request=0x7f060012;
        public static final int default_socket=0x7f060013;
        public static final int development_settings_allow_mock_location_text=0x7f06004a;
        public static final int development_settings_always_finish_text=0x7f060044;
        public static final int development_settings_compatibility_mode_text=0x7f060047;
        public static final int development_settings_compatibility_mode_toast=0x7f060048;
        public static final int development_settings_debug_app_label_text=0x7f06004e;
        public static final int development_settings_enable_gl_text=0x7f060049;
        public static final int development_settings_keep_screen_on_text=0x7f060050;
        public static final int development_settings_show_background_text=0x7f06004c;
        public static final int development_settings_show_cpu_text=0x7f060043;
        public static final int development_settings_show_load_text=0x7f060045;
        public static final int development_settings_show_sleep_text=0x7f06004f;
        public static final int development_settings_show_updates_text=0x7f060046;
        public static final int development_settings_show_xmpp_text=0x7f06004d;
        public static final int development_settings_wait_for_debugger_text=0x7f06004b;
        public static final int development_settings_window_orientation_listener_log=0x7f060051;
        public static final int device_info_asleeptime=0x7f06001b;
        public static final int device_info_awaketime=0x7f06001a;
        public static final int device_info_default=0x7f060018;
        public static final int device_info_uptime=0x7f060019;
        public static final int dialog_title_error=0x7f060070;
        public static final int disable_wifi=0x7f060003;
        /**  Package summary in Package Browser 
         */
        public static final int disabled=0x7f06002a;
        public static final int enable_wifi=0x7f060002;
        public static final int five_way_nav_label=0x7f06006d;
        public static final int gles_version_label=0x7f06006e;
        public static final int gls_tester_clear=0x7f060061;
        public static final int gls_tester_do_notification=0x7f060063;
        public static final int gls_tester_get_accounts=0x7f060060;
        public static final int gls_tester_go=0x7f060062;
        public static final int gls_tester_label=0x7f06005d;
        public static final int gls_tester_prefer_hosted=0x7f06005e;
        public static final int gls_tester_require_google=0x7f06005f;
        public static final int gls_tester_run_intent=0x7f060064;
        public static final int gls_tester_wipe_passwords=0x7f060065;
        public static final int gsm_version_baseband_label=0x7f060022;
        public static final int gsm_version_ril_impl_label=0x7f060023;
        public static final int hard_keyboard_label=0x7f06006b;
        public static final int input_method_label=0x7f06006a;
        public static final int insertbutton=0x7f0600af;
        public static final int invalid_perm_name=0x7f060071;
        public static final int launch_multiple=0x7f06003e;
        public static final int launch_singleInstance=0x7f060041;
        public static final int launch_singleTask=0x7f060040;
        public static final int launch_singleTop=0x7f06003f;
        public static final int launch_unknown=0x7f060042;
        public static final int menu_clear_exceptions=0x7f060001;
        public static final int menu_upload_exceptions=0x7f060000;
        public static final int monkey_screen_initialActivity_text=0x7f060052;
        public static final int monkey_screen_initial_activity_label=0x7f060055;
        public static final int monkey_screen_number_of_events_label=0x7f060053;
        public static final int monkey_screen_start_text=0x7f060054;
        public static final int navigation_label=0x7f06006c;
        public static final int no=0x7f06003d;
        public static final int nocode=0x7f06002d;
        /**  Activity details in Package Browser 
         */
        public static final int none=0x7f06003b;
        public static final int numsongs=0x7f0600ae;
        public static final int ok=0x7f060072;
        public static final int package_label=0x7f060068;
        public static final int package_list_header=0x7f060067;
        public static final int package_summary_activities_label=0x7f06003a;
        public static final int package_summary_data_label=0x7f060035;
        public static final int package_summary_instrumentation_label=0x7f060036;
        public static final int package_summary_process_label=0x7f060037;
        public static final int package_summary_providers_label=0x7f060039;
        public static final int package_summary_receivers_label=0x7f060034;
        public static final int package_summary_services_label=0x7f060038;
        public static final int package_summary_source_label=0x7f060033;
        public static final int package_summary_task_label=0x7f060031;
        public static final int package_summary_uid_label=0x7f060030;
        public static final int package_summary_version_label=0x7f060032;
        public static final int perm_desc_text=0x7f060073;
        public static final int perm_group_text=0x7f060074;
        public static final int perm_list_header_text=0x7f060077;
        /**  Permission details related string attribtues 
         */
        public static final int perm_name_text=0x7f06006f;
        public static final int perm_protection_text=0x7f060075;
        public static final int perm_source_text=0x7f060076;
        public static final int persistent=0x7f06002e;
        public static final int process_name_header=0x7f060066;
        public static final int radioInfo_menu_viewADN=0x7f060027;
        public static final int radioInfo_menu_viewFDN=0x7f060028;
        public static final int radioInfo_menu_viewSDN=0x7f060029;
        public static final int red_button_behavior_label=0x7f06005c;
        public static final int refresh_networks=0x7f060026;
        public static final int remove_default_route=0x7f060011;
        public static final int restart=0x7f06002f;
        public static final int routed_http_request=0x7f060016;
        public static final int routed_socket_request=0x7f060017;
        /**  MediaScannerActivity 
         */
        public static final int scancard=0x7f0600ad;
        public static final int select_account_to_sync=0x7f0600a1;
        public static final int shared_pkgs_text=0x7f060079;
        public static final int show_activity_clear_on_background_label=0x7f060056;
        public static final int show_activity_multiprocess_label=0x7f06005b;
        public static final int show_activity_process_label=0x7f060058;
        public static final int show_activity_required_permission_label=0x7f06005a;
        public static final int show_activity_state_not_needed_label=0x7f060059;
        public static final int show_activity_task_affinity_label=0x7f060057;
        public static final int source_uid_text=0x7f060078;
        public static final int start_hipri=0x7f06000d;
        public static final int start_mms=0x7f06000b;
        public static final int start_screen_toggling=0x7f060009;
        public static final int start_sync_button=0x7f060091;
        public static final int start_toggling=0x7f060007;
        public static final int status_already_bound=0x7f06009b;
        public static final int status_canceled_sync=0x7f060096;
        public static final int status_received_heartbeat=0x7f060098;
        public static final int status_remote_exception_while_canceling_sync=0x7f060097;
        public static final int status_remote_exception_while_starting_sync=0x7f060095;
        public static final int status_starting_sync_format=0x7f060094;
        public static final int status_sync_adapter_not_selected=0x7f06009c;
        public static final int status_sync_failed_format=0x7f060099;
        public static final int status_sync_succeeded_format=0x7f06009a;
        public static final int stop_hipri=0x7f06000e;
        public static final int stop_mms=0x7f06000c;
        public static final int stop_screen_toggling=0x7f06000a;
        public static final int stop_toggling=0x7f060008;
        public static final int sync_adapters_spinner_label=0x7f060093;
        public static final int system=0x7f06002b;
        /**  Application configuration requirements related attributes 
         */
        public static final int touchscreen_label=0x7f060069;
        public static final int turn_off_radio=0x7f060025;
        public static final int turn_on_radio=0x7f060024;
        public static final int unbind_button=0x7f060090;
        public static final int wifi_cycles_done=0x7f060006;
        public static final int wifi_off_duration=0x7f060005;
        public static final int wifi_on_duration=0x7f060004;
        public static final int yes=0x7f06003c;
    }
    public static final class style {
        public static final int SummaryCategoryHeader=0x7f070001;
        public static final int SummaryCategoryLayout=0x7f070000;
        public static final int TextAppearance=0x7f070006;
        public static final int TextAppearance_SummaryCategoryHeader=0x7f070008;
        public static final int TextAppearance_info_label=0x7f070007;
        public static final int TextAppearance_info_value=0x7f070009;
        public static final int entry_layout=0x7f070003;
        public static final int info_label=0x7f070004;
        public static final int info_layout=0x7f070002;
        public static final int info_value=0x7f070005;
    }
}
