/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.launcher;

public final class Manifest {
    public static final class permission {
        public static final String INSTALL_SHORTCUT="com.android.launcher.permission.INSTALL_SHORTCUT";
        public static final String READ_SETTINGS="com.android.launcher.permission.READ_SETTINGS";
        public static final String UNINSTALL_SHORTCUT="com.android.launcher.permission.UNINSTALL_SHORTCUT";
        public static final String WRITE_SETTINGS="com.android.launcher.permission.WRITE_SETTINGS";
    }
}
