/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.samplesync;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  Font size used for the contact name in the editor 
 Font size used for the contact name in the editor 
         */
        public static final int contact_name_text_size=0x7f050000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int invite_contact_uri=0x7f070000;
        public static final int message=0x7f070001;
        public static final int message_bottom=0x7f070005;
        public static final int ok_button=0x7f070006;
        public static final int password_edit=0x7f070004;
        public static final int username_edit=0x7f070002;
        public static final int username_fixed=0x7f070003;
        public static final int view_group_uri=0x7f070007;
    }
    public static final class layout {
        public static final int invite_contact_activity=0x7f030000;
        public static final int login_activity=0x7f030001;
        public static final int view_group_activity=0x7f030002;
    }
    public static final class string {
        /**  Button for going to the previous screen or step 
         */
        public static final int back_button_label=0x7f060010;
        /**  Button to cancel the current operation 
         */
        public static final int cancel_button_label=0x7f060011;
        public static final int header_account_type=0x7f060014;
        /**  The label of the button to add contact to this contact provider  
         */
        public static final int invite_action_label=0x7f06001c;
        /**  The description for the invite contact flow 
         */
        public static final int invite_contact_description=0x7f06001d;
        /**  Label for this package 
         */
        public static final int label=0x7f060000;
        public static final int label_email=0x7f060019;
        public static final int label_name=0x7f060015;
        public static final int label_phone_home=0x7f060016;
        public static final int label_phone_mobile=0x7f060017;
        public static final int label_phone_work=0x7f060018;
        /**  Message shown in dialog if the username or password is invalid. 
         */
        public static final int login_activity_loginfail_text_both=0x7f06000b;
        /**  Message shown in dialog to prompt the user for their password 
         */
        public static final int login_activity_loginfail_text_pwmissing=0x7f06000d;
        /**  Message shown in dialog if the password is invalid 
         */
        public static final int login_activity_loginfail_text_pwonly=0x7f06000c;
        /** 
        Message shown if the provided account doesn't support the current
        activity.
    
         */
        public static final int login_activity_newaccount_text=0x7f06000e;
        /**  Button to sign in after entering username and password 
         */
        public static final int login_activity_ok_button=0x7f06000a;
        /**  Label above password EditText 
         */
        public static final int login_activity_password_label=0x7f060009;
        /**  Label above username EditText 
         */
        public static final int login_activity_username_label=0x7f060008;
        public static final int menu_cancel=0x7f06001b;
        public static final int menu_done=0x7f06001a;
        public static final int notification_login_error=0x7f060005;
        /**  Permission description 
         */
        public static final int permdesc_samplesyncadapterAuth=0x7f060004;
        /**  Permission description 
         */
        public static final int permdesc_samplesyncadapterAuthPassword=0x7f060002;
        /**  Permission label 
         */
        public static final int permlab_samplesyncadapterAuth=0x7f060003;
        /**  Permission label 
         */
        public static final int permlab_samplesyncadapterAuthPassword=0x7f060001;
        public static final int profile_action=0x7f060012;
        /**  Button that takes the user to the "sign in" screen 
         */
        public static final int sign_in_button_label=0x7f06000f;
        /**  Message shown in progress dialog while app connects to the server 
         */
        public static final int ui_activity_authenticating=0x7f060007;
        /**  Title string for Login activity
         */
        public static final int ui_activity_title=0x7f060006;
        /**  The label of the button to view a group 
         */
        public static final int view_group_action_label=0x7f06001e;
        /**  The description for the view group button 
         */
        public static final int view_group_description=0x7f06001f;
        public static final int view_profile=0x7f060013;
    }
    public static final class xml {
        public static final int authenticator=0x7f040000;
        public static final int contacts=0x7f040001;
        public static final int syncadapter=0x7f040002;
    }
}
