/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.providers.telephony;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher_phone=0x7f020000;
    }
    public static final class string {
        /**  Official label of the TelephonyProvider, as seen in the "Manage
         Applications" UI.  The TelephonyProvider stores configuration
         info about the carrier and cell network, and also provides
         storage for SMS and MMS messages. [CHAR LIMIT=25] 
 outdated translation 4846406803456361049 
 outdated translation 4846406803456361049 
         */
        public static final int app_label=0x7f030000;
    }
}
