/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.vcard.tests;

public final class R {
    public static final class attr {
    }
    public static final class raw {
        public static final int v21_android_custom_prop=0x7f020000;
        public static final int v21_backslash=0x7f020001;
        public static final int v21_base64_no_2_crlf=0x7f020002;
        public static final int v21_complicated=0x7f020003;
        public static final int v21_im=0x7f020004;
        public static final int v21_invalid_comment_line=0x7f020005;
        public static final int v21_invalid_multiple_line=0x7f020006;
        public static final int v21_japanese_1=0x7f020007;
        public static final int v21_japanese_2=0x7f020008;
        public static final int v21_multiple_entry=0x7f020009;
        public static final int v21_nest=0x7f02000a;
        public static final int v21_org_before_title=0x7f02000b;
        public static final int v21_pref_handling=0x7f02000c;
        public static final int v21_simple_1=0x7f02000d;
        public static final int v21_simple_2=0x7f02000e;
        public static final int v21_simple_3=0x7f02000f;
        public static final int v21_sip=0x7f020010;
        public static final int v21_title_before_org=0x7f020011;
        public static final int v21_winmo_65=0x7f020012;
        public static final int v21_x_param=0x7f020013;
        public static final int v30_comma_separated=0x7f020014;
        public static final int v30_multibyte_param=0x7f020015;
        public static final int v30_pager=0x7f020016;
        public static final int v30_pause_wait=0x7f020017;
        public static final int v30_simple=0x7f020018;
        public static final int v30_sip=0x7f020019;
        public static final int v40_sip=0x7f02001a;
        public static final int v40_sort_as=0x7f02001b;
    }
}
