/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.keychain;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int cert_chooser_install_button=0x7f050001;
        public static final int cert_chooser_install_message=0x7f050000;
        public static final int cert_item_alias=0x7f050002;
        public static final int cert_item_selected=0x7f050004;
        public static final int cert_item_subject=0x7f050003;
    }
    public static final class layout {
        public static final int cert_chooser=0x7f020000;
        public static final int cert_chooser_footer=0x7f020001;
        public static final int cert_chooser_header=0x7f020002;
        public static final int cert_item=0x7f020003;
    }
    public static final class string {
        /**  Label of button to send the allow the application certificate request 
         */
        public static final int allow_button=0x7f030007;
        public static final int app_name=0x7f030000;
        /**  Label of button to send the deny the application certificate request 
         */
        public static final int deny_button=0x7f030008;
        /**  Label of button to send the user to the CertInstaller to install a certificate 
         */
        public static final int install_new_cert_button_label=0x7f030006;
        /**  Label of button to send the user to the CertInstaller to install a certificate (arguments are constants for .pfx and .p12) 
         */
        public static final int install_new_cert_message=0x7f030005;
        /**  Used at top of dialog to identify requesting application 
         */
        public static final int requesting_application=0x7f030003;
        /**  Used at top of dialog to identify requesting server (may be host:port or just host)
         */
        public static final int requesting_server=0x7f030004;
        /**  Dialog title when no certificates were found 
         */
        public static final int title_no_certs=0x7f030001;
        /**  Dialog title when at least one certificate was found 
         */
        public static final int title_select_cert=0x7f030002;
    }
    public static final class style {
        public static final int Transparent=0x7f040000;
    }
}
