/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.weatherlistwidget;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int widget_margin_bottom=0x7f050001;
        public static final int widget_margin_left=0x7f050002;
        public static final int widget_margin_right=0x7f050003;
        public static final int widget_margin_top=0x7f050000;
    }
    public static final class drawable {
        public static final int body=0x7f020000;
        public static final int footer=0x7f020001;
        public static final int header=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int item_bg_dark=0x7f020004;
        public static final int item_bg_light=0x7f020005;
        public static final int preview=0x7f020006;
        public static final int refresh=0x7f020007;
        public static final int refresh_button=0x7f020008;
        public static final int refresh_pressed=0x7f020009;
    }
    public static final class id {
        public static final int empty_view=0x7f070004;
        public static final int footer=0x7f070005;
        public static final int header=0x7f070001;
        public static final int refresh=0x7f070002;
        public static final int weather_list=0x7f070003;
        public static final int widget_item=0x7f070000;
    }
    public static final class layout {
        public static final int dark_widget_item=0x7f030000;
        public static final int light_widget_item=0x7f030001;
        public static final int widget_layout=0x7f030002;
    }
    public static final class string {
        public static final int empty_view_text=0x7f060000;
        public static final int item_format_string=0x7f060002;
        public static final int toast_format_string=0x7f060001;
    }
    public static final class xml {
        public static final int widgetinfo=0x7f040000;
    }
}
