/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.supportv4;

public final class R {
    public static final class anim {
        public static final int decelerate_quint=0x7f040000;
        public static final int fragment_slide_left_enter=0x7f040001;
        public static final int fragment_slide_left_exit=0x7f040002;
        public static final int fragment_slide_right_enter=0x7f040003;
        public static final int fragment_slide_right_exit=0x7f040004;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int alert_dialog_icon=0x7f020000;
        public static final int app_sample_code=0x7f020001;
        public static final int blue=0x7f020003;
        public static final int green=0x7f020004;
        public static final int red=0x7f020002;
        public static final int yellow=0x7f020005;
    }
    public static final class id {
        public static final int a_item=0x7f080023;
        public static final int accessibility_state=0x7f080000;
        public static final int b_item=0x7f080024;
        public static final int c_item=0x7f080025;
        public static final int callback=0x7f08001d;
        public static final int corky=0x7f080020;
        public static final int created=0x7f080003;
        public static final int d_item=0x7f080026;
        public static final int details=0x7f08000e;
        public static final int e_item=0x7f080027;
        public static final int embedded=0x7f080002;
        public static final int embedded_land=0x7f080004;
        public static final int excl_item=0x7f08002b;
        public static final int f_item=0x7f080028;
        public static final int frag1hide=0x7f080009;
        public static final int frag2hide=0x7f08000b;
        public static final int fragment1=0x7f08000a;
        public static final int fragment2=0x7f08000c;
        public static final int g_item=0x7f080029;
        public static final int get=0x7f08001f;
        public static final int goto_first=0x7f080012;
        public static final int goto_last=0x7f080013;
        public static final int h_item=0x7f08002a;
        public static final int icon=0x7f08001a;
        public static final int inline_text=0x7f080008;
        public static final int invisible_item=0x7f080022;
        public static final int long_press=0x7f080005;
        public static final int menu1=0x7f08000f;
        public static final int menu2=0x7f080010;
        public static final int msg=0x7f080018;
        public static final int new_fragment=0x7f080017;
        public static final int pager=0x7f080011;
        public static final int progress_horizontal=0x7f080014;
        public static final int realtabcontent=0x01010000;
        public static final int restart=0x7f080015;
        public static final int results=0x7f08001e;
        public static final int saved=0x7f080019;
        public static final int show=0x7f080006;
        public static final int show_dialog=0x7f080007;
        public static final int simple_fragment=0x7f080016;
        public static final int start=0x7f08001b;
        public static final int stop=0x7f08001c;
        public static final int text=0x7f080001;
        public static final int titles=0x7f08000d;
        public static final int violet=0x7f080021;
    }
    public static final class layout {
        public static final int accessibility_delegate=0x7f030000;
        public static final int accessibility_manager=0x7f030001;
        public static final int fragment_arguments_support=0x7f030002;
        public static final int fragment_context_menu=0x7f030003;
        public static final int fragment_dialog=0x7f030004;
        public static final int fragment_dialog_or_activity=0x7f030005;
        public static final int fragment_hide_show_support=0x7f030006;
        public static final int fragment_layout_support=0x7f030007;
        public static final int fragment_menu=0x7f030008;
        public static final int fragment_pager=0x7f030009;
        public static final int fragment_pager_list=0x7f03000a;
        public static final int fragment_retain_instance=0x7f03000b;
        public static final int fragment_stack=0x7f03000c;
        public static final int fragment_tabs=0x7f03000d;
        public static final int fragment_tabs_pager=0x7f03000e;
        public static final int hello_world=0x7f03000f;
        public static final int labeled_text_edit=0x7f030010;
        public static final int list_item_icon_text=0x7f030011;
        public static final int local_service_broadcaster=0x7f030012;
        public static final int receive_result=0x7f030013;
        public static final int send_result=0x7f030014;
        public static final int simple_list_item_checkable_1=0x7f030015;
    }
    public static final class menu {
        public static final int shortcuts=0x7f070000;
    }
    public static final class string {
        public static final int accessibility_delegate_button=0x7f05003a;
        public static final int accessibility_delegate_custom_text_added=0x7f05003b;
        public static final int accessibility_delegate_instructions=0x7f050039;
        public static final int accessibility_delegate_title=0x7f050038;
        public static final int accessibility_manager_accessibility_state=0x7f050037;
        public static final int accessibility_manager_enabled_service=0x7f050036;
        public static final int accessibility_manager_instructions=0x7f050034;
        public static final int accessibility_manager_no_enabled_services=0x7f050035;
        /**  Accessibility API 
         */
        public static final int accessibility_manager_title=0x7f050033;
        public static final int activity_sample_code=0x7f050000;
        public static final int alert_dialog_cancel=0x7f050004;
        public static final int alert_dialog_ok=0x7f050003;
        public static final int alert_dialog_two_buttons_title=0x7f050002;
        public static final int corky=0x7f050007;
        public static final int first=0x7f050029;
        public static final int fragment1menu=0x7f05001e;
        public static final int fragment2menu=0x7f05001f;
        public static final int fragment_alert_dialog_support=0x7f05000b;
        public static final int fragment_arguments_embedded=0x7f05000e;
        public static final int fragment_arguments_embedded_land=0x7f05000f;
        public static final int fragment_arguments_msg=0x7f05000d;
        public static final int fragment_arguments_support=0x7f05000c;
        public static final int fragment_context_menu_msg=0x7f050013;
        public static final int fragment_context_menu_support=0x7f050012;
        public static final int fragment_custom_animation_support=0x7f050010;
        public static final int fragment_dialog_or_activity_inline=0x7f050019;
        public static final int fragment_dialog_or_activity_msg=0x7f050018;
        public static final int fragment_dialog_or_activity_support=0x7f050017;
        public static final int fragment_dialog_support=0x7f050015;
        public static final int fragment_hide_show_support=0x7f050011;
        public static final int fragment_layout_support=0x7f05001a;
        public static final int fragment_list_array_support=0x7f05001b;
        public static final int fragment_menu_msg=0x7f05001d;
        public static final int fragment_menu_support=0x7f05001c;
        public static final int fragment_pager_support=0x7f050028;
        public static final int fragment_receive_result_support=0x7f050023;
        public static final int fragment_retain_instance_msg=0x7f050021;
        public static final int fragment_retain_instance_support=0x7f050020;
        public static final int fragment_stack_support=0x7f050024;
        public static final int fragment_state_pager_support=0x7f05002b;
        public static final int fragment_tabs=0x7f050026;
        public static final int fragment_tabs_pager=0x7f050027;
        public static final int hello_world=0x7f050001;
        public static final int initial_text=0x7f050005;
        public static final int last=0x7f05002a;
        public static final int loader_cursor_support=0x7f05002c;
        public static final int loader_custom_support=0x7f05002d;
        public static final int loader_throttle_support=0x7f05002e;
        public static final int local_service_broadcaster=0x7f05002f;
        public static final int local_service_broadcaster_msg=0x7f050030;
        public static final int long_press=0x7f050014;
        public static final int new_fragment=0x7f050025;
        public static final int pick_result=0x7f050006;
        public static final int receive_result_instructions=0x7f050009;
        public static final int receive_result_result=0x7f05000a;
        public static final int restart=0x7f050022;
        public static final int show=0x7f050016;
        public static final int start_service=0x7f050031;
        public static final int stop_service=0x7f050032;
        public static final int violet=0x7f050008;
    }
    public static final class style {
        /**  Older platforms don't have Theme.Holo.DialogWhenLarge; we will define
         our own wrapper theme that uses it only when running on the appropriate
         platform version.  On older platforms, we always use the generic
         fullscreen theme, because they don't support some feature that help
         in correctly laying out an activity as a dialog. 
 For API level 11 or later, we can use the magical DialogWhenLarge theme. 
         */
        public static final int ThemeDialogWhenLarge=0x7f060001;
        /**  This is a theme that will adjust itself depending on the API version.
         The default definition is the safe one, using a theme that has always
         been defined.  Look at values-11/styles.xml for a variation that is
         selected when the holographic theme is available. 
 For API level 11 or later, the Holo theme is available and we prefer that. 
         */
        public static final int ThemeHolo=0x7f060000;
    }
    public static final class styleable {
        /**  These are the attributes that we want to retrieve for
         app/FragmentArguments.java 
 BEGIN_INCLUDE(fragment_arguments) 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #FragmentArguments_android_label com.example.android.supportv4:android_label}</code></td><td></td></tr>
           </table>
           @see #FragmentArguments_android_label
         */
        public static final int[] FragmentArguments = {
            0x01010001
        };
        /**
          <p>This symbol is the offset where the {@link com.example.android.supportv4.R.attr#android_label}
          attribute's value can be found in the {@link #FragmentArguments} array.
          @attr name android:android_label
        */
        public static final int FragmentArguments_android_label = 0;
    };
}
