/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.protips;

public final class R {
    public static final class array {
        /**  Set of tips to show the user.

         First line is the tip title, which is shown in bold on its own line.

         All subsequent text is placed into the tip body.

         The occurrence of @drawable/foo causes the bitmap drawable named "foo"
         to be displayed to the right of the tip text.

         Example for tip #1:
          _____________________________________________     \_/
         |                                             |   /._.\
         |  See all your apps.         [all_apps.png]   > U|   |U
         |  Touch the Launcher icon.                   |   |___|
         |_____________________________________________|    U U
    
         */
        public static final int tips=0x7f050000;
        /**  dial *#*#TIPS#*#* 
 do not translate 
         */
        public static final int tips2=0x7f050001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int all_apps=0x7f020000;
        public static final int droid_widget=0x7f020001;
        public static final int droid_widget_focused=0x7f020002;
        public static final int droid_widget_normal=0x7f020003;
        public static final int droid_widget_pressed=0x7f020004;
        public static final int droidman_closed=0x7f020005;
        public static final int droidman_down_closed=0x7f020006;
        public static final int droidman_down_open=0x7f020007;
        public static final int droidman_open=0x7f020008;
        public static final int icon=0x7f020009;
        public static final int preview=0x7f02000a;
        public static final int trash=0x7f02000b;
    }
    public static final class id {
        public static final int bugdroid=0x7f080001;
        public static final int tip_bubble=0x7f080000;
        public static final int tip_callout=0x7f080003;
        public static final int tip_footer=0x7f080002;
        public static final int tip_header=0x7f080004;
        public static final int tip_message=0x7f080005;
        public static final int widget=0x7f080006;
    }
    public static final class layout {
        public static final int bubble=0x7f030000;
        public static final int droid=0x7f030001;
        public static final int widget=0x7f030002;
    }
    public static final class string {
        /**  Format string for the footer of the tip bubble. Substitutions:
            %1$d - the number of the current tip
            %2$d - the total number of tips
         
         */
        public static final int pager_footer=0x7f060001;
        /**  String to cause a TTS pause after reading @string/widget_name.
         Do not translate. 
         */
        public static final int tts_pause=0x7f060002;
        /**  Name of tips widget (shown in Launcher "add widget" list) 
         */
        public static final int widget_name=0x7f060000;
    }
    public static final class style {
        public static final int TipText=0x7f070000;
        public static final int TipText_Footer=0x7f070003;
        public static final int TipText_Header=0x7f070001;
        public static final int TipText_Message=0x7f070002;
    }
    public static final class xml {
        public static final int widget_build=0x7f040000;
    }
}
