/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.locationtracker;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int clear_data_menu=0x7f060007;
        public static final int entrylist_item=0x7f060000;
        public static final int export_csv=0x7f060006;
        public static final int export_kml=0x7f060005;
        public static final int export_sub_menu=0x7f060004;
        public static final int settings_menu=0x7f060003;
        public static final int start_service_menu=0x7f060001;
        public static final int stop_service_menu=0x7f060002;
    }
    public static final class layout {
        public static final int entrylist_item=0x7f020000;
    }
    public static final class menu {
        public static final int menu=0x7f050000;
    }
    public static final class string {
        public static final int advanced_preferences=0x7f040011;
        public static final int app_label=0x7f040014;
        public static final int clear_data=0x7f040018;
        public static final int confirm_title=0x7f04001a;
        public static final int delete_confirm=0x7f040019;
        public static final int dialog_title_mindistance_preference=0x7f040009;
        public static final int dialog_title_mintime_preference=0x7f040006;
        public static final int export_csv=0x7f040017;
        public static final int export_kml=0x7f040016;
        public static final int export_sub_menu=0x7f040015;
        public static final int provider_preferences=0x7f04000a;
        public static final int settings_menu=0x7f040002;
        public static final int start_service_menu=0x7f040000;
        public static final int stop_service_menu=0x7f040001;
        public static final int summary_advanced_preference=0x7f040013;
        public static final int summary_gps_preference=0x7f04000e;
        public static final int summary_mindistance_preference=0x7f040008;
        public static final int summary_mintime_preference=0x7f040005;
        public static final int summary_network_preference=0x7f04000c;
        public static final int summary_signal_preference=0x7f040010;
        public static final int title_advanced_log_preference=0x7f040012;
        public static final int title_gps_preference=0x7f04000d;
        public static final int title_mindistance_preference=0x7f040007;
        public static final int title_mintime_preference=0x7f040004;
        public static final int title_network_preference=0x7f04000b;
        public static final int title_signal_preference=0x7f04000f;
        public static final int update_preference=0x7f040003;
    }
    public static final class xml {
        public static final int preferences=0x7f030000;
    }
}
