/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.cts.stub;

public final class Manifest {
    public static final class permission {
        public static final String TEST_GRANTED="android.app.cts.permission.TEST_GRANTED";
    }
    public static final class permission_group {
        /**  Used for PackageManager test, don't delete this permission-group 
         */
        public static final String COST_MONEY="android.permission-group.COST_MONEY";
    }
}
