/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.providers.downloads.ui;

public final class R {
    public static final class anim {
        public static final int footer_appear=0x7f050000;
        public static final int footer_disappear=0x7f050001;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int checkmark_area=0x7f060000;
    }
    public static final class drawable {
        public static final int ic_download_misc_file_type=0x7f020000;
        public static final int ic_launcher_drm_file=0x7f020001;
        public static final int ic_menu_desk_clock=0x7f020002;
    }
    public static final class id {
        public static final int date_ordered_list=0x7f090000;
        public static final int delete_download=0x7f09000d;
        public static final int domain=0x7f090008;
        public static final int download_checkbox=0x7f090005;
        public static final int download_icon=0x7f090006;
        public static final int download_title=0x7f090007;
        public static final int empty=0x7f090002;
        public static final int last_modified_date=0x7f090009;
        public static final int share_download=0x7f09000c;
        public static final int size_ordered_list=0x7f090001;
        public static final int size_text=0x7f09000b;
        public static final int sort_button=0x7f090004;
        public static final int sort_menu=0x7f090003;
        public static final int status_text=0x7f09000a;
    }
    public static final class layout {
        public static final int download_list=0x7f040000;
        public static final int download_list_item=0x7f040001;
        public static final int list_group_header=0x7f040002;
    }
    public static final class menu {
        public static final int download_menu=0x7f080000;
    }
    public static final class mipmap {
        public static final int ic_launcher_download=0x7f030000;
    }
    public static final class string {
        /**  The name of the application that appears in the launcher [CHAR LIMIT=15] 
         */
        public static final int app_label=0x7f070000;
        /**  Button to display sort-by-date option [CHAR LIMIT=25] 
         */
        public static final int button_sort_by_date=0x7f070006;
        /**  Button to display sort-by-size option [CHAR LIMIT=25] 
         */
        public static final int button_sort_by_size=0x7f070005;
        /**  Text for button to cancel a download that is currently in progress [CHAR LIMIT=25] 
         */
        public static final int cancel_running_download=0x7f070019;
        /**  Text for button to delete a download that has completed, or to delete multiple download
         entries [CHAR LIMIT=25] 
         */
        public static final int delete_download=0x7f070017;
        /**  Text for button appearing in the pop-up selection menu to deselect all currently selected
    downloads in the download list [CHAR LIMIT=25] 
         */
        public static final int deselect_all=0x7f07001b;
        /**  Text for dialog when user clicks on a download that failed because it was interrupted and
         the server doesn't support resuming downloads [CHAR LIMIT=200] 
         */
        public static final int dialog_cannot_resume=0x7f070012;
        /**  Text for dialog when user clicks on a download that failed [CHAR LIMIT=200] 
         */
        public static final int dialog_failed_body=0x7f07000c;
        /**  Text for dialog when user clicks on a download that failed because the requested
         destination file already exists [CHAR LIMIT=200] 
         */
        public static final int dialog_file_already_exists=0x7f070013;
        /**  Text for dialog when user clicks on a completed download but the file is missing
         [CHAR LIMIT=200] 
         */
        public static final int dialog_file_missing_body=0x7f07000f;
        /**  Text for dialog when user clicks on a download that failed due to insufficient space on
         the internal download cache [CHAR LIMIT=200] 
         */
        public static final int dialog_insufficient_space_on_cache=0x7f070011;
        /**  Text for dialog when user clicks on a download that failed due to insufficient space on
         external storage [CHAR LIMIT=200] 
         */
        public static final int dialog_insufficient_space_on_external=0x7f070010;
        /**  Text for dialog when user clicks on a download that failed because it was requested to go
         on the external media, which is not mounted [CHAR LIMIT=200] 
         */
        public static final int dialog_media_not_found=0x7f070014;
        /**  Text for dialog when user clicks on a download that has not yet begun, but will be started
         in the future. [CHAR LIMIT=200] 
         */
        public static final int dialog_queued_body=0x7f07000e;
        /**  Dialog/toast messages 
 Title of dialog that is shown when the user clicks a download for which no file is
         available, either because the download hasn't started or because the download failed
         [CHAR LIMIT=25] 
         */
        public static final int dialog_title_not_available=0x7f07000b;
        /**  Title for dialog when user clicks on a download that has not yet begun, but will be started
         in the future. [CHAR LIMIT=25] 
         */
        public static final int dialog_title_queued_body=0x7f07000d;
        /**  Status indicating that the download has ended without completing successfully.  Appears for
         an individual item in the download list.  [CHAR LIMIT=11] 
         */
        public static final int download_error=0x7f07000a;
        /**  Text for a toast appearing when a user clicks on a completed download, informing the user
         that there is no application on the device that can open the file that was downloaded
         [CHAR LIMIT=200] 
         */
        public static final int download_no_application_title=0x7f070015;
        /**  Status messages 
 Status indicating that the download has been queued to start in the future.  Appears for an
         individual item in the download list.  [CHAR LIMIT=11] 
         */
        public static final int download_queued=0x7f070007;
        /**  Status indicating that the system is currently downloading the file.  Appears for an
         individual item in the download list.  [CHAR LIMIT=11] 
         */
        public static final int download_running=0x7f070008;
        /**  title shown when displaying list of apps to choose from when share is clicked on
        [CHAR LIMIT = 20] 
         */
        public static final int download_share_dialog=0x7f07001e;
        /**  Status indicating that the download has completed successfully. Appears for an individual
         item in the download list.  [CHAR LIMIT=11] 
         */
        public static final int download_success=0x7f070009;
        /**  The title that appears at the top of the activity listing downloads sorted by date [CHAR LIMIT=40] 
         */
        public static final int download_title_sorted_by_date=0x7f070001;
        /**  The title that appears at the top of the activity listing downloads sorted by size [CHAR LIMIT=40] 
         */
        public static final int download_title_sorted_by_size=0x7f070002;
        /**  Text for button to keep a download that has not yet begun [CHAR LIMIT=25] 
         */
        public static final int keep_queued_download=0x7f070018;
        /**  Default title for an item in the download list for which no title was provided by the app.
         [CHAR LIMIT=20] 
         */
        public static final int missing_title=0x7f070004;
        /**  Appears in lieu of the list of downloads if there are no downloads to view
         [CHAR LIMIT=200] 
         */
        public static final int no_downloads=0x7f070003;
        /**  Buttons 
 Text for button to remove the entry for a download that has not yet begun or that has
         failed [CHAR LIMIT=25] 
         */
        public static final int remove_download=0x7f070016;
        /**  Text for button appearing in a dialog to restart a download, either one that failed or one
         for which the downloaded file is now missing [CHAR LIMIT=25] 
         */
        public static final int retry_download=0x7f07001a;
        /**  Text for menu to select all downloads in the download list [CHAR LIMIT=25] 
         */
        public static final int select_all=0x7f07001c;
        /**  number of downloads selected [CHAR LIMIT=50] 
         */
        public static final int selected_count=0x7f07001d;
    }
}
