/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.frameworks.coretests;

public final class Manifest {
    public static final class permission {
        public static final String TEST_DENIED="com.android.frameworks.coretests.permission.TEST_DENIED";
        public static final String TEST_GRANTED="com.android.frameworks.coretests.permission.TEST_GRANTED";
    }
}
