/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.frameworks.coretests;

public final class R {
    public static final class array {
        public static final int reminder_minutes_labels=0x7f060000;
    }
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int numRows=0x7f010000;
    }
    public static final class drawable {
        public static final int big_drawable_background=0x7f020000;
        public static final int bitmap_drawable=0x7f020001;
        public static final int black_square=0x7f020002;
        public static final int black_square_stretchable=0x7f020003;
        public static final int blue=0x7f02000a;
        public static final int box=0x7f020004;
        public static final int drawable_background=0x7f020005;
        public static final int green=0x7f02000b;
        public static final int red=0x7f020009;
        public static final int sym_now_playing_pause_1=0x7f020006;
        public static final int sym_now_playing_skip_backward_1=0x7f020007;
        public static final int sym_now_playing_skip_forward_1=0x7f020008;
        public static final int yellow=0x7f02000c;
    }
    public static final class id {
        public static final int a=0x7f090077;
        public static final int absolute=0x7f090068;
        public static final int absolute_layout=0x7f09001e;
        public static final int add_row_button=0x7f090002;
        public static final int afterDescendants=0x7f090013;
        public static final int animatingButton=0x7f090003;
        public static final int auto=0x7f09005e;
        public static final int autocompletetextview1=0x7f090006;
        public static final int b=0x7f090078;
        public static final int beforeDescendants=0x7f090012;
        public static final int blob=0x7f09006d;
        public static final int blocksDescendants=0x7f090014;
        public static final int body=0x7f09005c;
        public static final int bottom=0x7f090030;
        public static final int bottomBlob=0x7f090072;
        public static final int bottomLeftButton=0x7f090022;
        public static final int bottomRight=0x7f090081;
        public static final int bottomRightButton=0x7f090024;
        public static final int button=0x7f090048;
        public static final int button1=0x7f09000e;
        public static final int button2=0x7f09000f;
        public static final int button3=0x7f090010;
        public static final int button4=0x7f090039;
        public static final int button5=0x7f09003a;
        public static final int button6=0x7f09003b;
        public static final int button7=0x7f09003c;
        public static final int button8=0x7f09003d;
        public static final int button9=0x7f09003e;
        public static final int c=0x7f090079;
        public static final int cell1=0x7f090089;
        public static final int cell2=0x7f09008a;
        public static final int cell3=0x7f09008b;
        public static final int cellThenSpan=0x7f09007b;
        public static final int cell_bottom=0x7f090087;
        public static final int cell_center=0x7f090085;
        public static final int cell_top=0x7f090083;
        public static final int center=0x7f09002b;
        public static final int center_horizontal=0x7f090028;
        public static final int center_horizontal_bottom=0x7f09002e;
        public static final int change_backgrounds=0x7f090019;
        public static final int child=0x7f090098;
        public static final int child1=0x7f090051;
        public static final int child2=0x7f090052;
        public static final int child3=0x7f090053;
        public static final int child4=0x7f090054;
        public static final int childToMakeVisible=0x7f090071;
        public static final int clickableParent=0x7f090015;
        public static final int column1=0x7f090049;
        public static final int column2=0x7f09004a;
        public static final int column3=0x7f09004b;
        public static final int container=0x7f090097;
        public static final int content=0x7f09003f;
        public static final int currenttime=0x7f090009;
        public static final int data=0x7f09001f;
        public static final int dimension=0x7f090099;
        public static final int disabledButton=0x7f090016;
        public static final int disabledButtonA=0x7f090017;
        public static final int disabledButtonB=0x7f090018;
        public static final int edit=0x7f090064;
        public static final int editText=0x7f090047;
        public static final int editText1=0x7f09004f;
        public static final int editText2=0x7f090050;
        public static final int elv=0x7f090037;
        public static final int empty=0x7f090059;
        public static final int fixed_height=0x7f09007d;
        public static final int fixed_width=0x7f09007e;
        public static final int frame=0x7f090055;
        public static final int frame_layout=0x7f09001d;
        public static final int go=0x7f090011;
        public static final int gone=0x7f090096;
        public static final int grid=0x7f090031;
        public static final int group=0x7f09005f;
        public static final int hide=0x7f090056;
        public static final int image=0x7f090066;
        public static final int image_button=0x7f09006a;
        public static final int included_button=0x7f090033;
        public static final int included_button_overriden=0x7f090034;
        public static final int included_button_visibility=0x7f090035;
        public static final int included_button_with_size=0x7f090036;
        public static final int inner_list=0x7f09004c;
        public static final int invis=0x7f090095;
        public static final int layout=0x7f090005;
        public static final int left=0x7f090025;
        public static final int leftLayout=0x7f090020;
        public static final int left_bottom=0x7f09002c;
        public static final int left_center_vertical=0x7f090029;
        public static final int linear=0x7f090063;
        public static final int linear_layout=0x7f09001b;
        public static final int list=0x7f090057;
        public static final int next=0x7f09000c;
        public static final int noDimension=0x7f09009c;
        public static final int noHeight=0x7f09009b;
        public static final int noWidth=0x7f09009a;
        public static final int non_fixed_width=0x7f09007f;
        public static final int parent=0x7f090027;
        public static final int pause=0x7f09000b;
        public static final int prev=0x7f09000a;
        public static final int progress=0x7f090069;
        public static final int refDown=0x7f090094;
        public static final int refUp=0x7f090092;
        public static final int reference=0x7f090080;
        public static final int reference1=0x7f090082;
        public static final int reference2=0x7f090084;
        public static final int reference3=0x7f090086;
        public static final int relative=0x7f090067;
        public static final int relative_layout=0x7f09001c;
        public static final int reminder_remove=0x7f09004e;
        public static final int reminder_value=0x7f09004d;
        public static final int right=0x7f090026;
        public static final int right_bottom=0x7f09002d;
        public static final int right_center_vertical=0x7f09002a;
        public static final int root=0x7f090038;
        public static final int routeToField=0x7f090007;
        public static final int row=0x7f090088;
        public static final int scrollToBlob=0x7f09006c;
        public static final int scrollToRectFromBottom=0x7f090074;
        public static final int scrollToRectFromBottom2=0x7f090073;
        public static final int scrollToRectFromTop=0x7f09006e;
        public static final int scrollToRectFromTop2=0x7f09006f;
        public static final int scrollView=0x7f09006b;
        public static final int show=0x7f090008;
        public static final int simple_view=0x7f09005a;
        public static final int span=0x7f09007c;
        public static final int spanThenCell=0x7f09007a;
        public static final int spinner=0x7f09005d;
        public static final int stub_inflated=0x7f090091;
        public static final int subject=0x7f09005b;
        public static final int table=0x7f090001;
        public static final int text=0x7f090032;
        public static final int text1=0x7f090058;
        public static final int text_view=0x7f09001a;
        public static final int textviewtest_layout=0x7f09008c;
        public static final int textviewtest_textview=0x7f09008d;
        public static final int top=0x7f09002f;
        public static final int topBlob=0x7f090070;
        public static final int topLeftButton=0x7f090021;
        public static final int topRightButton=0x7f090023;
        public static final int totaltime=0x7f09000d;
        public static final int value_one=0x7f090060;
        public static final int value_three=0x7f090062;
        public static final int value_two=0x7f090061;
        public static final int victim=0x7f090093;
        public static final int view1=0x7f090041;
        public static final int view2=0x7f090042;
        public static final int view3=0x7f090043;
        public static final int view4=0x7f090044;
        public static final int view5=0x7f090045;
        public static final int view6=0x7f090046;
        public static final int viewOne=0x7f090040;
        public static final int viewStub=0x7f09008f;
        public static final int viewStubWithId=0x7f090090;
        public static final int view_attach_view=0x7f090004;
        public static final int vis=0x7f09008e;
        public static final int wb1=0x7f090075;
        public static final int wb2=0x7f090076;
        public static final int web=0x7f090065;
        public static final int webview=0x7f090000;
    }
    public static final class layout {
        public static final int accessibility_injector_test=0x7f030000;
        public static final int add_column_in_table=0x7f030001;
        public static final int animator_basic=0x7f030002;
        public static final int attach_view_test=0x7f030003;
        public static final int autocompletetextview_simple=0x7f030004;
        public static final int baseline_0width_and_weight=0x7f030005;
        public static final int baseline_buttons=0x7f030006;
        public static final int baseline_center_gravity=0x7f030007;
        public static final int brightness_limit=0x7f030008;
        public static final int descendant_focusability=0x7f030009;
        public static final int disabled=0x7f03000a;
        public static final int drawable_background_minimum_size=0x7f03000b;
        public static final int fill_in_wrap=0x7f03000c;
        public static final int focus_after_removal=0x7f03000d;
        public static final int focus_listener=0x7f03000e;
        public static final int framelayout_gravity=0x7f03000f;
        public static final int framelayout_margin=0x7f030010;
        public static final int grid_in_horizontal=0x7f030011;
        public static final int grid_in_vertical=0x7f030012;
        public static final int grid_padding=0x7f030013;
        public static final int grid_scroll_listener=0x7f030014;
        public static final int grid_thrasher=0x7f030015;
        public static final int include_button=0x7f030016;
        public static final int include_button_with_size=0x7f030017;
        public static final int include_tag=0x7f030018;
        public static final int inflated_expandablelistview=0x7f030019;
        public static final int interrogation_activity=0x7f03001a;
        public static final int layout_five=0x7f03001b;
        public static final int layout_four=0x7f03001c;
        public static final int layout_one=0x7f03001d;
        public static final int layout_six=0x7f03001e;
        public static final int layout_tag=0x7f03001f;
        public static final int layout_three=0x7f030020;
        public static final int layout_two=0x7f030021;
        public static final int linear_layout_buttons=0x7f030022;
        public static final int linear_layout_edittext_then_button=0x7f030023;
        public static final int linear_layout_grid=0x7f030024;
        public static final int linear_layout_listview_height=0x7f030025;
        public static final int linear_layout_spinner_then_button=0x7f030026;
        public static final int linear_layout_textviews=0x7f030027;
        public static final int linear_layout_weight=0x7f030028;
        public static final int list_dividers=0x7f030029;
        public static final int list_filter=0x7f03002a;
        public static final int list_in_horizontal=0x7f03002b;
        public static final int list_in_vertical=0x7f03002c;
        public static final int list_recycler_profiling=0x7f03002d;
        public static final int list_scroll_listener=0x7f03002e;
        public static final int list_take_focus_from_side=0x7f03002f;
        public static final int list_thrasher=0x7f030030;
        public static final int list_with_button_above=0x7f030031;
        public static final int list_with_disappearing_item_bug_item=0x7f030032;
        public static final int list_with_empty_view=0x7f030033;
        public static final int longpress=0x7f030034;
        public static final int mail_message=0x7f030035;
        public static final int merge_child=0x7f030036;
        public static final int merge_tag=0x7f030037;
        public static final int popup_window_visibility=0x7f030038;
        public static final int pre_draw_listener=0x7f030039;
        public static final int radiogroup_checkedchild=0x7f03003a;
        public static final int remote_view_host=0x7f03003b;
        public static final int remote_view_test_bad_1=0x7f03003c;
        public static final int remote_view_test_bad_2=0x7f03003d;
        public static final int remote_view_test_good=0x7f03003e;
        public static final int scroll_to_rect_with_internal_scroll=0x7f03003f;
        public static final int scroll_to_rectangle=0x7f030040;
        public static final int scrollview_linear_layout=0x7f030041;
        public static final int scrollview_with_webviews=0x7f030042;
        public static final int table_layout_cell_span=0x7f030043;
        public static final int table_layout_fixed_width=0x7f030044;
        public static final int table_layout_horizontal_gravity=0x7f030045;
        public static final int table_layout_vertical_gravity=0x7f030046;
        public static final int table_layout_weight=0x7f030047;
        public static final int textview_test=0x7f030048;
        public static final int translucent_background=0x7f030049;
        public static final int viewgroupchildren=0x7f03004a;
        public static final int viewstub=0x7f03004b;
        public static final int visibility=0x7f03004c;
        public static final int visibility_callback=0x7f03004d;
        public static final int weight_sum=0x7f03004e;
        public static final int with_bitmap_background=0x7f03004f;
        public static final int zero_sized=0x7f030050;
    }
    public static final class raw {
        public static final int alt_ip_only=0x7f050000;
        public static final int history_v1=0x7f050001;
        public static final int install=0x7f050002;
        public static final int install_app1_cert1=0x7f050003;
        public static final int install_app1_cert1_cert2=0x7f050004;
        public static final int install_app1_cert2=0x7f050005;
        public static final int install_app1_cert3=0x7f050006;
        public static final int install_app1_cert3_cert4=0x7f050007;
        public static final int install_app1_unsigned=0x7f050008;
        public static final int install_app2_cert1=0x7f050009;
        public static final int install_app2_cert1_cert2=0x7f05000a;
        public static final int install_app2_cert2=0x7f05000b;
        public static final int install_app2_cert3=0x7f05000c;
        public static final int install_app2_unsigned=0x7f05000d;
        public static final int install_decl_perm=0x7f05000e;
        public static final int install_loc_auto=0x7f05000f;
        public static final int install_loc_internal=0x7f050010;
        public static final int install_loc_sdcard=0x7f050011;
        public static final int install_loc_unspecified=0x7f050012;
        public static final int install_shared1_cert1=0x7f050013;
        public static final int install_shared1_cert1_cert2=0x7f050014;
        public static final int install_shared1_cert2=0x7f050015;
        public static final int install_shared1_unsigned=0x7f050016;
        public static final int install_shared2_cert1=0x7f050017;
        public static final int install_shared2_cert1_cert2=0x7f050018;
        public static final int install_shared2_cert2=0x7f050019;
        public static final int install_shared2_unsigned=0x7f05001a;
        public static final int install_use_perm_good=0x7f05001b;
        public static final int install_uses_feature=0x7f05001c;
        public static final int medium=0x7f05001d;
        public static final int net_dev_typical=0x7f05001e;
        public static final int obb_enc_file100_orig1=0x7f05001f;
        public static final int obb_enc_file100_orig3=0x7f050020;
        public static final int obb_file1=0x7f050021;
        public static final int obb_file2=0x7f050022;
        public static final int obb_file2_nosign=0x7f050023;
        public static final int obb_file3=0x7f050024;
        public static final int obb_file3_bad_packagename=0x7f050025;
        public static final int small=0x7f050026;
        public static final int subject_alt_only=0x7f050027;
        public static final int subject_only=0x7f050028;
        public static final int subject_with_alt_names=0x7f050029;
        public static final int subject_with_wild_alt_name=0x7f05002a;
        public static final int test1=0x7f05002b;
        public static final int test1_nosig=0x7f05002c;
        public static final int test1_wrongpackage=0x7f05002d;
        public static final int text=0x7f05002e;
        public static final int wild_alt_name_only=0x7f05002f;
        public static final int xt_qtaguid_extended=0x7f050030;
        public static final int xt_qtaguid_iface_typical=0x7f050031;
        public static final int xt_qtaguid_typical=0x7f050032;
        public static final int xt_qtaguid_typical_with_set=0x7f050033;
    }
    public static final class string {
        /**  Misc. 
         */
        public static final int add_row_button=0x7f07003a;
        public static final int app_name=0x7f070000;
        /**  InterrogationActivity 
         */
        public static final int button1=0x7f07004e;
        public static final int button2=0x7f07004f;
        public static final int button3=0x7f070050;
        public static final int button4=0x7f070051;
        public static final int button5=0x7f070052;
        public static final int button6=0x7f070053;
        public static final int button7=0x7f070054;
        public static final int button8=0x7f070055;
        public static final int button9=0x7f070056;
        /**  List with button above 
         */
        public static final int button_above_list_label=0x7f07002e;
        public static final int cancel=0x7f07002b;
        public static final int change_backgrounds=0x7f070036;
        public static final int disabled_button=0x7f07003b;
        /**  List with empty view 
         */
        public static final int empty_list=0x7f070037;
        public static final int enter_title=0x7f07002c;
        public static final int enter_url=0x7f07002d;
        public static final int go=0x7f07003f;
        public static final int hide=0x7f07003e;
        public static final int include_button=0x7f070041;
        public static final int include_label=0x7f070040;
        public static final int keypad_eight=0x7f07000c;
        public static final int keypad_five=0x7f070009;
        public static final int keypad_four=0x7f070008;
        public static final int keypad_nine=0x7f07000d;
        /**  Strings for the 12 key dialer 
         */
        public static final int keypad_one=0x7f070005;
        public static final int keypad_pound=0x7f070010;
        public static final int keypad_seven=0x7f07000b;
        public static final int keypad_six=0x7f07000a;
        public static final int keypad_star=0x7f07000f;
        public static final int keypad_three=0x7f070007;
        public static final int keypad_two=0x7f070006;
        public static final int keypad_zero=0x7f07000e;
        public static final int layout_five_text_text=0x7f070043;
        public static final int layout_four_text_text=0x7f070044;
        public static final int layout_six_text_text=0x7f070045;
        public static final int left_bottom=0x7f070002;
        /**  FocusAfterRemoval 
         */
        public static final int left_top=0x7f070001;
        public static final int linear_listheight_fill=0x7f070031;
        /**  Linear Layout show/hide & sizing 
         */
        public static final int linear_listheight_fixed=0x7f070030;
        public static final int linear_listheight_hide=0x7f070032;
        public static final int menu_add=0x7f070038;
        public static final int menu_remove=0x7f070039;
        public static final int menu_test=0x7f070046;
        public static final int metadata_text=0x7f070047;
        /**  Drawable 
         */
        public static final int minimal_text=0x7f070035;
        public static final int permdesc_testDenied=0x7f07004b;
        public static final int permdesc_testGranted=0x7f070049;
        public static final int permlab_testDenied=0x7f07004a;
        public static final int permlab_testGranted=0x7f070048;
        public static final int right_bottom=0x7f070004;
        public static final int right_top=0x7f070003;
        public static final int scroll_bottom_button=0x7f070023;
        public static final int scroll_bottom_button2=0x7f070022;
        public static final int scroll_to_me=0x7f070021;
        /**  scroll_to_rectangle 
         */
        public static final int scroll_top_button=0x7f07001f;
        public static final int scroll_top_button2=0x7f070020;
        public static final int searchable_hint=0x7f07004d;
        public static final int searchable_label=0x7f07004c;
        /**  Baseline 
         */
        public static final int show=0x7f070033;
        /**  List take focus from side 
         */
        public static final int side_button_label=0x7f07002f;
        public static final int submit=0x7f07002a;
        /**  CellSpan 
         */
        public static final int table_layout_a=0x7f070017;
        public static final int table_layout_b=0x7f070018;
        public static final int table_layout_c=0x7f070019;
        public static final int table_layout_d=0x7f07001a;
        public static final int table_layout_e=0x7f07001b;
        public static final int table_layout_export=0x7f070015;
        public static final int table_layout_export_shortcut=0x7f070016;
        public static final int table_layout_f=0x7f07001c;
        public static final int table_layout_g=0x7f07001d;
        public static final int table_layout_h=0x7f07001e;
        /**  HorizontalGravity 
         */
        public static final int table_layout_open=0x7f070011;
        public static final int table_layout_open_shortcut=0x7f070012;
        public static final int table_layout_save_as=0x7f070013;
        public static final int table_layout_save_as_shortcut=0x7f070014;
        public static final int text=0x7f07003d;
        public static final int textview_hebrew_text=0x7f070057;
        public static final int time=0x7f070034;
        public static final int translucent_background=0x7f07003c;
        public static final int view=0x7f070042;
        public static final int visibility_1_gone=0x7f070029;
        public static final int visibility_1_invis=0x7f070028;
        /**  Visibility 
         */
        public static final int visibility_1_view_1=0x7f070024;
        public static final int visibility_1_view_2=0x7f070025;
        public static final int visibility_1_view_3=0x7f070026;
        public static final int visibility_1_vis=0x7f070027;
    }
    public static final class style {
        public static final int Animation=0x7f080001;
        public static final int Theme=0x7f080000;
    }
    public static final class xml {
        public static final int metadata=0x7f040000;
        public static final int metadata_app=0x7f040001;
        public static final int searchable=0x7f040002;
    }
    public static final class styleable {
        /** Attributes that can be used with a SelectableRowView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #SelectableRowView_numRows com.android.frameworks.coretests:numRows}</code></td><td></td></tr>
           </table>
           @see #SelectableRowView_numRows
         */
        public static final int[] SelectableRowView = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link com.android.frameworks.coretests.R.attr#numRows}
          attribute's value can be found in the {@link #SelectableRowView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:numRows
        */
        public static final int SelectableRowView_numRows = 0;
    };
}
