/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.stk;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int bright_foreground_dark=0x7f050001;
        public static final int ltgrey=0x7f050000;
    }
    public static final class drawable {
        public static final int ic_launcher_sim_toolkit=0x7f020000;
    }
    public static final class id {
        public static final int buttonPanel=0x7f070010;
        public static final int button_cancel=0x7f070011;
        public static final int button_no=0x7f070009;
        public static final int button_ok=0x7f070006;
        public static final int button_yes=0x7f070008;
        public static final int dialog_message=0x7f07000f;
        public static final int icon=0x7f07000a;
        public static final int in_text=0x7f070005;
        public static final int input_restriction_info=0x7f070002;
        public static final int input_type=0x7f070003;
        public static final int left_container=0x7f070013;
        public static final int message=0x7f070018;
        public static final int messagePanel=0x7f07000d;
        public static final int normal_layout=0x7f070001;
        public static final int num_of_chars=0x7f070004;
        public static final int progress_bar=0x7f070017;
        public static final int prompt=0x7f070000;
        public static final int right_container=0x7f070016;
        public static final int scrollView=0x7f07000e;
        public static final int stk_menu_title=0x7f07000c;
        public static final int stk_title=0x7f070012;
        public static final int text=0x7f07000b;
        public static final int title_icon=0x7f070014;
        public static final int title_text=0x7f070015;
        public static final int yes_no_layout=0x7f070007;
    }
    public static final class layout {
        public static final int stk_event_msg=0x7f030000;
        public static final int stk_input=0x7f030001;
        public static final int stk_menu_item=0x7f030002;
        public static final int stk_menu_list=0x7f030003;
        public static final int stk_msg_dialog=0x7f030004;
        public static final int stk_title=0x7f030005;
        public static final int stk_tone_dialog=0x7f030006;
    }
    public static final class string {
        /**  Description for the type of text allowed in a form: alphanumeric or digits only 
         */
        public static final int alphabet=0x7f06000a;
        /**  Default Application label used on home screen with an icon 
         */
        public static final int app_name=0x7f060000;
        /**  Cancel button used to dismiss a message dialog and terminate the current SIM session
         */
        public static final int button_cancel=0x7f060007;
        /**  No button, used on a Yes/No confirmation screen 
         */
        public static final int button_no=0x7f060009;
        /**  OK button used to confirm a message dialog 
         */
        public static final int button_ok=0x7f060006;
        /**  Yes button, used on a Yes/No confirmation screen 
         */
        public static final int button_yes=0x7f060008;
        /**  Default transition message when launching a call 
         */
        public static final int default_call_setup_msg=0x7f06000c;
        /**  Type of alphabet text allowed in a form: 0-9, *, #, + characters only 
         */
        public static final int digits=0x7f06000b;
        public static final int disable_app=0x7f06000f;
        public static final int enable_app=0x7f06000e;
        /**  Menu button option for requesting additional help information 
         */
        public static final int help=0x7f060002;
        /**  Menu button option to navigate back to the previous screen 
         */
        public static final int menu_back=0x7f060003;
        /**  Menu button option for ending current SIM session 
         */
        public static final int menu_end_session=0x7f060001;
        /**  Settings entry which describes the current SIM Toolkit service on the device 
         */
        public static final int service_name=0x7f060004;
        public static final int stk_app_state=0x7f06000d;
        /**  Default description for service_name when no STK service is available 
         */
        public static final int stk_no_service=0x7f060005;
    }
    public static final class xml {
        public static final int stk_settings=0x7f040000;
    }
}
