/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.providers.contacts;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
    }
    public static final class integer {
        /** 
      Maximum dimension (height or width) of contact display photos or
      photos from the social stream.
    
         */
        public static final int config_max_display_photo_dim=0x7f030000;
        /**  Maximum dimension (height or width) of contact photo thumbnails 
         */
        public static final int config_max_thumbnail_photo_dim=0x7f030001;
    }
    public static final class string {
        /**  This is the label for the application that stores contacts data 
         */
        public static final int app_label=0x7f040001;
        /**  The name of the default contact directory 
         */
        public static final int default_directory=0x7f040007;
        /**  The name of the invisible local contact directory 
         */
        public static final int local_invisible_directory=0x7f040008;
        /**  What to show in messaging that refers to this provider, e.g. AccountSyncSettings 
         */
        public static final int provider_label=0x7f040002;
        /**  Description of an application permission, listed so the user can choose whether
         they want to allow the application to do this. [CHAR LIMIT=NONE] 
         */
        public static final int read_write_all_voicemail_description=0x7f04000a;
        /**  Title of an application permission, listed so the user can choose whether they want to
     allow the application to do this.  [CHAR LIMIT=NONE] 
         */
        public static final int read_write_all_voicemail_label=0x7f040009;
        /**  Label for this app's shared user ID (and thus for all other
         apps sharing the uid). 
         */
        public static final int sharedUserLabel=0x7f040000;
        /**  [CHAR LIMIT=NONE] Boot message while upgrading contacts. 
         */
        public static final int upgrade_msg=0x7f040003;
        /**  Text for the notification shown when updating contacts fails because of memory shortage 
         */
        public static final int upgrade_out_of_memory_notification_text=0x7f040006;
        /**  Ticker for the notification shown when updating contacts fails because of memory shortage 
         */
        public static final int upgrade_out_of_memory_notification_ticker=0x7f040004;
        /**  Title for the notification shown when updating contacts fails because of memory shortage 
         */
        public static final int upgrade_out_of_memory_notification_title=0x7f040005;
        /**  The prefix string before the number used for the display name for the voicemail table.
         Because of the way this is combined in SQL we can't allow a generic format string.
         The resulting string will be this string with the number appended to the end.
         Note that the trailing space is important, and that to achieve it we have to wrap the
         string in double quotes. 
         */
        public static final int voicemail_from_column=0x7f04000b;
    }
}
