/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.gallery;

public final class R {
    public static final class anim {
        public static final int footer_appear=0x7f040000;
        public static final int footer_disappear=0x7f040001;
        public static final int slide_in=0x7f040002;
        public static final int slide_in_vertical=0x7f040003;
        public static final int slide_out=0x7f040004;
        public static final int slide_out_vertical=0x7f040005;
        public static final int transition_in=0x7f040006;
        public static final int transition_out=0x7f040007;
    }
    public static final class array {
        /**  Options in dialog that appears after selecting Picture size setting option 
         */
        public static final int pref_gallery_size_choices=0x7f090000;
        /**  Option values in dialog that appears after selecting Picture size setting option 
         */
        public static final int pref_gallery_size_values=0x7f090001;
        /**  Options in dialog that appears after selecting Slideshow interval setting option 
         */
        public static final int pref_gallery_slideshow_interval_choices=0x7f090004;
        /**  Option values in dialog that appears after selecting Slideshow interval setting option 
         */
        public static final int pref_gallery_slideshow_interval_values=0x7f090005;
        /**  Options in dialog that appears after selecting Slideshow transition
     setting option 
         */
        public static final int pref_gallery_slideshow_transition_choices=0x7f090006;
        /**  Option values in dialog that appears after selecting Slideshow transition setting option 
         */
        public static final int pref_gallery_slideshow_transition_values=0x7f090007;
        /**  Options in dialog that appears after selecting Picture sort setting option 
         */
        public static final int pref_gallery_sort_choices=0x7f090002;
        /**  Option values in dialog that appears after selecting Picture sort setting option 
         */
        public static final int pref_gallery_sort_values=0x7f090003;
    }
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int icons=0x7f010000;
        /**  Weather we keep the space in both ends 
         <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int keepEndSpace=0x7f010003;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int modes=0x7f010001;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>horizontal</code></td><td>0</td><td></td></tr>
<tr><td><code>vertical</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int orientation=0x7f010002;
    }
    public static final class color {
        public static final int bubble_dark_background=0x7f070000;
        public static final int transparent=0x7f070001;
    }
    public static final class drawable {
        public static final int appwidget_bg=0x7f020000;
        public static final int btn_camera_arrow_left=0x7f020001;
        public static final int btn_camera_arrow_left_default=0x7f020002;
        public static final int btn_camera_arrow_left_press=0x7f020003;
        public static final int btn_camera_arrow_left_selected=0x7f020004;
        public static final int btn_camera_arrow_right=0x7f020005;
        public static final int btn_camera_arrow_right_default=0x7f020006;
        public static final int btn_camera_arrow_right_press=0x7f020007;
        public static final int btn_camera_arrow_right_selected=0x7f020008;
        public static final int btn_check_buttonless_off=0x7f020009;
        public static final int btn_check_buttonless_on=0x7f02000a;
        public static final int camera_crop_height=0x7f02000b;
        public static final int camera_crop_width=0x7f02000c;
        public static final int detail_photo_border=0x7f02000d;
        public static final int frame_gallery_preview=0x7f02000e;
        public static final int frame_gallery_preview_album=0x7f02000f;
        public static final int frame_gallery_preview_album_mask=0x7f020010;
        public static final int frame_gallery_preview_album_pressed=0x7f020011;
        public static final int frame_gallery_preview_album_selected=0x7f020012;
        public static final int frame_overlay_gallery_camera=0x7f020013;
        public static final int frame_overlay_gallery_folder=0x7f020014;
        public static final int frame_overlay_gallery_video=0x7f020015;
        public static final int grid_background=0x7f020016;
        public static final int ic_btn_actionmenu_attach_default=0x7f020017;
        public static final int ic_btn_actionmenu_attach_pressed=0x7f020018;
        public static final int ic_btn_actionmenu_attach_selected=0x7f020019;
        public static final int ic_btn_actionmenu_cancel_default=0x7f02001a;
        public static final int ic_btn_actionmenu_cancel_pressed=0x7f02001b;
        public static final int ic_btn_actionmenu_cancel_selected=0x7f02001c;
        public static final int ic_btn_actionmenu_delete_default=0x7f02001d;
        public static final int ic_btn_actionmenu_delete_pressed=0x7f02001e;
        public static final int ic_btn_actionmenu_delete_selected=0x7f02001f;
        public static final int ic_btn_actionmenu_play_default=0x7f020020;
        public static final int ic_btn_actionmenu_play_pressed=0x7f020021;
        public static final int ic_btn_actionmenu_play_selected=0x7f020022;
        public static final int ic_btn_actionmenu_set_as_default=0x7f020023;
        public static final int ic_btn_actionmenu_set_as_pressed=0x7f020024;
        public static final int ic_btn_actionmenu_set_as_selected=0x7f020025;
        public static final int ic_btn_actionmenu_share_default=0x7f020026;
        public static final int ic_btn_actionmenu_share_pressed=0x7f020027;
        public static final int ic_btn_actionmenu_share_selected=0x7f020028;
        public static final int ic_error_mms_video_overlay=0x7f020029;
        public static final int ic_gallery_empty2=0x7f02002a;
        public static final int ic_gallery_video_overlay=0x7f02002b;
        public static final int ic_launcher_camera=0x7f02002c;
        public static final int ic_launcher_gallery=0x7f02002d;
        public static final int ic_menu_3d_globe=0x7f02002e;
        public static final int ic_menu_attach=0x7f02002f;
        public static final int ic_menu_camera_play=0x7f020030;
        public static final int ic_menu_camera_video_view=0x7f020031;
        public static final int ic_menu_cancel=0x7f020032;
        public static final int ic_menu_delete=0x7f020033;
        public static final int ic_menu_multiselect_gallery=0x7f020034;
        public static final int ic_menu_set_as=0x7f020035;
        public static final int ic_menu_share=0x7f020036;
        public static final int ic_menu_view_details=0x7f020037;
        public static final int ic_missing_thumbnail_picture=0x7f020038;
        public static final int ic_missing_thumbnail_video=0x7f020039;
        public static final int image_border_bg_focus_blue=0x7f02003a;
        public static final int image_border_bg_normal=0x7f02003b;
        public static final int image_border_bg_pressed_blue=0x7f02003c;
        public static final int indicator_autocrop=0x7f02003d;
        public static final int photo_inner=0x7f02003e;
    }
    public static final class id {
        public static final int abs=0x7f060038;
        public static final int action_icon_panel=0x7f06003b;
        public static final int albums=0x7f060029;
        public static final int attach=0x7f06003f;
        public static final int button_close=0x7f060030;
        public static final int button_delete=0x7f06002f;
        public static final int button_share=0x7f06002e;
        public static final int cancel=0x7f060040;
        public static final int delete_progress=0x7f060007;
        public static final int details_bit_rate_row=0x7f06001e;
        public static final int details_bit_rate_value=0x7f06001f;
        public static final int details_codec_row=0x7f060022;
        public static final int details_codec_value=0x7f060023;
        public static final int details_date_taken_row=0x7f060024;
        public static final int details_date_taken_value=0x7f060025;
        public static final int details_duration_row=0x7f06001a;
        public static final int details_duration_value=0x7f06001b;
        public static final int details_file_size_value=0x7f06000b;
        public static final int details_format_row=0x7f060020;
        public static final int details_format_value=0x7f060021;
        public static final int details_frame_rate_row=0x7f06001c;
        public static final int details_frame_rate_value=0x7f06001d;
        public static final int details_image_title=0x7f06000a;
        public static final int details_latitude_row=0x7f060014;
        public static final int details_latitude_value=0x7f060015;
        public static final int details_location_row=0x7f060018;
        public static final int details_location_value=0x7f060019;
        public static final int details_longitude_row=0x7f060016;
        public static final int details_longitude_value=0x7f060017;
        public static final int details_make_row=0x7f06000e;
        public static final int details_make_value=0x7f06000f;
        public static final int details_model_row=0x7f060010;
        public static final int details_model_value=0x7f060011;
        public static final int details_resolution_row=0x7f06000c;
        public static final int details_resolution_value=0x7f06000d;
        public static final int details_thumbnail_image=0x7f060009;
        public static final int details_whitebalance_row=0x7f060012;
        public static final int details_whitebalance_value=0x7f060013;
        public static final int discard=0x7f060004;
        public static final int footer_organize=0x7f06002d;
        public static final int grid=0x7f06002c;
        public static final int horizontal=0x7f060000;
        public static final int image=0x7f060002;
        public static final int image1_slideShow=0x7f060036;
        public static final int image2_slideShow=0x7f060037;
        public static final int left_text=0x7f060006;
        public static final int next_image=0x7f06003a;
        public static final int no_images=0x7f06002a;
        public static final int no_pictures_image=0x7f06002b;
        public static final int photo=0x7f060033;
        public static final int play=0x7f06003d;
        public static final int prev_image=0x7f060039;
        public static final int progress_indicator=0x7f060032;
        public static final int root=0x7f060028;
        public static final int rootLayout=0x7f060034;
        public static final int save=0x7f060003;
        public static final int screen=0x7f060005;
        public static final int scroll_view=0x7f060008;
        public static final int setas=0x7f06003c;
        public static final int share=0x7f06003e;
        public static final int slideShowContainer=0x7f060035;
        public static final int surface_view=0x7f060031;
        public static final int thumbnail=0x7f060026;
        public static final int title=0x7f060027;
        public static final int vertical=0x7f060001;
    }
    public static final class layout {
        public static final int cropimage=0x7f030000;
        public static final int custom_gallery_title=0x7f030001;
        public static final int delete_image=0x7f030002;
        public static final int detailsview=0x7f030003;
        public static final int gallery_picker_item=0x7f030004;
        public static final int gallerypicker=0x7f030005;
        public static final int gallerypicker_no_images=0x7f030006;
        public static final int image_gallery=0x7f030007;
        public static final int movie_view=0x7f030008;
        public static final int photo_frame=0x7f030009;
        public static final int viewimage=0x7f03000a;
    }
    public static final class string {
        /**  General strings 
 label for the icon meaning 'show me all the images' 
         */
        public static final int all_images=0x7f080000;
        /**  label for the icon meaning 'show me all the videos' 
         */
        public static final int all_videos=0x7f080001;
        /**  button indicating that the video just taken should be accepted as an attachment 
         */
        public static final int camera_attach=0x7f080026;
        /**  button indicating that the video recording session should be canceled 
         */
        public static final int camera_cancel=0x7f080027;
        /**  button indicating that the picture just taken should be cropped 
         */
        public static final int camera_crop=0x7f080028;
        /**  label for the icon meaning 'show me all the images that were taken with the camera' 
         */
        public static final int camera_label=0x7f080002;
        /**  String indicating an action of picking a picture to use as wallpaper (e.g. set wallpaper from "Pictures") 
         */
        public static final int camera_pick_wallpaper=0x7f08002d;
        /**  button indicating that the video just taken should be played 
         */
        public static final int camera_play=0x7f080025;
        /**  button indicating that the picture just taken should be set as a contact photo, wallpaper, etc 
         */
        public static final int camera_set=0x7f080024;
        public static final int camera_setas_wallpaper=0x7f08002e;
        /**  button indicating that the picture just taken should be shared by email, mms, etc 
         */
        public static final int camera_share=0x7f080023;
        /**  button indicating that the picture just taken should be deleted 
         */
        public static final int camera_toss=0x7f080022;
        /**  Menu item to go to the settings screen 
         */
        public static final int camerasettings=0x7f080045;
        /**  menu pick to go to camera mode to capture a picture 
         */
        public static final int capture_picture=0x7f08001a;
        /**  menu pick to go to video mode to capture a video 
         */
        public static final int capture_video=0x7f08001b;
        /**  Confirmation dialog message after deleting a picture 
         */
        public static final int confirm_delete_message=0x7f08001f;
        /**  Confirmation dialog message after deleting a multiple media files 
         */
        public static final int confirm_delete_multiple_message=0x7f080021;
        /**  Confirmation dialog title after deleting a picture 
         */
        public static final int confirm_delete_title=0x7f08001e;
        /**  Confirmation dialog message after deleting a video 
         */
        public static final int confirm_delete_video_message=0x7f080020;
        /**  Text of context menu when an image is selected 
         */
        public static final int context_menu_header=0x7f080060;
        /**  button indicating that the cropped image should be reverted back to the original 
         */
        public static final int crop_discard_text=0x7f08001d;
        /**  menu pick: crop the currently selected image 
         */
        public static final int crop_label=0x7f080008;
        /**  button indicating that the cropped image should be saved 
         */
        public static final int crop_save_text=0x7f08001c;
        /**  Default option value in dialog that appears after selecting Picture size setting option 
         */
        public static final int default_value_pref_gallery_size=0x7f080034;
        /**  Default option value in dialog that appears after selecting Slideshow interval setting option 
         */
        public static final int default_value_pref_gallery_slideshow_interval=0x7f08003c;
        /**  Default option value in dialog that appears after selecting Slideshow transition setting option 
         */
        public static final int default_value_pref_gallery_slideshow_transition=0x7f080040;
        /**  Default option value in dialog that appears after selecting Picture sort setting option 
         */
        public static final int default_value_pref_gallery_sort=0x7f080038;
        /**  The messsage shown on progress dialog when deleting images 
         */
        public static final int delete_images_message=0x7f080077;
        /**  menu pick to view the details of the currently selected image 
         */
        public static final int details=0x7f080013;
        /**  Label in message of Details dialog  
         */
        public static final int details_bit_rate=0x7f080056;
        /**  Label in message of Details dialog  
         */
        public static final int details_codec=0x7f080057;
        /**  Label in message of Details dialog  
         */
        public static final int details_date_taken=0x7f080054;
        /**  Used to format image dimensions in Details dialog. e.g. 64 x 64 
         */
        public static final int details_dimension_x=0x7f080059;
        /**  Label in message of Details dialog  
         */
        public static final int details_duration=0x7f080053;
        /**  Label in message of Details dialog  
         */
        public static final int details_file_size=0x7f08004b;
        /**  Label in message of Details dialog  
         */
        public static final int details_format=0x7f080058;
        /**  Unit of measure in the Details dialog frames per second. e.g. 20 fps 
         */
        public static final int details_fps=0x7f08005c;
        /**  Label in message of Details dialog  
         */
        public static final int details_frame_rate=0x7f080055;
        /**  Used to format video duration in Details dialog. hours:minutes:seconds e.g. 0:21:30 
         */
        public static final int details_hms=0x7f08005b;
        /**  Label in message of Details dialog  
         */
        public static final int details_image_latitude=0x7f080050;
        /**  Label in message of Details dialog  
         */
        public static final int details_image_location=0x7f080052;
        /**  Label in message of Details dialog  
         */
        public static final int details_image_longitude=0x7f080051;
        /**  Label in message of Details dialog  
         */
        public static final int details_image_make=0x7f08004d;
        /**  Label in message of Details dialog  
         */
        public static final int details_image_model=0x7f08004e;
        /**  Label in message of Details dialog  
         */
        public static final int details_image_resolution=0x7f08004c;
        /**  Label in message of Details dialog  
         */
        public static final int details_image_whitebalance=0x7f08004f;
        /**  Unit of measure in the Details dialog K bits per second. e.g. 192 Kbps 
         */
        public static final int details_kbps=0x7f08005d;
        /**  Unit of measure in the Details dialog M bits per second. e.g. 2.3 Mbps 
         */
        public static final int details_mbps=0x7f08005e;
        /**  Used to format short video duration in Details dialog. minutes:seconds e.g. 00:30 
         */
        public static final int details_ms=0x7f08005a;
        /**  Details dialog "OK" button. Dismisses dialog. 
         */
        public static final int details_ok=0x7f08005f;
        /**  Title of Details dialog  
         */
        public static final int details_panel_title=0x7f08004a;
        /**  Title for the file information dialog 
         */
        public static final int file_info_title=0x7f080072;
        /**  Title for picture frame gadget to show in list of all available gadgets 
         */
        public static final int gadget_title=0x7f080071;
        /**  label for the folder that contains Camera pictures in the gallery 
         */
        public static final int gallery_camera_bucket_name=0x7f080005;
        /**  label for the folder that contains Camera videos in the gallery 
         */
        public static final int gallery_camera_media_bucket_name=0x7f080007;
        /**  label for the folder that contains Camera videos in the gallery 
         */
        public static final int gallery_camera_videos_bucket_name=0x7f080006;
        /**  label for the gallery application (displayed when the user needs to
         choose an application to pick a picture or a video) 
         */
        public static final int gallery_label=0x7f080004;
        /**  label for the 'pictures application shown in the top level 'all applications' 
         */
        public static final int gallery_picker_label=0x7f080003;
        /**  Text message indicating that there are no pictures or videos in a particular
         bucket on the SD card 
         */
        public static final int image_gallery_NoImageView_text=0x7f080046;
        /**  shown in the video player view while the video is being loaded, before it starts playing 
         */
        public static final int loading_video=0x7f08006c;
        /**  Activity label. This might show up in the activity-picker 
         */
        public static final int movieviewlabel=0x7f08006b;
        /**  Hint that appears when cropping an image with more than one face 
         */
        public static final int multiface_crop_help=0x7f080062;
        /**  menu pick to enter multiselect mode 
         */
        public static final int multiselect=0x7f080019;
        /**  Title shown on the button which will close the multiselction mode 
         */
        public static final int multiselect_cancel=0x7f080076;
        /**  The title shown on the button which will delete all the selected images 
         */
        public static final int multiselect_delete=0x7f080075;
        /**  The title shown on the button which share the selected images by gmail, mms, and etc. 
         */
        public static final int multiselect_share=0x7f080074;
        /**  Message to show when there's no lat/lng information in the image 
         */
        public static final int no_location_image=0x7f080049;
        /**  alert to the user to that an SD card must be installed before using the camera 
 outdated translation 820691042667338625 
         */
        public static final int no_storage=0x7f08000c;
        /**  Toast after trying to share multiple media files indicating that there are no applications which are capable of so doing. 
         */
        public static final int no_way_to_share=0x7f08002b;
        /**  Toast after trying to share a picture indicating that there are no applications which are capable of so doing. 
         */
        public static final int no_way_to_share_image=0x7f080029;
        /**  Toast after trying to share a video indicating that there are no applications which are capable of so doing. 
         */
        public static final int no_way_to_share_video=0x7f08002a;
        /**  alert to the user to that the SD card is too full to complete the operation 
 outdated translation 6655334407957844653 
         */
        public static final int not_enough_space=0x7f08000d;
        /**  Activity title when in the image gallery to see pictures 
         */
        public static final int photos_gallery_title=0x7f080063;
        /**  Activity title when in the image gallery to select a picture 
         */
        public static final int pick_photos_gallery_title=0x7f080064;
        /**  Activity title when in the image gallery to select a video 
         */
        public static final int pick_videos_gallery_title=0x7f080066;
        /**  Settings screen, section heading  
         */
        public static final int pref_gallery_category=0x7f08002f;
        /**  Preference summary for whether the user should be prompted form confirmation when deleting images  
         */
        public static final int pref_gallery_confirm_delete_summary=0x7f080048;
        /**  Preference title for whether the user should be prompted form confirmation when deleting images  
         */
        public static final int pref_gallery_confirm_delete_title=0x7f080047;
        /**  Title of dialog that appears after selecting Picture size setting option 
         */
        public static final int pref_gallery_size_dialogtitle=0x7f080033;
        /**  Settings screen, title for preference for image size to be used in the im 
         */
        public static final int pref_gallery_size_summary=0x7f080032;
        /**  Settings screen, setting summary text 
         */
        public static final int pref_gallery_size_title=0x7f080031;
        /**  Title of dialog that appears after selecting Slideshow interval setting option 
         */
        public static final int pref_gallery_slideshow_interval_dialogtitle=0x7f08003b;
        /**  Settings screen, setting summary text 
         */
        public static final int pref_gallery_slideshow_interval_summary=0x7f08003a;
        /**  Settings screen, setting option name 
         */
        public static final int pref_gallery_slideshow_interval_title=0x7f080039;
        /**  Settings screen, setting summary text 
         */
        public static final int pref_gallery_slideshow_repeat_summary=0x7f080042;
        /**  Settings screen, setting check box name 
         */
        public static final int pref_gallery_slideshow_repeat_title=0x7f080041;
        /**  Settings screen, setting summary text 
         */
        public static final int pref_gallery_slideshow_shuffle_summary=0x7f080044;
        /**  Settings screen, setting check box name 
         */
        public static final int pref_gallery_slideshow_shuffle_title=0x7f080043;
        /**  Title of dialog that appears after selecting Slideshow transition setting option 
         */
        public static final int pref_gallery_slideshow_transition_dialogtitle=0x7f08003f;
        /**  Settings screen, setting summary text 
         */
        public static final int pref_gallery_slideshow_transition_summary=0x7f08003e;
        /**  Settings screen, setting option name 
         */
        public static final int pref_gallery_slideshow_transition_title=0x7f08003d;
        /**  Title of dialog that appears after selecting Picture sort setting option 
         */
        public static final int pref_gallery_sort_dialogtitle=0x7f080037;
        /**  Settings screen, setting summary text 
         */
        public static final int pref_gallery_sort_summary=0x7f080036;
        /**  Settings screen, setting option name 
         */
        public static final int pref_gallery_sort_title=0x7f080035;
        /**  Settings screen, section heading  
         */
        public static final int pref_slideshow_category=0x7f080030;
        /**  menu pick: go to the preferences screen for the camera or image gallery 
         */
        public static final int preferences_label=0x7f08000a;
        /**  alert to the user to that the SD card is being disk-checked 
 outdated translation 2914969119574812666 
         */
        public static final int preparing_sd=0x7f08000e;
        /**  Movie View Start Playing dialog title 
         */
        public static final int resume_playing_message=0x7f08006e;
        /**  Movie View Start Playing button "Beginning" 
         */
        public static final int resume_playing_restart=0x7f080070;
        /**  Movie View Start Playing button "Resume from bookmark" 
         */
        public static final int resume_playing_resume=0x7f08006f;
        /**  Movie View Resume Playing dialog title 
         */
        public static final int resume_playing_title=0x7f08006d;
        /**  menu pick to rotate the currently selected image (brings up submenu) 
         */
        public static final int rotate=0x7f080015;
        /**  menu pick to rotate the currently selected image to the left 
         */
        public static final int rotate_left=0x7f080016;
        /**  menu pick to rotate the currently selected image to the right 
         */
        public static final int rotate_right=0x7f080017;
        /**  Toast/alert that the face detection is being run 
         */
        public static final int runningFaceDetection=0x7f080011;
        /**  Settings stuff 
 Toast/alert that the image is being saved to the SD card 
         */
        public static final int savingImage=0x7f080010;
        /**  Displayed in the title of the dialog for things to do with a picture that
         is to be sent to another application: 
         */
        public static final int sendImage=0x7f080067;
        /**  Displayed in the title of the dialog for things to do with a video that
         is to be sent to another application. 
         */
        public static final int sendVideo=0x7f080069;
        /**  Displayed in the title of the dialog for things to do with media files that
         are to be sent to another application: 
         */
        public static final int send_media_files=0x7f08006a;
        /**  Displayed in the title of the dialog for things to do with a picture that
         is to be "set as" (e.g. set as contact photo or set as wallpaper) 
         */
        public static final int setImage=0x7f080068;
        /**  menu pick to show the location of the currently selected image on maps
         */
        public static final int show_on_map=0x7f080014;
        /**  menu pick to start a slide show 
         */
        public static final int slide_show=0x7f080018;
        /**  Text of context menu when a video is selected 
         */
        public static final int video_context_menu_header=0x7f080061;
        /**  The video is execeed the size limit of a MMS, and suggest user to record a shorter length clip 
         */
        public static final int video_exceed_mms_limit=0x7f080073;
        /**  Menu item for playing the video. 
         */
        public static final int video_play=0x7f08002c;
        /**  Activity title when in the image gallery to see videos 
         */
        public static final int videos_gallery_title=0x7f080065;
        /**  Menu items: 
 menu pick to view the currently selected image 
         */
        public static final int view=0x7f080012;
        /**  menu pick: view the currently selected image 
         */
        public static final int view_label=0x7f080009;
        /**  alert to the user to wait for some operation to complete 
         */
        public static final int wait=0x7f08000b;
        /**  Toast/alert after saving wallpaper 
         */
        public static final int wallpaper=0x7f08000f;
    }
    public static final class style {
        public static final int OnscreenActionIcon=0x7f0a0000;
        public static final int Theme_DeleteImageDialog=0x7f0a0001;
    }
    public static final class xml {
        public static final int appwidget_info=0x7f050000;
        public static final int gallery_preferences=0x7f050001;
    }
    public static final class styleable {
        /** Attributes that can be used with a EvenlySpacedLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #EvenlySpacedLayout_keepEndSpace com.android.gallery:keepEndSpace}</code></td><td> Weather we keep the space in both ends </td></tr>
           <tr><td><code>{@link #EvenlySpacedLayout_orientation com.android.gallery:orientation}</code></td><td></td></tr>
           </table>
           @see #EvenlySpacedLayout_keepEndSpace
           @see #EvenlySpacedLayout_orientation
         */
        public static final int[] EvenlySpacedLayout = {
            0x7f010002, 0x7f010003
        };
        /**
          <p>
          @attr description
           Weather we keep the space in both ends 


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:keepEndSpace
        */
        public static final int EvenlySpacedLayout_keepEndSpace = 1;
        /**
          <p>This symbol is the offset where the {@link com.android.gallery.R.attr#orientation}
          attribute's value can be found in the {@link #EvenlySpacedLayout} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>horizontal</code></td><td>0</td><td></td></tr>
<tr><td><code>vertical</code></td><td>1</td><td></td></tr>
</table>
          @attr name android:orientation
        */
        public static final int EvenlySpacedLayout_orientation = 0;
        /** Attributes that can be used with a IconIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #IconIndicator_icons com.android.gallery:icons}</code></td><td></td></tr>
           <tr><td><code>{@link #IconIndicator_modes com.android.gallery:modes}</code></td><td></td></tr>
           </table>
           @see #IconIndicator_icons
           @see #IconIndicator_modes
         */
        public static final int[] IconIndicator = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link com.android.gallery.R.attr#icons}
          attribute's value can be found in the {@link #IconIndicator} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android:icons
        */
        public static final int IconIndicator_icons = 0;
        /**
          <p>This symbol is the offset where the {@link com.android.gallery.R.attr#modes}
          attribute's value can be found in the {@link #IconIndicator} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android:modes
        */
        public static final int IconIndicator_modes = 1;
        /** Attributes that can be used with a IconListPreference.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #IconListPreference_icons com.android.gallery:icons}</code></td><td></td></tr>
           </table>
           @see #IconListPreference_icons
         */
        public static final int[] IconListPreference = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link com.android.gallery.R.attr#icons}
          attribute's value can be found in the {@link #IconListPreference} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android:icons
        */
        public static final int IconListPreference_icons = 0;
    };
}
