/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

namespace XobotOS.Samples.SkiaTests
{

public static class @R {
    public static class @attr {
    }
    public static class @drawable {
        public const int alert_dialog_icon=0x7f020000;
        public const int apidemo_androidlogo=0x7f020001;
        public const int app_sample_code=0x7f020002;
        public const int arrow_down_float=0x7f020003;
        public const int arrow_up_float=0x7f020004;
        public const int balloons=0x7f020005;
        public const int beach=0x7f020006;
        public const int btn_check_off=0x7f020007;
        public const int btn_check_on=0x7f020008;
        public const int btn_circle_normal=0x7f020009;
        public const int btn_default_normal=0x7f02000a;
        public const int button=0x7f02000b;
        public const int ic_contact_picture=0x7f02000c;
        public const int ic_launcher_settings=0x7f02000d;
        public const int ic_popup_reminder=0x7f02000e;
        public const int icon48x48_2=0x7f02000f;
        public const int progress_circular_background=0x7f020010;
        public const int progress_particle=0x7f020011;
        public const int scrollbar_state2=0x7f020012;
        public const int star_big_on=0x7f020013;
    }
}

}
