/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.supportv13;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int alert_dialog_icon=0x7f020000;
        public static final int app_sample_code=0x7f020001;
        public static final int blue=0x7f020003;
        public static final int green=0x7f020004;
        public static final int red=0x7f020002;
        public static final int yellow=0x7f020005;
    }
    public static final class id {
        public static final int goto_first=0x7f050001;
        public static final int goto_last=0x7f050002;
        public static final int pager=0x7f050000;
        public static final int text=0x7f050003;
    }
    public static final class layout {
        public static final int fragment_pager=0x7f030000;
        public static final int fragment_pager_list=0x7f030001;
        public static final int hello_world=0x7f030002;
        public static final int simple_list_item_checkable_1=0x7f030003;
    }
    public static final class string {
        public static final int action_bar_tabs_pager=0x7f040007;
        public static final int activity_sample_code=0x7f040000;
        public static final int alert_dialog_two_buttons_title=0x7f040002;
        public static final int first=0x7f040004;
        public static final int fragment_pager_support=0x7f040003;
        public static final int fragment_state_pager_support=0x7f040006;
        public static final int hello_world=0x7f040001;
        public static final int last=0x7f040005;
    }
}
