/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.mediadump;

public final class R {
    public static final class attr {
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f030003;
        public static final int does_dump=0x7f030001;
        public static final int pause=0x7f030005;
        public static final int play=0x7f030004;
        public static final int update_settings=0x7f030002;
        public static final int video_url=0x7f030000;
    }
}
