/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.test.layout;

public final class R {
    public static final class attr {
    }
    public static final class layout {
        public static final int grid0=0x7f020000;
        public static final int grid4=0x7f020001;
        public static final int grid5=0x7f020002;
        public static final int grid6=0x7f020003;
        public static final int grid7=0x7f020004;
    }
}
