/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.cellbroadcastreceiver;

public final class R {
    public static final class array {
        /**  Entries listed in the ListPreference for allowed alert durations. [CHAR LIMIT=30] 
         */
        public static final int alert_sound_duration_entries=0x7f090000;
        /**  Do not translate. Values that are retrieved from the ListPreference.
         These must match the alert_sound_duration_entries above. 
         */
        public static final int alert_sound_duration_values=0x7f090001;
    }
    public static final class attr {
    }
    public static final class bool {
        /**  Whether to enable channel 50 settings (Brazil) 
         */
        public static final int show_brazil_settings=0x7f070002;
        /**  Whether to enable CMAS settings (United States) 
         */
        public static final int show_cmas_settings=0x7f070001;
        /**  Whether to enable ETWS settings (Japan) 
         */
        public static final int show_etws_settings=0x7f070000;
    }
    public static final class color {
        public static final int read_bgcolor=0x7f060001;
        /**  the background color used for unread broadcasts 
         */
        public static final int unread_bgcolor=0x7f060000;
    }
    public static final class drawable {
        public static final int ic_launcher_cbreceiver=0x7f020000;
        public static final int ic_warning_large=0x7f020001;
        public static final int list_item_background_read=0x7f020002;
        public static final int list_item_background_unread=0x7f020003;
        public static final int stat_color_warning=0x7f020004;
    }
    public static final class id {
        public static final int channel=0x7f0a0000;
        public static final int date=0x7f0a0001;
        public static final int message=0x7f0a0002;
    }
    public static final class layout {
        public static final int cell_broadcast_list_item=0x7f030000;
        public static final int cell_broadcast_list_screen=0x7f030001;
        public static final int delete_broadcast_dialog_view=0x7f030002;
    }
    public static final class raw {
        public static final int attention_signal=0x7f050000;
    }
    public static final class string {
        /**  Do not translate. Empty summary for alert duration (set by CellBroadcastSettings). 
         */
        public static final int alert_sound_duration_summary=0x7f08001e;
        /**  Preference title for alert sound duration list. [CHAR LIMIT=30] 
         */
        public static final int alert_sound_duration_title=0x7f08001d;
        /**  The name of the Cell Broadcast Receiver app. [CHAR LIMIT=NONE] 
         */
        public static final int app_label=0x7f080000;
        /**  Cancel button text for delete broadcast dialog. [CHAR LIMIT=25] 
         */
        public static final int button_cancel=0x7f08000b;
        /**  Delete button text for delete broadcast dialog. [CHAR LIMIT=25] 
         */
        public static final int button_delete=0x7f08000a;
        /**  Text for dismiss button in broadcast message view dialog. [CHAR LIMIT=25] 
         */
        public static final int button_dismiss=0x7f080002;
        /**  Preference category title for Brazil settings. [CHAR LIMIT=50] 
         */
        public static final int category_brazil_settings_title=0x7f08002b;
        /**  Preference category title for CMAS settings. [CHAR LIMIT=50] 
         */
        public static final int category_cmas_settings_title=0x7f080024;
        /**  Preference category title for ETWS settings. [CHAR LIMIT=50] 
         */
        public static final int category_etws_settings_title=0x7f080021;
        /**  Dialog title for all non-emergency cell broadcasts. [CHAR LIMIT=50] 
         */
        public static final int cb_other_message_identifiers=0x7f080019;
        /**  CMAS dialog title for child abduction emergency (Amber Alert). [CHAR LIMIT=50] 
         */
        public static final int cmas_amber_alert=0x7f080014;
        /**  CMAS dialog title for CMAS Exercise. [CHAR LIMIT=50] 
         */
        public static final int cmas_exercise_alert=0x7f080016;
        /**  CMAS dialog title for extreme alert. [CHAR LIMIT=50] 
         */
        public static final int cmas_extreme_alert=0x7f080012;
        /**  CMAS dialog title for operator defined use. [CHAR LIMIT=50] 
         */
        public static final int cmas_operator_defined_alert=0x7f080017;
        /**  CMAS dialog title for presidential level alert. [CHAR LIMIT=50] 
         */
        public static final int cmas_presidential_level_alert=0x7f080011;
        /**  CMAS dialog title for required monthly test. [CHAR LIMIT=50] 
         */
        public static final int cmas_required_monthly_test=0x7f080015;
        /**  CMAS dialog title for severe alert. [CHAR LIMIT=50] 
         */
        public static final int cmas_severe_alert=0x7f080013;
        /**  Delete all broadcasts confirmation dialog message. [CHAR LIMIT=NONE] 
         */
        public static final int confirm_delete_all_broadcasts=0x7f080009;
        /**  Delete broadcast confirmation dialog message. [CHAR LIMIT=NONE] 
         */
        public static final int confirm_delete_broadcast=0x7f080008;
        /**  Confirm Delete 
 Delete confirmation dialog title. [CHAR LIMIT=30] 
         */
        public static final int confirm_dialog_title=0x7f080007;
        /**  Preference category title for emergency alert settings. [CHAR LIMIT=50] 
         */
        public static final int emergency_alert_settings_title=0x7f08001a;
        /**  Preference summary for enable text-to-speech checkbox. [CHAR LIMIT=100] 
         */
        public static final int enable_alert_speech_summary=0x7f080020;
        /**  Preference title for enable text-to-speech checkbox. [CHAR LIMIT=30] 
         */
        public static final int enable_alert_speech_title=0x7f08001f;
        /**  Preference summary for enable channel 50 alerts (Brazil only). [CHAR LIMIT=100] 
         */
        public static final int enable_channel_50_alerts_summary=0x7f08002d;
        /**  Preference title for enable channel 50 alerts (Brazil only). [CHAR LIMIT=30] 
         */
        public static final int enable_channel_50_alerts_title=0x7f08002c;
        /**  Preference summary for enable CMAS amber alerts checkbox. [CHAR LIMIT=100] 
         */
        public static final int enable_cmas_amber_alerts_summary=0x7f080028;
        /**  Preference title for enable CMAS amber alerts checkbox. [CHAR LIMIT=50] 
         */
        public static final int enable_cmas_amber_alerts_title=0x7f080027;
        /**  Preference summary for enable CMAS imminent threat alerts checkbox. [CHAR LIMIT=100] 
         */
        public static final int enable_cmas_imminent_threat_alerts_summary=0x7f080026;
        /**  Preference title for enable CMAS imminent threat alerts checkbox. [CHAR LIMIT=30] 
         */
        public static final int enable_cmas_imminent_threat_alerts_title=0x7f080025;
        /**  Preference summary for enable CMAS test alerts checkbox. [CHAR LIMIT=100] 
         */
        public static final int enable_cmas_test_alerts_summary=0x7f08002a;
        /**  Preference title for enable CMAS test alerts checkbox. [CHAR LIMIT=30] 
         */
        public static final int enable_cmas_test_alerts_title=0x7f080029;
        /**  Preference summary for enable notifications checkbox. [CHAR LIMIT=50] 
         */
        public static final int enable_emergency_alerts_summary=0x7f08001c;
        /**  Preference title for enable emergency alerts checkbox. [CHAR LIMIT=30] 
         */
        public static final int enable_emergency_alerts_title=0x7f08001b;
        /**  Preference summary for enable ETWS test alerts checkbox. [CHAR LIMIT=100] 
         */
        public static final int enable_etws_test_alerts_summary=0x7f080023;
        /**  Preference title for enable ETWS test alerts checkbox. [CHAR LIMIT=30] 
         */
        public static final int enable_etws_test_alerts_title=0x7f080022;
        /**  ETWS dialog title for Earthquake and Tsunami Warning. [CHAR LIMIT=50] 
         */
        public static final int etws_earthquake_and_tsunami_warning=0x7f08000e;
        /**  ETWS dialog title for Earthquake Warning. [CHAR LIMIT=50] 
         */
        public static final int etws_earthquake_warning=0x7f08000c;
        /**  ETWS dialog title for other emergency type. [CHAR LIMIT=50] 
         */
        public static final int etws_other_emergency_type=0x7f080010;
        /**  ETWS dialog title for test message. [CHAR LIMIT=50] 
         */
        public static final int etws_test_message=0x7f08000f;
        /**  ETWS dialog title for Tsunami Warning. [CHAR LIMIT=50] 
         */
        public static final int etws_tsunami_warning=0x7f08000d;
        /**  Context menu item to delete a previously received broadcast. [CHAR LIMIT=30] 
         */
        public static final int menu_delete=0x7f080006;
        /**  Menu item for deleting all broadcasts. [CHAR LIMIT=30] 
         */
        public static final int menu_delete_all=0x7f080004;
        /**  Menu item for accessing application settings. [CHAR LIMIT=30] 
         */
        public static final int menu_preferences=0x7f080003;
        /**  Context menu item to view a previously received broadcast. [CHAR LIMIT=30] 
         */
        public static final int menu_view=0x7f080005;
        /**  Dialog title for all other message identifiers in the PWS range. [CHAR LIMIT=50] 
         */
        public static final int pws_other_message_identifiers=0x7f080018;
        /**  Label for settings screen. [CHAR LIMIT=NONE] 
         */
        public static final int sms_cb_settings=0x7f080001;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
