/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.obbapp;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int mount=0x7f040000;
        public static final int path=0x7f040005;
        public static final int path_label=0x7f040004;
        public static final int status=0x7f040003;
        public static final int status_label=0x7f040002;
        public static final int unmount=0x7f040001;
    }
    public static final class layout {
        public static final int obb_mount_activity=0x7f020000;
    }
    public static final class string {
        public static final int attempting_mount=0x7f030009;
        public static final int attempting_unmount=0x7f03000a;
        public static final int failed_to_start_mount=0x7f030007;
        public static final int failed_to_start_unmount=0x7f030008;
        public static final int mount=0x7f030001;
        public static final int obb_already_mounted=0x7f030005;
        public static final int obb_app=0x7f030000;
        public static final int obb_not_mounted=0x7f030006;
        public static final int path_label=0x7f030003;
        public static final int status_label=0x7f030004;
        public static final int unmount=0x7f030002;
    }
}
