/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.apps.tag;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int active_tag_icon=0x7f020000;
        public static final int default_contact_photo=0x7f020001;
        public static final int ic_btn_round_minus=0x7f020002;
        public static final int ic_launcher_nfc=0x7f020003;
        public static final int ic_tab_all_tags=0x7f020004;
        public static final int ic_tab_my_tag=0x7f020005;
        public static final int ic_tab_selected_all_tags=0x7f020006;
        public static final int ic_tab_selected_my_tag=0x7f020007;
        public static final int ic_tab_selected_starred=0x7f020008;
        public static final int ic_tab_starred=0x7f020009;
        public static final int ic_tab_unselected_all_tags=0x7f02000a;
        public static final int ic_tab_unselected_my_tag=0x7f02000b;
        public static final int ic_tab_unselected_starred=0x7f02000c;
        public static final int panel_background=0x7f02000d;
        public static final int tag_scan_illustration=0x7f02000e;
        public static final int title_bar_medium=0x7f02000f;
    }
    public static final class id {
        public static final int icon=0x7f080002;
        public static final int image=0x7f080000;
        public static final int list=0x7f080005;
        public static final int primary=0x7f080003;
        public static final int secondary=0x7f080004;
        public static final int text=0x7f080001;
    }
    public static final class layout {
        public static final int tag_divider=0x7f030000;
        public static final int tag_image=0x7f030001;
        public static final int tag_text=0x7f030002;
        public static final int tag_uri=0x7f030003;
        public static final int tag_viewer=0x7f030004;
    }
    public static final class raw {
        public static final int discovered_tag_notification=0x7f050000;
    }
    public static final class string {
        /**  String displayed for an action to call a phone number 
         */
        public static final int action_call=0x7f060007;
        /**  String displayed for an action to send a text message to a phone number 
         */
        public static final int action_text=0x7f060006;
        /**  The title of the NFC tag application 
         */
        public static final int app_name=0x7f060000;
        /**  Button label indicating that the user wants to delete a tag 
         */
        public static final int button_done=0x7f060005;
        /**  Message for prompting on an empty tag 
         */
        public static final int empty_tag_prompt=0x7f060008;
        /**  Action description indicating the user can import a scanned vCard 
         */
        public static final int import_vcard=0x7f060009;
        /**  String describing MIME content when it's shared with other application 
         */
        public static final int mime_display_name=0x7f06000a;
        /**  The title displayed for an empty tag 
         */
        public static final int tag_empty=0x7f060004;
        /**  The title displayed for unknown tag types 
         */
        public static final int tag_unknown=0x7f060003;
        /**  The title for the activity that shows a tag that was stored from a past scan 
         */
        public static final int title_existing_tag=0x7f060002;
        /**  The title for the activity that shows a tag that was just scanned 
         */
        public static final int title_scanned_tag=0x7f060001;
        /**  Description string for vCard messages 
         */
        public static final int vcard_title=0x7f06000b;
    }
    public static final class style {
        public static final int AboutTheme=0x7f070003;
        public static final int about_page=0x7f070001;
        public static final int about_text=0x7f070002;
        public static final int record_title=0x7f070000;
    }
    public static final class xml {
        public static final int filter_nfc=0x7f040000;
    }
}
