/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.simplewiktionary;

public final class R {
    public static final class array {
        public static final int month_names=0x7f060000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
        public static final int star_logo=0x7f020001;
        public static final int widget_bg=0x7f020002;
        public static final int widget_bg_normal=0x7f020003;
        public static final int widget_bg_pressed=0x7f020004;
        public static final int widget_bg_selected=0x7f020005;
    }
    public static final class id {
        public static final int bullet=0x7f080005;
        public static final int definition=0x7f080006;
        public static final int icon=0x7f080002;
        public static final int message=0x7f080001;
        public static final int widget=0x7f080000;
        public static final int word_title=0x7f080003;
        public static final int word_type=0x7f080004;
    }
    public static final class layout {
        public static final int widget_message=0x7f030000;
        public static final int widget_word=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int template_define_url=0x7f050003;
        public static final int template_user_agent=0x7f050001;
        public static final int template_wotd_title=0x7f050002;
        public static final int widget_error=0x7f050006;
        public static final int widget_loading=0x7f050005;
        public static final int widget_name=0x7f050004;
    }
    public static final class style {
        public static final int BulletPoint=0x7f070001;
        public static final int Text=0x7f070002;
        public static final int Text_Definition=0x7f070006;
        public static final int Text_Loading=0x7f070003;
        public static final int Text_WordTitle=0x7f070004;
        public static final int Text_WordType=0x7f070005;
        public static final int WidgetBackground=0x7f070000;
    }
    public static final class xml {
        public static final int widget_word=0x7f040000;
    }
}
