/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.gl2java;

public final class R {
    public static final class attr {
    }
    public static final class string {
        /**  Simple strings. 
         */
        public static final int gl2java_activity=0x7f020000;
    }
}
