/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.nfc;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int list=0x7f060002;
        public static final int text=0x7f060000;
        public static final int title=0x7f060001;
    }
    public static final class layout {
        public static final int tag_divider=0x7f030000;
        public static final int tag_text=0x7f030001;
        public static final int tag_viewer=0x7f030002;
    }
    public static final class raw {
        public static final int discovered_tag_notification=0x7f040000;
    }
    public static final class string {
        /**  The title of the NFC tag application 
         */
        public static final int app_name=0x7f050000;
        /**  Heading for the text of the content in the "my tag" feature. 
         */
        public static final int tag_text=0x7f050002;
        /**  The title for the activity that shows a tag that was just scanned 
         */
        public static final int title_scanned_tag=0x7f050001;
    }
}
