/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.gesture.builder;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int gesture_color=0x7f040000;
    }
    public static final class dimen {
        public static final int gesture_thumbnail_inset=0x7f050000;
        public static final int gesture_thumbnail_size=0x7f050001;
    }
    public static final class drawable {
        public static final int ic_gesturebuilder=0x7f020000;
    }
    public static final class id {
        public static final int addButton=0x7f070005;
        public static final int done=0x7f070002;
        public static final int gesture_name=0x7f070000;
        public static final int gestures_overlay=0x7f070001;
        public static final int label=0x7f070003;
        public static final int name=0x7f070004;
        public static final int reloadButton=0x7f070006;
    }
    public static final class layout {
        public static final int create_gesture=0x7f030000;
        public static final int dialog_rename=0x7f030001;
        public static final int gestures_item=0x7f030002;
        public static final int gestures_list=0x7f030003;
    }
    public static final class string {
        /**  Application name 
         */
        public static final int application_name=0x7f060000;
        /**  Label, button used to add a gesture 
         */
        public static final int button_add=0x7f060002;
        /**  Label, button used to cancel the operation of adding a gesture 
         */
        public static final int button_discard=0x7f060004;
        /**  Label, button used to save a gesture newly created 
         */
        public static final int button_done=0x7f060005;
        /**  Label, button used to reload all gestures 
         */
        public static final int button_reload=0x7f060003;
        /**  Buttons in Rename gesture dialog box 
         */
        public static final int cancel_action=0x7f06000a;
        /**  Error message, informs the user he needs to enter a name before saving a gesture 
         */
        public static final int error_missing_name=0x7f060007;
        /**  Title of the screen used to view/manage gestures 
         */
        public static final int gestures_activity=0x7f06000d;
        /**  Noun, menu item used to remove a gesture 
         */
        public static final int gestures_delete=0x7f06000f;
        /**  Message displayed when a gesture is successfully deleted 
         */
        public static final int gestures_delete_success=0x7f060010;
        /**  Message displayed when the user has no gestures 
         */
        public static final int gestures_empty=0x7f06000c;
        /**  Message, displayed when the sdcard cannot be found, 1st parameter is the name of the file that stores the gestures.  CHAR LIMIT=80 
         */
        public static final int gestures_error_loading=0x7f060013;
        /**  Message displayed when the user opens the gestures settings screen 
         */
        public static final int gestures_loading=0x7f06000b;
        /**  Noun, menu item used to rename a gesture 
         */
        public static final int gestures_rename=0x7f06000e;
        /**  Label of gesture name field in Rename gesture dialog box 
         */
        public static final int gestures_rename_label=0x7f060012;
        /**  Title of dialog box 
         */
        public static final int gestures_rename_title=0x7f060011;
        /**  Title, name of the activity used to create a gesture 
         */
        public static final int label_create_gesture=0x7f060001;
        /**  Label, prompt asking the user to enter the name of the gesture 
         */
        public static final int prompt_gesture_name=0x7f060006;
        /**  Buttons in Rename gesture dialog box 
         */
        public static final int rename_action=0x7f060009;
        /**  success message, tells the user where the gesture was saved 
         */
        public static final int save_success=0x7f060008;
    }
}
