/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.notepad;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_notes=0x7f020000;
        public static final int ic_menu_compose=0x7f020001;
        public static final int ic_menu_delete=0x7f020002;
        public static final int ic_menu_edit=0x7f020003;
        public static final int ic_menu_revert=0x7f020004;
        public static final int ic_menu_save=0x7f020005;
        public static final int live_folder_notes=0x7f020006;
    }
    public static final class id {
        public static final int context_copy=0x7f060007;
        public static final int context_delete=0x7f060008;
        public static final int context_open=0x7f060006;
        public static final int menu_add=0x7f060009;
        public static final int menu_delete=0x7f060005;
        public static final int menu_paste=0x7f06000a;
        public static final int menu_revert=0x7f060004;
        public static final int menu_save=0x7f060003;
        public static final int note=0x7f060000;
        public static final int ok=0x7f060002;
        public static final int title=0x7f060001;
    }
    public static final class layout {
        public static final int note_editor=0x7f030000;
        public static final int noteslist_item=0x7f030001;
        public static final int title_editor=0x7f030002;
    }
    public static final class menu {
        public static final int editor_options_menu=0x7f050000;
        public static final int list_context_menu=0x7f050001;
        public static final int list_options_menu=0x7f050002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int button_ok=0x7f04000d;
        public static final int error_message=0x7f040012;
        public static final int error_title=0x7f040011;
        public static final int live_folder_name=0x7f040001;
        public static final int menu_add=0x7f040006;
        public static final int menu_copy=0x7f04000b;
        public static final int menu_delete=0x7f040008;
        public static final int menu_open=0x7f040009;
        public static final int menu_paste=0x7f04000c;
        public static final int menu_revert=0x7f04000a;
        public static final int menu_save=0x7f040007;
        public static final int nothing_to_save=0x7f040013;
        public static final int resolve_edit=0x7f04000f;
        public static final int resolve_title=0x7f040010;
        public static final int text_title=0x7f04000e;
        public static final int title_create=0x7f040003;
        public static final int title_edit=0x7f040004;
        public static final int title_edit_title=0x7f040002;
        public static final int title_notes_list=0x7f040005;
    }
}
