/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.videoeditor;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int audio_loop_separator=0x7f060003;
        public static final int audio_waveform=0x7f060002;
        public static final int orange=0x7f060005;
        public static final int playhead_edge=0x7f060000;
        public static final int playhead_fill=0x7f060001;
        public static final int playhead_tick_color=0x7f060004;
    }
    public static final class dimen {
        public static final int add_audio_track_button_width=0x7f070010;
        public static final int audio_layout_height=0x7f07000c;
        public static final int handle_width=0x7f070011;
        public static final int media_layout_height=0x7f070008;
        public static final int media_layout_padding=0x7f07000f;
        public static final int overlay_layout_height=0x7f07000b;
        public static final int playhead_layout_height=0x7f07000d;
        public static final int playhead_layout_text_size=0x7f07000e;
        public static final int playhead_margin_bottom=0x7f070016;
        public static final int playhead_margin_top=0x7f070013;
        public static final int playhead_margin_top_not_ok=0x7f070015;
        public static final int playhead_margin_top_ok=0x7f070014;
        public static final int playhead_tick_height=0x7f070017;
        public static final int project_picker_column_width=0x7f070004;
        public static final int project_picker_item_container_width=0x7f070005;
        public static final int project_picker_item_font_size=0x7f070003;
        public static final int project_picker_item_height=0x7f070007;
        public static final int project_picker_item_overlay_height=0x7f070002;
        public static final int project_picker_item_overlay_horizontal_inset=0x7f070001;
        public static final int project_picker_item_overlay_vertical_inset=0x7f070000;
        public static final int project_picker_item_width=0x7f070006;
        public static final int timelime_item_horizontal_padding=0x7f070019;
        public static final int timelime_item_vertical_padding=0x7f070018;
        public static final int timelime_transition_vertical_inset=0x7f07001a;
        public static final int timeline_add_media_button_height=0x7f070009;
        public static final int timeline_add_media_button_top_padding=0x7f07000a;
        public static final int timeline_separator_height=0x7f070012;
    }
    public static final class drawable {
        public static final int activity_background=0x7f020000;
        public static final int add_audio_track=0x7f020001;
        public static final int add_clip_big=0x7f020002;
        public static final int add_transition_focused=0x7f020003;
        public static final int add_transition_normal=0x7f020004;
        public static final int add_transition_pressed=0x7f020005;
        public static final int add_transition_selector=0x7f020006;
        public static final int add_video_project_big=0x7f020007;
        public static final int background_selector=0x7f020008;
        public static final int border=0x7f020009;
        public static final int btn_arrow_left=0x7f02000a;
        public static final int btn_arrow_right=0x7f02000b;
        public static final int btn_playback_ic_next=0x7f02000c;
        public static final int btn_playback_ic_pause=0x7f02000d;
        public static final int btn_playback_ic_play=0x7f02000e;
        public static final int btn_playback_ic_prev=0x7f02000f;
        public static final int btn_playback_ic_rev=0x7f020010;
        public static final int buttons_background=0x7f020011;
        public static final int buttons_background_zoom=0x7f020012;
        public static final int effects_generic=0x7f020013;
        public static final int effects_gradient=0x7f020014;
        public static final int effects_negative=0x7f020015;
        public static final int effects_pan_zoom=0x7f020016;
        public static final int effects_sepia=0x7f020017;
        public static final int ic_clip_highlight=0x7f020018;
        public static final int ic_drag_clip=0x7f020019;
        public static final int ic_drag_clip_left=0x7f02001a;
        public static final int ic_drag_clip_right=0x7f02001b;
        public static final int ic_menu_add_clip_normal=0x7f02001c;
        public static final int ic_menu_add_effect_selector=0x7f02001d;
        public static final int ic_menu_add_effects=0x7f02001e;
        public static final int ic_menu_add_effects_disabled=0x7f02001f;
        public static final int ic_menu_add_title=0x7f020020;
        public static final int ic_menu_add_title_disabled=0x7f020021;
        public static final int ic_menu_add_title_selector=0x7f020022;
        public static final int ic_menu_add_trans_end=0x7f020023;
        public static final int ic_menu_add_trans_end_disabled=0x7f020024;
        public static final int ic_menu_add_trans_end_selector=0x7f020025;
        public static final int ic_menu_add_trans_start=0x7f020026;
        public static final int ic_menu_add_trans_start_disabled=0x7f020027;
        public static final int ic_menu_add_trans_start_selector=0x7f020028;
        public static final int ic_menu_add_video=0x7f020029;
        public static final int ic_menu_delete=0x7f02002a;
        public static final int ic_menu_delete_disabled=0x7f02002b;
        public static final int ic_menu_delete_selector=0x7f02002c;
        public static final int ic_menu_duck=0x7f02002d;
        public static final int ic_menu_edit=0x7f02002e;
        public static final int ic_menu_edit_disabled=0x7f02002f;
        public static final int ic_menu_edit_effect_selector=0x7f020030;
        public static final int ic_menu_edit_effects=0x7f020031;
        public static final int ic_menu_edit_effects_disabled=0x7f020032;
        public static final int ic_menu_edit_selector=0x7f020033;
        public static final int ic_menu_remove_effect_selector=0x7f020034;
        public static final int ic_menu_remove_effects=0x7f020035;
        public static final int ic_menu_remove_effects_disabled=0x7f020036;
        public static final int ic_menu_unmute=0x7f020037;
        public static final int ic_playhead=0x7f020038;
        public static final int item_progress_left=0x7f020039;
        public static final int item_progress_right=0x7f02003a;
        public static final int list_pressed_holo_dark=0x7f02003b;
        public static final int list_selected_holo_dark=0x7f02003c;
        public static final int overlay_background_1=0x7f02003d;
        public static final int overlay_background_2=0x7f02003e;
        public static final int playhead=0x7f02003f;
        public static final int playhead_move_not_ok=0x7f020040;
        public static final int playhead_move_ok=0x7f020041;
        public static final int project_picker_item_selector=0x7f020042;
        public static final int round_button_normal=0x7f020043;
        public static final int round_button_pressed=0x7f020044;
        public static final int surface_background=0x7f020045;
        public static final int theme_preview_film=0x7f020046;
        public static final int theme_preview_rock_and_roll=0x7f020047;
        public static final int theme_preview_surfing=0x7f020048;
        public static final int theme_preview_travel=0x7f020049;
        public static final int timeline_background_line=0x7f02004a;
        public static final int timeline_background_noline=0x7f02004b;
        public static final int timeline_item_normal=0x7f02004c;
        public static final int timeline_item_pressed=0x7f02004d;
        public static final int timeline_item_selected=0x7f02004e;
        public static final int timeline_item_selector=0x7f02004f;
        public static final int timeline_loading=0x7f020050;
        public static final int timeline_transition_normal=0x7f020051;
        public static final int timeline_transparent_normal_item_selector=0x7f020052;
        public static final int transition_alpha_contour=0x7f020053;
        public static final int transition_alpha_diagonal=0x7f020054;
        public static final int transition_crossfade=0x7f020055;
        public static final int transition_fade_black=0x7f020056;
        public static final int transition_item_selector=0x7f020057;
        public static final int transition_sliding_bottom_out_top_in=0x7f020058;
        public static final int transition_sliding_left_out_right_in=0x7f020059;
        public static final int transition_sliding_right_out_left_in=0x7f02005a;
        public static final int transition_sliding_top_out_bottom_in=0x7f02005b;
        public static final int zoom_thumb_selector=0x7f02005c;
    }
    public static final class id {
        public static final int action_add_begin_transition=0x7f08004c;
        public static final int action_add_end_transition=0x7f08004d;
        public static final int action_add_overlay=0x7f080049;
        public static final int action_bar_title=0x7f080006;
        public static final int action_change_transition=0x7f080057;
        public static final int action_delete_media_item=0x7f080054;
        public static final int action_duck=0x7f080046;
        public static final int action_edit_overlay=0x7f080055;
        public static final int action_gradient_effect=0x7f08004f;
        public static final int action_negative_effect=0x7f080051;
        public static final int action_no_effect=0x7f080052;
        public static final int action_pan_zoom_effect=0x7f08004e;
        public static final int action_remove_audio_track=0x7f080047;
        public static final int action_remove_overlay=0x7f08004a;
        public static final int action_remove_project=0x7f080056;
        public static final int action_remove_transition=0x7f080058;
        public static final int action_rendering_mode=0x7f080053;
        public static final int action_sepia_effect=0x7f080050;
        public static final int action_volume=0x7f080004;
        public static final int action_volume_icon=0x7f080005;
        public static final int add_audio_track_button=0x7f080003;
        public static final int add_left_media_item_button=0x7f080008;
        public static final int add_new_media_item_menu=0x7f08003a;
        public static final int add_right_media_item_button=0x7f08000c;
        public static final int done=0x7f080017;
        public static final int duration_left=0x7f080037;
        public static final int duration_right=0x7f080039;
        public static final int editor_next=0x7f080029;
        public static final int editor_play=0x7f080028;
        public static final int editor_prev=0x7f080026;
        public static final int editor_project_view=0x7f080023;
        public static final int editor_rewind=0x7f080027;
        public static final int editor_time=0x7f08002a;
        public static final int editor_zoom=0x7f080024;
        public static final int empty_project_progress=0x7f08000a;
        public static final int empty_project_text=0x7f08000b;
        public static final int empty_project_view=0x7f080009;
        public static final int end_rectangle=0x7f080016;
        public static final int export_option_quality=0x7f08000e;
        public static final int export_option_size=0x7f08000d;
        public static final int handle_left=0x7f080018;
        public static final int handle_right=0x7f080030;
        public static final int image_loading=0x7f080013;
        public static final int item_name=0x7f080010;
        public static final int item_preview=0x7f08000f;
        public static final int ken_burns_image=0x7f080012;
        public static final int left_view_width=0x7f080000;
        public static final int loading_progress_bar=0x7f08001a;
        public static final int loading_progress_text=0x7f08001b;
        public static final int loading_progress_view=0x7f080019;
        public static final int media_item_effect_menu=0x7f08004b;
        public static final int media_item_title_menu=0x7f080048;
        public static final int menu_item_capture_image=0x7f08003c;
        public static final int menu_item_capture_video=0x7f08003b;
        public static final int menu_item_change_aspect_ratio=0x7f080040;
        public static final int menu_item_delete_project=0x7f080043;
        public static final int menu_item_edit_project_name=0x7f080041;
        public static final int menu_item_export_movie=0x7f080042;
        public static final int menu_item_import_audio=0x7f08003f;
        public static final int menu_item_import_image=0x7f08003e;
        public static final int menu_item_import_video=0x7f08003d;
        public static final int menu_item_play_exported_movie=0x7f080044;
        public static final int menu_item_share_movie=0x7f080045;
        public static final int overlay_cancel=0x7f080022;
        public static final int overlay_change_title_template=0x7f08001e;
        public static final int overlay_generic=0x7f08001c;
        public static final int overlay_layer=0x7f08002c;
        public static final int overlay_ok=0x7f080021;
        public static final int overlay_preview=0x7f08001d;
        public static final int overlay_subtitle=0x7f080020;
        public static final int overlay_title=0x7f08001f;
        public static final int playback_buttons=0x7f080025;
        public static final int playhead_offset=0x7f080001;
        public static final int playhead_type=0x7f080002;
        public static final int projects=0x7f08002e;
        public static final int root=0x7f08002d;
        public static final int start_rectangle=0x7f080015;
        public static final int text_1=0x7f080007;
        public static final int thumbnail=0x7f08002f;
        public static final int timeline=0x7f080032;
        public static final int timeline_audio_tracks=0x7f080035;
        public static final int timeline_media=0x7f080033;
        public static final int timeline_overlays=0x7f080034;
        public static final int timeline_playhead=0x7f080036;
        public static final int timeline_scroller=0x7f080031;
        public static final int transition_duration=0x7f080038;
        public static final int video_frame_view=0x7f080011;
        public static final int video_view=0x7f08002b;
        public static final int which_rectangle=0x7f080014;
    }
    public static final class layout {
        public static final int add_audio_track_button=0x7f040000;
        public static final int audio_track_action_bar=0x7f040001;
        public static final int audio_track_item=0x7f040002;
        public static final int edit_one_dialog_view=0x7f040003;
        public static final int empty_left_timeline_item=0x7f040004;
        public static final int empty_project_layout=0x7f040005;
        public static final int empty_right_timeline_item=0x7f040006;
        public static final int empty_timeline_item=0x7f040007;
        public static final int export_options_dialog_view=0x7f040008;
        public static final int image_with_text_row_view=0x7f040009;
        public static final int ken_burns_layout=0x7f04000a;
        public static final int left_handle_view=0x7f04000b;
        public static final int list_view=0x7f04000c;
        public static final int loading_layout=0x7f04000d;
        public static final int media_item=0x7f04000e;
        public static final int overlay_item=0x7f04000f;
        public static final int overlay_title_editor=0x7f040010;
        public static final int project_layout=0x7f040011;
        public static final int project_picker=0x7f040012;
        public static final int project_picker_item=0x7f040013;
        public static final int right_handle_view=0x7f040014;
        public static final int timeline_layout=0x7f040015;
        public static final int transition_list_view=0x7f040016;
        public static final int transition_view=0x7f040017;
        public static final int video_editor=0x7f040018;
    }
    public static final class menu {
        public static final int action_bar_menu=0x7f0b0000;
        public static final int audio_mode_menu=0x7f0b0001;
        public static final int media_item_mode_menu=0x7f0b0002;
        public static final int overlay_mode_menu=0x7f0b0003;
        public static final int project_menu=0x7f0b0004;
        public static final int transition_mode_menu=0x7f0b0005;
    }
    public static final class mipmap {
        public static final int ic_launcher_moviestudio=0x7f030000;
    }
    public static final class raw {
        public static final int mask_contour=0x7f050000;
        public static final int mask_diagonal=0x7f050001;
        public static final int theme_film_audio_track=0x7f050002;
        public static final int theme_rockandroll_audio_track=0x7f050003;
        public static final int theme_surfing_audio_track=0x7f050004;
        public static final int theme_travel_audio_track=0x7f050005;
    }
    public static final class string {
        /**  Aspect ratio labels 
 Menu item aspect ratios are displayed in a single item select dialog. 
         */
        public static final int aspect_ratio_11_9=0x7f090033;
        public static final int aspect_ratio_16_9=0x7f090034;
        public static final int aspect_ratio_3_2=0x7f090035;
        public static final int aspect_ratio_4_3=0x7f090036;
        public static final int aspect_ratio_5_3=0x7f090037;
        /**  Text displayed in menu for ducking (lower background music volume
         if there is sound in foreground) [CHAR LIMIT = 20]
         */
        public static final int audio_track_menu_duck=0x7f090030;
        /**  Displayed in dialog buttons. 
         */
        public static final int done=0x7f09008b;
        /**  Displayed in dialog buttons and menu items. 
         */
        public static final int edit=0x7f09008c;
        /**  Menu text displayed for adding new media item. 
         */
        public static final int editor_add=0x7f090004;
        /**  Error message displayed in a toast if an audio track cannot be added. 
         */
        public static final int editor_add_audio_track_error=0x7f090052;
        /**  Menu item used to add a transition at the beginning of the image or video clip. 
         */
        public static final int editor_add_begin_transition=0x7f090026;
        /**  Menu item used to add an effect. 
         */
        public static final int editor_add_effect=0x7f09001e;
        /**  Error message displayed in a toast if an effect cannot be added. 
         */
        public static final int editor_add_effect_error=0x7f090050;
        /**  Menu item used to add a transition at the end of the image or video clip. 
         */
        public static final int editor_add_end_transition=0x7f090027;
        /**  Error message displayed in a toast if an error occurs if an image cannot be added to the project. 
         */
        public static final int editor_add_image_error=0x7f090042;
        /**  Menu item used to add a new title (overlay title). 
         */
        public static final int editor_add_overlay=0x7f090014;
        /**  Error message displayed in a toast if an overlay cannot be added. 
         */
        public static final int editor_add_overlay_error=0x7f09004b;
        /**  Error message displayed in a toast if a transition cannot be added. 
         */
        public static final int editor_add_transition_error=0x7f090048;
        /**  Error message displayed in a toast if an error occurs if a video clip cannot be added to the project. 
         */
        public static final int editor_add_video_clip_error=0x7f090041;
        /**  Error message displayed in a toast if a theme cannot be applied. 
         */
        public static final int editor_apply_theme_error=0x7f09003c;
        /**  Error message displayed in a toast if the aspect ratio cannot be changed. 
         */
        public static final int editor_aspect_ratio_error=0x7f09003b;
        /**  Menu item for capturing a new image. 
         */
        public static final int editor_capture_image=0x7f09000f;
        /**  Menu item for capturing a new video clip. 
         */
        public static final int editor_capture_video=0x7f09000e;
        /**  Menu item used to change the aspect ratio of the movie. 
         */
        public static final int editor_change_aspect_ratio=0x7f09000b;
        /**  Menu item used to change an effect type and/or duration. 
         */
        public static final int editor_change_effect=0x7f09001f;
        /**  Menu item used to change the rendering mode. Launches a single choice dialog. 
         */
        public static final int editor_change_rendering_mode=0x7f090018;
        /**  Menu item used to change a transition type and/or duration. 
         */
        public static final int editor_change_transition=0x7f090028;
        /**  Error message displayed in a toast if a project cannot be created. 
         */
        public static final int editor_create_error=0x7f090039;
        /**  Error message displayed in a toast if an error had occurred while releasing the project. 
         */
        public static final int editor_delete_error=0x7f090040;
        /**  Menu item used to delete the project. 
         */
        public static final int editor_delete_project=0x7f09000d;
        /**  Text displayed in the delete project confirmation dialog. 
         */
        public static final int editor_delete_project_question=0x7f090010;
        /**  Disable looping for the audio track. 
         */
        public static final int editor_disable_loop_audio_track=0x7f09002d;
        /**  Menu item used to change the overlay title. 
         */
        public static final int editor_edit_overlay=0x7f090015;
        /**  Menu item used to change the project name. 
         */
        public static final int editor_edit_project_name=0x7f09000c;
        /**  Text displayed as the header of effect menu. 
         */
        public static final int editor_effect_menu_header=0x7f09001d;
        /**  Audio tracks 
 Enable looping for the audio track. 
         */
        public static final int editor_enable_loop_audio_track=0x7f09002c;
        /**  Error message displayed in a toast if a movie cannot be applied. 
         */
        public static final int editor_export_error=0x7f09003d;
        /**  Menu item used to export the movie. 
         */
        public static final int editor_export_movie=0x7f090009;
        /**  Menu item text for effect gradient. 
         */
        public static final int editor_gradient_effect=0x7f090022;
        /**  Toast message used when an image needs to be downloaded before it can be used 
         */
        public static final int editor_image_load=0x7f09002a;
        /**  Menu item used to launch the Music song picker. 
         */
        public static final int editor_import_audio=0x7f090007;
        /**  Menu item used to launch the Gallery image picker. 
         */
        public static final int editor_import_image=0x7f090006;
        /**  Menu item used to launch the Gallery video clip picker. 
         */
        public static final int editor_import_video=0x7f090005;
        /**  Error message displayed in a toast if a project cannot be loaded. 
         */
        public static final int editor_load_error=0x7f09003a;
        /**  Displayed in the center of the activity while a project is loading. 
         */
        public static final int editor_loading_project=0x7f090002;
        /**  Error message displayed in a toast when a video clip or an image cannot be downloaded. 
         */
        public static final int editor_media_load_error=0x7f090056;
        /**  Error message displayed in a toast if video clip or an image cannot be moved in the timeline. 
         */
        public static final int editor_move_media_item_error=0x7f090043;
        /**  Mute the audio track. 
         */
        public static final int editor_mute=0x7f09002e;
        /**  Menu item text for effect negative. 
         */
        public static final int editor_negative_effect=0x7f090024;
        /**  Menu item text for no effect. 
         */
        public static final int editor_no_effect=0x7f090025;
        /**  Displayed in the center of the activity if a project could not be loaded. 
         */
        public static final int editor_no_project=0x7f090003;
        /**  Menu item text for effect pan zoom. 
         */
        public static final int editor_pan_zoom_effect=0x7f090021;
        /**  Menu item used to play the exported movie. 
         */
        public static final int editor_play_exported_movie=0x7f09000a;
        /**  Error message displayed in a toast if an error had occurred while releasing the project. 
         */
        public static final int editor_release_error=0x7f09003f;
        /**  Error message displayed in a toast if an audio track cannot be removed. 
         */
        public static final int editor_remove_audio_track_error=0x7f090053;
        /**  Text displayed in the remove audio track confirmation dialog. 
         */
        public static final int editor_remove_audio_track_question=0x7f090012;
        /**  Menu item used to remove an effect. 
         */
        public static final int editor_remove_effect=0x7f090020;
        /**  Error message displayed in a toast if an effect cannot be removed. 
         */
        public static final int editor_remove_effect_error=0x7f090051;
        /**  Text displayed in the remove effect confirmation dialog. 
         */
        public static final int editor_remove_effect_question=0x7f09001a;
        /**  Text displayed in the remove image confirmation dialog. 
         */
        public static final int editor_remove_image_question=0x7f09001c;
        /**  Error message displayed in a toast if video clip or image cannot be removed from the timeline. 
         */
        public static final int editor_remove_media_item_error=0x7f090044;
        /**  Menu item used to remove a title (overlay title). 
         */
        public static final int editor_remove_overlay=0x7f090016;
        /**  Error message displayed in a toast if an overlay cannot be removed. 
         */
        public static final int editor_remove_overlay_error=0x7f09004c;
        /**  Text displayed in the remove overlay confirmation dialog. 
         */
        public static final int editor_remove_overlay_question=0x7f090017;
        /**  Error message displayed in a toast if a transition cannot be removed. 
         */
        public static final int editor_remove_transition_error=0x7f090049;
        /**  Text displayed in the remove transition confirmation dialog. 
         */
        public static final int editor_remove_transition_question=0x7f090019;
        /**  Text displayed in the remove video clip confirmation dialog. 
         */
        public static final int editor_remove_video_question=0x7f09001b;
        /**  Error message displayed in a toast if a project cannot be saved. 
         */
        public static final int editor_saved_error=0x7f09003e;
        /**  Menu item text for effect sepia. 
         */
        public static final int editor_sepia_effect=0x7f090023;
        /**  Error message displayed in a toast if an audio track cannot be trimmed. 
         */
        public static final int editor_set_audio_track_boundaries_error=0x7f090054;
        /**  Error message displayed in a toast if an overlay duration cannot be changed. 
         */
        public static final int editor_set_duration_overlay_error=0x7f09004d;
        /**  Error message displayed in a toast if a video clip cannot be trimmed. 
         */
        public static final int editor_set_media_item_boundaries_error=0x7f090047;
        /**  Error message displayed in a toast if the image duration cannot be changed. 
         */
        public static final int editor_set_media_item_duration_error=0x7f090046;
        /**  Error message displayed in a toast if the rendering mode of an image/video clip cannot be changed. 
         */
        public static final int editor_set_rendering_mode_error=0x7f090045;
        /**  Error message displayed in a toast if an overlay start time cannot be changed. 
         */
        public static final int editor_set_start_time_overlay_error=0x7f09004e;
        /**  Error message displayed in a toast if a transition duration cannot be changed. 
         */
        public static final int editor_set_transition_duration_error=0x7f09004a;
        /**  Error message displayed in a toast if an overlay text cannot be changed. 
         */
        public static final int editor_set_user_attributes_overlay_error=0x7f09004f;
        /**  Menu item used to share the movie (e.g. to YouTube). 
         */
        public static final int editor_share_movie=0x7f090008;
        /**  Error messages 
 Error message displayed in a toast if a project cannot be created because the storage is not accessible. 
         */
        public static final int editor_storage_not_available=0x7f090038;
        /**  Menu header of title overlay menu. 
         */
        public static final int editor_title_menu_header=0x7f090013;
        /**  The title displayed in the contextual action bar when a transition is selected. 
         */
        public static final int editor_transition_title=0x7f09002b;
        /**  Error message displayed in a toast if a transition cannot be added. 
         */
        public static final int editor_transition_too_short=0x7f090055;
        /**  Unmute the audio track. 
         */
        public static final int editor_unmute=0x7f09002f;
        /**  Toast message used when a video clip needs to be downloaded before it can be used 
         */
        public static final int editor_video_load=0x7f090029;
        /**  Text displayed in the playback widget to indicate the current playhead time position [CHAR_LIMIT=11] 
         */
        public static final int editor_zero_time_stamp=0x7f090011;
        /**  Effect 5 name. 
         */
        public static final int effect_fifties=0x7f09007b;
        /**  Effect 2 name. 
         */
        public static final int effect_gradient=0x7f090078;
        /**  Effect 4 name. 
         */
        public static final int effect_negative=0x7f09007a;
        /**  Effect 1 name. 
         */
        public static final int effect_pan_zoom=0x7f090077;
        /**  Effect 3 name. 
         */
        public static final int effect_sepia=0x7f090079;
        /**  Effect names
 The effects selection dialog title. 
         */
        public static final int effects_select_effect=0x7f090076;
        /**  Export options dialog
 The title of the export dialog. 
         */
        public static final int export_dialog_export=0x7f090057;
        /**  The label of the movie quality spinner. 
         */
        public static final int export_dialog_movie_quality=0x7f090059;
        /**  The high quality option. 
         */
        public static final int export_dialog_movie_quality_high=0x7f09005c;
        /**  The low quality option. 
         */
        public static final int export_dialog_movie_quality_low=0x7f09005a;
        /**  The medium quality option. 
         */
        public static final int export_dialog_movie_quality_medium=0x7f09005b;
        /**  The label of the movie size spinner. 
         */
        public static final int export_dialog_movie_size=0x7f090058;
        public static final int full_app_name=0x7f090001;
        public static final int hour_and_minutes=0x7f090090;
        /**  Time related format strings displayed in the carousel below the project preview 
         */
        public static final int hours_and_minutes=0x7f09008f;
        public static final int minute_and_seconds=0x7f090092;
        public static final int minutes=0x7f090091;
        /**  Displayed in dialog buttons. 
         */
        public static final int no=0x7f09008a;
        /**  The text displayed on the button used to change overlay title template. 
         */
        public static final int overlay_change_title_template_button_text=0x7f090075;
        /**  The overlay type 2 name 
         */
        public static final int overlay_preview_bottom=0x7f09006e;
        /**  Overlay names
 The overlay type 1 name 
         */
        public static final int overlay_preview_center=0x7f09006d;
        /**  The dialog label for the overlay sample subtitle. 
         */
        public static final int overlay_subtitle_label=0x7f090074;
        /**  The sample subtitle for overlay 1. 
         */
        public static final int overlay_subtitle_sample=0x7f090071;
        /**  Overlay sample titles
 The label/name for overlay 1. 
         */
        public static final int overlay_title=0x7f09006f;
        /**  The dialog label for the overlay sample title. 
         */
        public static final int overlay_title_label=0x7f090073;
        /**  The sample title for overlay 1. 
         */
        public static final int overlay_title_sample=0x7f090070;
        /**  Overlay title activity EditText labels 
 The dialog label for the overlay name. 
         */
        public static final int overlays_select_type=0x7f090072;
        /**  The label for the end rectangle checkbox. 
         */
        public static final int pan_zoom_end=0x7f09005f;
        public static final int pan_zoom_small_image_error=0x7f090060;
        /**  The label for the start rectangle checkbox. 
         */
        public static final int pan_zoom_start=0x7f09005e;
        /**  Pan and zoom activity
 The title of the Pan & zoom activity. 
         */
        public static final int pan_zoom_title=0x7f09005d;
        /**  Project picker 
 Text displayed in the project picker new project option [CHAR_LIMIT=18]
         */
        public static final int projects_new_project=0x7f090031;
        /**  Text displayed in the project name dialog title. 
         */
        public static final int projects_project_name=0x7f090032;
        /**  Displayed in dialog buttons and menu items. 
         */
        public static final int remove=0x7f09008d;
        /**  Rendering modes displayed in the single choice selection dialog
 The black borders rendering mode. 
         */
        public static final int rendering_mode_black_borders=0x7f090086;
        /**  The cropping rendering mode. 
         */
        public static final int rendering_mode_crop=0x7f090088;
        /**  The stretch to fit rendering mode. 
         */
        public static final int rendering_mode_stretch=0x7f090087;
        public static final int seconds=0x7f090093;
        public static final int short_app_name=0x7f090000;
        /**  The sample subtitle for Theme 3. 
         */
        public static final int theme_film_subtitle=0x7f090069;
        /**  The sample title for Theme 3. 
         */
        public static final int theme_film_title=0x7f090068;
        /**  The label/name for Theme 3. 
         */
        public static final int theme_name_film=0x7f090067;
        /**  The label/name for Theme 4. 
         */
        public static final int theme_name_rock_and_roll=0x7f09006a;
        /**  The label/name for Theme 2. 
         */
        public static final int theme_name_surfing=0x7f090064;
        /**  Themes names and titles
 The label/name for Theme 1. 
         */
        public static final int theme_name_travel=0x7f090061;
        /**  The sample subtitle for Theme 4. 
         */
        public static final int theme_rock_and_roll_subtitle=0x7f09006c;
        /**  The sample title for Theme 4. 
         */
        public static final int theme_rock_and_roll_title=0x7f09006b;
        /**  The sample subtitle for Theme 2. 
         */
        public static final int theme_surfing_subtitle=0x7f090066;
        /**  The sample title for Theme 2. 
         */
        public static final int theme_surfing_title=0x7f090065;
        /**  The sample subtitle for Theme 1. 
         */
        public static final int theme_travel_subtitle=0x7f090063;
        /**  The sample title for Theme 1. 
         */
        public static final int theme_travel_title=0x7f090062;
        /**  The name of the transition using a contour alpha mask. 
         */
        public static final int transitions_alpha_countour=0x7f09007d;
        /**  The name of the transition using a diagonal alpha mask. 
         */
        public static final int transitions_alpha_diagonal=0x7f09007e;
        /**  The name of the crossfade transition. 
         */
        public static final int transitions_crossfade=0x7f09007f;
        /**  The text which displays the duration of a transition as a decimal number (e.g. "1.5 sec"). 
         */
        public static final int transitions_duration=0x7f090085;
        /**  The name of the fade to and from black transition. 
         */
        public static final int transitions_fade_black=0x7f090080;
        /**  Transition names
 The transition selection dialog title. 
         */
        public static final int transitions_select_transition=0x7f09007c;
        /**  The name of the top to bottom transition. 
         */
        public static final int transitions_sliding_bottom_out_top_in=0x7f090084;
        /**  The name of the right to left transition. 
         */
        public static final int transitions_sliding_left_out_right_in=0x7f090082;
        /**  The name of the left to right transition. 
         */
        public static final int transitions_sliding_right_out_left_in=0x7f090081;
        /**  The name of the bottom to top transition. 
         */
        public static final int transitions_sliding_top_out_bottom_in=0x7f090083;
        /**  Displayed in the carousel if the project does not have a name. 
         */
        public static final int untitled=0x7f09008e;
        /**  Generic strings
 Displayed in dialog buttons. 
         */
        public static final int yes=0x7f090089;
    }
    public static final class style {
        /**  Base application theme is the default theme. 
         */
        public static final int Theme=0x7f0a0000;
        /**  Variation on the Holo theme with a custom window background and an action bar 
         */
        public static final int Theme_VideoEditorHolo=0x7f0a0002;
        public static final int VideoEditorActionBarStyle=0x7f0a0001;
        public static final int audio_timeline_item=0x7f0a0006;
        public static final int media_timeline_item=0x7f0a0003;
        public static final int overlay_timeline_item=0x7f0a0005;
        public static final int transition_timeline_item=0x7f0a0004;
    }
}
