/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.snake;

public final class R {
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int tileSize=0x7f010000;
    }
    public static final class drawable {
        public static final int greenstar=0x7f020000;
        public static final int redstar=0x7f020001;
        public static final int yellowstar=0x7f020002;
    }
    public static final class id {
        public static final int snake=0x7f050000;
        public static final int text=0x7f050001;
    }
    public static final class layout {
        public static final int snake_layout=0x7f030000;
    }
    public static final class string {
        public static final int mode_lose_prefix=0x7f040002;
        public static final int mode_lose_suffix=0x7f040003;
        public static final int mode_pause=0x7f040001;
        public static final int mode_ready=0x7f040000;
        public static final int snake_layout_text_text=0x7f040004;
    }
    public static final class styleable {
        /** Attributes that can be used with a TileView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #TileView_tileSize com.example.android.snake:tileSize}</code></td><td></td></tr>
           </table>
           @see #TileView_tileSize
         */
        public static final int[] TileView = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link com.example.android.snake.R.attr#tileSize}
          attribute's value can be found in the {@link #TileView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:tileSize
        */
        public static final int TileView_tileSize = 0;
    };
}
