/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.soundrecorder;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int gradient_bg=0x7f020000;
        public static final int ic_launcher_soundrecorder=0x7f020001;
        public static final int play=0x7f020002;
        public static final int record=0x7f020003;
        public static final int recording_led=0x7f020004;
        public static final int stop=0x7f020005;
        public static final int vumeter=0x7f020006;
    }
    public static final class id {
        public static final int acceptButton=0x7f060009;
        public static final int discardButton=0x7f060008;
        public static final int exitButtons=0x7f060007;
        public static final int playButton=0x7f06000c;
        public static final int recordButton=0x7f06000b;
        public static final int stateLED=0x7f060003;
        public static final int stateMessage1=0x7f060005;
        public static final int stateMessage2=0x7f060004;
        public static final int stateMessage2Layout=0x7f060002;
        public static final int stateProgressBar=0x7f060006;
        public static final int stopButton=0x7f06000d;
        public static final int timerView=0x7f060001;
        public static final int timerViewLayout=0x7f060000;
        public static final int uvMeter=0x7f06000a;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        /**  button to accept the current recording and return it to the caller 
 outdated translation 7770652589312551402 
         */
        public static final int accept=0x7f04000b;
        /**  application name and title of error dialogs
         */
        public static final int app_name=0x7f040000;
        /**  all recordings will show up in the media database with this 'album' name 
         */
        public static final int audio_db_album_name=0x7f040011;
        /**  all recordings will show up in the media database with this 'artist' name 
         */
        public static final int audio_db_artist_name=0x7f040010;
        /**  all recordings will show up in the media database in a playlist with this name 
         */
        public static final int audio_db_playlist_name=0x7f040012;
        /**  the name under which recordings will be visible in the media database is formatted like this 
         */
        public static final int audio_db_title_format=0x7f04000f;
        /**  acknowlegement button in a number of dialogs 
         */
        public static final int button_ok=0x7f04000d;
        /**  button to discard the current recording and return to the caller 
         */
        public static final int discard=0x7f04000c;
        /**  shown as the message in a dialog when the app encountered an unspecified internal error 
         */
        public static final int error_app_internal=0x7f040014;
        /**  shown as the message in a dialog when the recording could not be added to the media database 
         */
        public static final int error_mediadb_new_record=0x7f040015;
        /**  shown as the message in a dialog when an error occured because of an error accessing the sd card 
 outdated translation 8005660724361043509 
         */
        public static final int error_sdcard_access=0x7f040013;
        /**  label shown when there is no sd card available to record to 
 outdated translation 2251831579676114197 
         */
        public static final int insert_sd_card=0x7f040008;
        /**  label shown when the recording has reached maximum allowed file size 
         */
        public static final int max_length_reached=0x7f040007;
        /**  Screen title after recording 
         */
        public static final int message_recorded=0x7f040002;
        /**  label shown when there is more than 1 minute but less than 9 minutes of space left to record 
         */
        public static final int min_available=0x7f040009;
        /**  Screen title before and during recording 
         */
        public static final int record_your_message=0x7f040001;
        /**  Label shown during recording 
         */
        public static final int recording=0x7f040004;
        /**  Label shown when the recording is stopped for a reason other than the user stopping it (e.g. the sd card was removed) 
         */
        public static final int recording_stopped=0x7f040005;
        /**  Screen title while playing back a recording 
         */
        public static final int review_message=0x7f040003;
        /**  label shown when there is less than 1 minute of space left to record 
         */
        public static final int sec_available=0x7f04000a;
        /**  label shown when there is not enough space to record something 
         */
        public static final int storage_is_full=0x7f040006;
        /**  Do not translate. Format of the timer that shows how much has been recorded so far 
         */
        public static final int timer_format=0x7f04000e;
    }
    public static final class style {
        public static final int MediaButton=0x7f050001;
        public static final int Theme_SoundRecorder=0x7f050000;
    }
}
