/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.settings.tests;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_settings_applications=0x7f020000;
    }
    public static final class id {
        public static final int discoverable=0x7f050002;
        public static final int enable=0x7f050001;
        public static final int msg_container=0x7f050000;
        public static final int scan=0x7f050003;
    }
    public static final class layout {
        public static final int bluetooth_request_permission_test=0x7f030000;
        public static final int manufacturer_main=0x7f030001;
        public static final int operator_main=0x7f030002;
    }
    public static final class string {
        public static final int discoverable=0x7f040001;
        /**  Test only. Do not translate. 
 Test only. Do not translate. 
 Test only. Do not translate. 
         */
        public static final int enable=0x7f040000;
        public static final int manufacturer_hello=0x7f040007;
        public static final int manufacturer_settings_summary=0x7f040009;
        public static final int manufacturer_settings_title=0x7f040008;
        public static final int operator_hello=0x7f040004;
        public static final int operator_settings_summary=0x7f040006;
        public static final int operator_settings_title=0x7f040005;
        public static final int start_scan=0x7f040002;
        public static final int stop_scan=0x7f040003;
    }
}
