/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.perftest;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int checker=0x7f020000;
        public static final int data=0x7f020001;
        public static final int flares=0x7f020002;
        public static final int globe=0x7f020003;
        public static final int leaf=0x7f020004;
        public static final int light1=0x7f020005;
        public static final int space=0x7f020006;
        public static final int test_pattern=0x7f020007;
        public static final int torusmap=0x7f020008;
    }
    public static final class id {
        public static final int benchmark_mode=0x7f060000;
        public static final int debug_mode=0x7f060001;
    }
    public static final class menu {
        public static final int loader_menu=0x7f050000;
    }
    public static final class raw {
        public static final int multitexf=0x7f030000;
        public static final int rsbench=0x7f030001;
        public static final int shader2f=0x7f030002;
        public static final int shader2movev=0x7f030003;
        public static final int shader2v=0x7f030004;
        public static final int shaderf=0x7f030005;
        public static final int shaderv=0x7f030006;
        public static final int text_test=0x7f030007;
        public static final int torus=0x7f030008;
        public static final int torus_test=0x7f030009;
    }
    public static final class string {
        public static final int benchmark_mode=0x7f040000;
        public static final int debug_mode=0x7f040001;
    }
}
