/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.home;

public final class R {
    public static final class anim {
        public static final int fade_in=0x7f040000;
        public static final int fade_out=0x7f040001;
        public static final int grid_entry=0x7f040002;
        public static final int grid_exit=0x7f040003;
        public static final int hide_applications=0x7f040004;
        public static final int show_applications=0x7f040005;
    }
    public static final class attr {
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int marginBottom=0x7f010004;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int marginLeft=0x7f010001;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int marginRight=0x7f010003;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int marginTop=0x7f010002;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>horizontal</code></td><td>0</td><td></td></tr>
<tr><td><code>vertical</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int stackOrientation=0x7f010000;
    }
    public static final class color {
        public static final int bright_text_dark_focused=0x7f080000;
    }
    public static final class drawable {
        public static final int all_applications=0x7f020000;
        public static final int all_applications_background=0x7f020001;
        public static final int all_applications_button_background=0x7f020002;
        public static final int all_applications_label_background=0x7f020003;
        public static final int application_background=0x7f020004;
        public static final int application_background_static=0x7f020005;
        public static final int bg_android=0x7f020006;
        public static final int bg_android_icon=0x7f020007;
        public static final int bg_sunrise=0x7f020008;
        public static final int bg_sunrise_icon=0x7f020009;
        public static final int bg_sunset=0x7f02000a;
        public static final int bg_sunset_icon=0x7f02000b;
        public static final int favorite_background=0x7f02000c;
        public static final int focused_application_background_static=0x7f02000d;
        public static final int grid_selector=0x7f02000e;
        public static final int hide_all_applications=0x7f02000f;
        public static final int ic_launcher_allhide=0x7f020010;
        public static final int ic_launcher_allshow=0x7f020011;
        public static final int ic_launcher_home=0x7f020012;
        public static final int pressed_application_background_static=0x7f020013;
        public static final int show_all_applications=0x7f020014;
    }
    public static final class id {
        public static final int all_apps=0x7f050005;
        public static final int faves_and_recents=0x7f050006;
        public static final int gallery=0x7f050007;
        public static final int horizontal=0x7f050000;
        public static final int label=0x7f050004;
        public static final int show_all_apps=0x7f050002;
        public static final int show_all_apps_check=0x7f050003;
        public static final int vertical=0x7f050001;
    }
    public static final class layout {
        public static final int all_applications_button=0x7f030000;
        public static final int application=0x7f030001;
        public static final int favorite=0x7f030002;
        public static final int home=0x7f030003;
        public static final int wallpaper=0x7f030004;
    }
    public static final class string {
        /**  Home 
         */
        public static final int home_title=0x7f060000;
        public static final int menu_search=0x7f060003;
        public static final int menu_settings=0x7f060004;
        /**  Home Menus 
         */
        public static final int menu_wallpaper=0x7f060002;
        public static final int show_all_apps=0x7f060001;
        /**  Wallpaper 
 Wallpaper 
         */
        public static final int wallpaper_instructions=0x7f060005;
    }
    public static final class style {
        public static final int Theme=0x7f070000;
    }
    public static final class styleable {
        /** Attributes that can be used with a ApplicationsStackLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ApplicationsStackLayout_marginBottom com.example.android.home:marginBottom}</code></td><td></td></tr>
           <tr><td><code>{@link #ApplicationsStackLayout_marginLeft com.example.android.home:marginLeft}</code></td><td></td></tr>
           <tr><td><code>{@link #ApplicationsStackLayout_marginRight com.example.android.home:marginRight}</code></td><td></td></tr>
           <tr><td><code>{@link #ApplicationsStackLayout_marginTop com.example.android.home:marginTop}</code></td><td></td></tr>
           <tr><td><code>{@link #ApplicationsStackLayout_stackOrientation com.example.android.home:stackOrientation}</code></td><td></td></tr>
           </table>
           @see #ApplicationsStackLayout_marginBottom
           @see #ApplicationsStackLayout_marginLeft
           @see #ApplicationsStackLayout_marginRight
           @see #ApplicationsStackLayout_marginTop
           @see #ApplicationsStackLayout_stackOrientation
         */
        public static final int[] ApplicationsStackLayout = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004
        };
        /**
          <p>This symbol is the offset where the {@link com.example.android.home.R.attr#marginBottom}
          attribute's value can be found in the {@link #ApplicationsStackLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:marginBottom
        */
        public static final int ApplicationsStackLayout_marginBottom = 4;
        /**
          <p>This symbol is the offset where the {@link com.example.android.home.R.attr#marginLeft}
          attribute's value can be found in the {@link #ApplicationsStackLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:marginLeft
        */
        public static final int ApplicationsStackLayout_marginLeft = 1;
        /**
          <p>This symbol is the offset where the {@link com.example.android.home.R.attr#marginRight}
          attribute's value can be found in the {@link #ApplicationsStackLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:marginRight
        */
        public static final int ApplicationsStackLayout_marginRight = 3;
        /**
          <p>This symbol is the offset where the {@link com.example.android.home.R.attr#marginTop}
          attribute's value can be found in the {@link #ApplicationsStackLayout} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:marginTop
        */
        public static final int ApplicationsStackLayout_marginTop = 2;
        /**
          <p>This symbol is the offset where the {@link com.example.android.home.R.attr#stackOrientation}
          attribute's value can be found in the {@link #ApplicationsStackLayout} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>horizontal</code></td><td>0</td><td></td></tr>
<tr><td><code>vertical</code></td><td>1</td><td></td></tr>
</table>
          @attr name android:stackOrientation
        */
        public static final int ApplicationsStackLayout_stackOrientation = 0;
    };
}
