/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.cts.verifier;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int detective=0x7f020000;
        public static final int fs_error=0x7f020001;
        public static final int fs_good=0x7f020002;
        public static final int fs_indeterminate=0x7f020003;
        public static final int fs_warning=0x7f020004;
        public static final int gray_bubble=0x7f020005;
        public static final int icon=0x7f020006;
        public static final int test_fail_gradient=0x7f020007;
        public static final int test_pass_gradient=0x7f020008;
    }
    public static final class id {
        public static final int apply_policy_button=0x7f090023;
        public static final int bt_empty_new_devices=0x7f090016;
        public static final int bt_empty_paired_devices=0x7f090014;
        public static final int bt_empty_received_messages=0x7f09001b;
        public static final int bt_empty_sent_messages=0x7f090019;
        public static final int bt_make_discoverable_button=0x7f090010;
        public static final int bt_new_devices=0x7f090015;
        public static final int bt_paired_devices=0x7f090013;
        public static final int bt_pick_server_button=0x7f090011;
        public static final int bt_received_messages=0x7f09001a;
        public static final int bt_scan_button=0x7f090017;
        public static final int bt_sent_messages=0x7f090018;
        public static final int bt_settings=0x7f090012;
        public static final int bt_toggle_button=0x7f09001c;
        public static final int calibrateButton=0x7f090008;
        public static final int cameraview=0x7f090020;
        public static final int clear=0x7f090041;
        public static final int clearButton=0x7f09000c;
        public static final int continue_button=0x7f090030;
        public static final int da_force_lock_button=0x7f090024;
        public static final int detective_logo=0x7f090033;
        public static final int dismissButton=0x7f09000e;
        public static final int doneButton=0x7f090005;
        public static final int export=0x7f090043;
        public static final int fail_button=0x7f090036;
        public static final int fs_feature=0x7f09002f;
        public static final int fs_icon=0x7f09002e;
        public static final int fs_legend_error_image=0x7f09002b;
        public static final int fs_legend_error_text=0x7f09002c;
        public static final int fs_legend_good_image=0x7f090025;
        public static final int fs_legend_good_text=0x7f090026;
        public static final int fs_legend_indeterminate_image=0x7f090027;
        public static final int fs_legend_indeterminate_text=0x7f090028;
        public static final int fs_legend_warning_image=0x7f090029;
        public static final int fs_legend_warning_text=0x7f09002a;
        public static final int fs_warnings=0x7f09002d;
        public static final int generate_button=0x7f09001d;
        public static final int generate_policy_button=0x7f090022;
        public static final int gl_surface_view=0x7f090037;
        public static final int info_button=0x7f090035;
        public static final int label=0x7f090002;
        public static final int list=0x7f090006;
        public static final int pass_button=0x7f090034;
        public static final int pass_fail_buttons=0x7f090039;
        public static final int progress=0x7f090007;
        public static final int report_text=0x7f090038;
        public static final int resulttext=0x7f09001f;
        public static final int resultview=0x7f090021;
        public static final int runAllButton=0x7f090009;
        public static final int runbutton=0x7f09001e;
        public static final int sendResultsButton=0x7f09000f;
        public static final int sensor_value=0x7f09003a;
        public static final int slider=0x7f090003;
        public static final int status=0x7f090004;
        public static final int stopButton=0x7f09000a;
        public static final int surface=0x7f09003c;
        public static final int testName=0x7f090000;
        public static final int testScore=0x7f090001;
        public static final int textView=0x7f09000d;
        public static final int usb_empty_received_messages=0x7f090040;
        public static final int usb_empty_sent_messages=0x7f09003e;
        public static final int usb_received_messages=0x7f09003f;
        public static final int usb_sent_messages=0x7f09003d;
        public static final int version_text=0x7f090031;
        public static final int videoframe=0x7f09003b;
        public static final int view=0x7f090042;
        public static final int viewResultsButton=0x7f09000b;
        public static final int welcome_text=0x7f090032;
    }
    public static final class layout {
        public static final int aq_row=0x7f030000;
        public static final int aq_sound_level_meter=0x7f030001;
        public static final int aq_verifier_activity=0x7f030002;
        public static final int aq_view_results=0x7f030003;
        public static final int bt_connection_access=0x7f030004;
        public static final int bt_device_name=0x7f030005;
        public static final int bt_device_picker=0x7f030006;
        public static final int bt_message_row=0x7f030007;
        public static final int bt_messages=0x7f030008;
        public static final int bt_toggle=0x7f030009;
        public static final int bu_main=0x7f03000a;
        public static final int bu_preference_row=0x7f03000b;
        public static final int ca_main=0x7f03000c;
        public static final int da_policy_main=0x7f03000d;
        public static final int da_screen_lock_main=0x7f03000e;
        public static final int fs_info=0x7f03000f;
        public static final int fs_main=0x7f030010;
        public static final int fs_row=0x7f030011;
        public static final int main=0x7f030012;
        public static final int pass_fail_buttons=0x7f030013;
        public static final int pass_fail_gl=0x7f030014;
        public static final int pass_fail_list=0x7f030015;
        public static final int report_viewer=0x7f030016;
        public static final int snsr_gyro=0x7f030017;
        public static final int sv_play=0x7f030018;
        public static final int test_category_row=0x7f030019;
        public static final int usb_main=0x7f03001a;
        public static final int usb_message_row=0x7f03001b;
        public static final int vertical_divider=0x7f03001c;
    }
    public static final class menu {
        public static final int test_list_menu=0x7f080000;
    }
    public static final class raw {
        public static final int sns_texture=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        /**  General experiment messages 
         */
        public static final int aq_audiorecord_buffer_size_error=0x7f0600aa;
        public static final int aq_audiotrack_buffer_size_error=0x7f0600ab;
        public static final int aq_bias_exp=0x7f060093;
        public static final int aq_bias_report=0x7f06009a;
        /**  Button labels for VerifierActivity 
         */
        public static final int aq_calibrate=0x7f06007d;
        /**   Instructions for calibrating the volume 
         */
        public static final int aq_calibrate_volume_instructions=0x7f060087;
        /**   Title for CalibrateVolumeActivity 
         */
        public static final int aq_calibrate_volume_name=0x7f060086;
        public static final int aq_clear=0x7f060082;
        public static final int aq_cold_latency=0x7f060094;
        public static final int aq_cold_latency_report=0x7f0600a7;
        public static final int aq_complete=0x7f060098;
        /**  Experiment names 
         */
        public static final int aq_default_exp=0x7f06008d;
        /**  Button label for ViewResultsActivity 
         */
        public static final int aq_dismiss=0x7f060084;
        /**  Button label for CalibrateVolumeActivity 
         */
        public static final int aq_done=0x7f060088;
        public static final int aq_email_results=0x7f060081;
        public static final int aq_exception_error=0x7f0600af;
        /**  Experiment outcomes 
         */
        public static final int aq_fail=0x7f060096;
        public static final int aq_glitch_exp=0x7f060090;
        public static final int aq_glitch_report_error=0x7f0600a1;
        public static final int aq_glitch_report_exact=0x7f0600a2;
        public static final int aq_glitch_report_range=0x7f0600a3;
        public static final int aq_init_audiorecord_error=0x7f0600ac;
        public static final int aq_init_audiotrack_error=0x7f0600ad;
        public static final int aq_level_report=0x7f0600a4;
        public static final int aq_linearity_exp=0x7f060091;
        public static final int aq_linearity_report_error=0x7f06009f;
        public static final int aq_linearity_report_normal=0x7f0600a0;
        /**  Experiment reports 
         */
        public static final int aq_loopback_report=0x7f060099;
        public static final int aq_overflow_exp=0x7f060092;
        public static final int aq_overflow_report_error=0x7f06009b;
        public static final int aq_overflow_report_fail=0x7f06009d;
        public static final int aq_overflow_report_pass=0x7f06009e;
        public static final int aq_overflow_report_short=0x7f06009c;
        public static final int aq_pass=0x7f060097;
        public static final int aq_recording_error=0x7f0600ae;
        public static final int aq_run_all=0x7f06007e;
        public static final int aq_sound_level_exp=0x7f06008e;
        public static final int aq_spectrum_report_error=0x7f0600a5;
        public static final int aq_spectrum_report_normal=0x7f0600a6;
        public static final int aq_spectrum_shape_exp=0x7f06008f;
        public static final int aq_status_high=0x7f06008b;
        public static final int aq_status_low=0x7f06008a;
        public static final int aq_status_ok=0x7f06008c;
        /**   Status values for CalibrateVolumeActivity 
         */
        public static final int aq_status_unknown=0x7f060089;
        public static final int aq_stop=0x7f06007f;
        /**  E-mail subject line for test results 
         */
        public static final int aq_subject=0x7f060085;
        /**   Strings for Audio Quality Verifier 
 Title for Audio Quality Verifier activity 
         */
        public static final int aq_verifier=0x7f06007b;
        public static final int aq_verifier_info=0x7f06007c;
        public static final int aq_view_results=0x7f060080;
        /**  Title for ViewResultsActivity 
         */
        public static final int aq_view_results_name=0x7f060083;
        public static final int aq_warm_latency=0x7f060095;
        public static final int aq_warm_latency_report_error=0x7f0600a8;
        public static final int aq_warm_latency_report_normal=0x7f0600a9;
        public static final int backup_info=0x7f06001b;
        /**  Strings for BackupTestActivity 
         */
        public static final int backup_test=0x7f06001a;
        /**  Strings for BluetoothActivity 
         */
        public static final int bluetooth_test=0x7f060038;
        public static final int bluetooth_test_info=0x7f060039;
        public static final int bt_ca_dialog=0x7f060046;
        public static final int bt_ca_tips=0x7f060047;
        public static final int bt_connected=0x7f06004f;
        public static final int bt_connecting=0x7f06004e;
        public static final int bt_connection_access_client=0x7f060043;
        public static final int bt_connection_access_client_info=0x7f060045;
        public static final int bt_connection_access_server=0x7f060042;
        public static final int bt_connection_access_server_info=0x7f060044;
        public static final int bt_control=0x7f06003a;
        public static final int bt_device_communication=0x7f06003b;
        public static final int bt_device_picker=0x7f060059;
        public static final int bt_disable_bluetooth=0x7f06003f;
        public static final int bt_disabling=0x7f060040;
        public static final int bt_disabling_error=0x7f060041;
        public static final int bt_enable_bluetooth=0x7f06003e;
        public static final int bt_insecure_client=0x7f060058;
        public static final int bt_insecure_pairing_error_message=0x7f060056;
        public static final int bt_insecure_pairing_error_title=0x7f060055;
        public static final int bt_insecure_server=0x7f06004a;
        public static final int bt_insecure_server_instructions=0x7f06004b;
        public static final int bt_listening=0x7f06004d;
        public static final int bt_make_discoverable=0x7f060053;
        public static final int bt_new_devices=0x7f06005b;
        public static final int bt_no_devices=0x7f06005c;
        public static final int bt_no_messages=0x7f060052;
        public static final int bt_paired_devices=0x7f06005a;
        public static final int bt_pick_server=0x7f060054;
        public static final int bt_received_messages=0x7f060050;
        public static final int bt_scan=0x7f06005d;
        public static final int bt_scanning=0x7f06005e;
        public static final int bt_secure_client=0x7f060057;
        public static final int bt_secure_server=0x7f060048;
        public static final int bt_secure_server_instructions=0x7f060049;
        public static final int bt_sent_messages=0x7f060051;
        public static final int bt_settings=0x7f060060;
        public static final int bt_toggle_bluetooth=0x7f06003c;
        public static final int bt_toggle_instructions=0x7f06003d;
        public static final int bt_unpair=0x7f06005f;
        public static final int bt_waiting=0x7f06004c;
        public static final int bu_files=0x7f06001d;
        public static final int bu_generate=0x7f06001f;
        public static final int bu_generate_error=0x7f060020;
        public static final int bu_instructions=0x7f060021;
        public static final int bu_loading=0x7f06001e;
        public static final int bu_preferences=0x7f06001c;
        public static final int bu_settings=0x7f060022;
        public static final int ca_result_label=0x7f0600b2;
        public static final int ca_run_label=0x7f0600b1;
        /**  Strings for Camera Analyzer 
         */
        public static final int camera_analyzer=0x7f0600b0;
        public static final int clear=0x7f060012;
        public static final int congratulations=0x7f060079;
        public static final int continue_button_text=0x7f060003;
        public static final int da_apply_policy=0x7f060027;
        public static final int da_force_lock=0x7f060035;
        public static final int da_generate_policy=0x7f060026;
        public static final int da_lock_error=0x7f060037;
        public static final int da_lock_success=0x7f060036;
        public static final int da_maximum_failed_passwords_for_wipe=0x7f060030;
        public static final int da_maximum_time_to_lock=0x7f060031;
        public static final int da_no_policy=0x7f060025;
        public static final int da_password_minimum_length=0x7f06002f;
        public static final int da_password_quality=0x7f06002a;
        public static final int da_password_quality_alphabetic=0x7f06002b;
        public static final int da_password_quality_alphanumeric=0x7f06002c;
        public static final int da_password_quality_numeric=0x7f06002d;
        public static final int da_password_quality_something=0x7f06002e;
        public static final int da_policy_info=0x7f060032;
        public static final int da_policy_reboot=0x7f060029;
        public static final int da_policy_serialization_info=0x7f060024;
        /**  Strings for Device Administration tests 
         */
        public static final int da_policy_serialization_test=0x7f060023;
        public static final int da_random_policy=0x7f060028;
        public static final int da_screen_lock_info=0x7f060034;
        public static final int da_screen_lock_test=0x7f060033;
        public static final int empty=0x7f06006a;
        public static final int export=0x7f060016;
        public static final int fail_button_text=0x7f060006;
        /**  Strings for FeatureSummaryActivity 
         */
        public static final int feature_summary=0x7f060061;
        public static final int feature_summary_info=0x7f060062;
        public static final int file_status=0x7f060077;
        public static final int fs_disallowed=0x7f060063;
        public static final int fs_legend_error=0x7f060069;
        public static final int fs_legend_good=0x7f060066;
        public static final int fs_legend_indeterminate=0x7f060067;
        public static final int fs_legend_warning=0x7f060068;
        public static final int fs_missing_wifi_telephony=0x7f060064;
        public static final int fs_no_data=0x7f060065;
        public static final int info_button_text=0x7f060005;
        public static final int no_file_status=0x7f060078;
        public static final int no_storage=0x7f060017;
        public static final int no_suid_files=0x7f06007a;
        public static final int pass_button_text=0x7f060004;
        public static final int report_saved=0x7f060018;
        /**  Strings for ReportViewerActivity 
         */
        public static final int report_viewer=0x7f060019;
        public static final int scanning_directory=0x7f060076;
        /**  Strings for AccelerometerTestActivity and GyroscopeTestActivity 
         */
        public static final int snsr_accel_test=0x7f06006b;
        public static final int snsr_accel_test_info=0x7f06006c;
        public static final int snsr_gyro_test=0x7f06006d;
        public static final int snsr_gyro_test_degrees_message=0x7f060073;
        public static final int snsr_gyro_test_degrees_title=0x7f060072;
        public static final int snsr_gyro_test_info=0x7f06006e;
        public static final int snsr_gyro_test_no_gyro_message=0x7f060071;
        public static final int snsr_gyro_test_no_gyro_title=0x7f060070;
        public static final int snsr_gyro_test_progress=0x7f06006f;
        /**  Strings for StreamingVideoActivity 
         */
        public static final int streaming_video=0x7f0600bf;
        public static final int streaming_video_info=0x7f0600c0;
        /**  Strings for SuidFilesActivity 
         */
        public static final int suid_files=0x7f060074;
        public static final int suid_files_info=0x7f060075;
        public static final int sv_failed_message=0x7f0600c3;
        public static final int sv_failed_title=0x7f0600c2;
        public static final int sv_no_data=0x7f0600c1;
        public static final int test_category_audio=0x7f060008;
        public static final int test_category_camera=0x7f060009;
        public static final int test_category_device_admin=0x7f06000a;
        public static final int test_category_features=0x7f060010;
        public static final int test_category_hardware=0x7f06000b;
        public static final int test_category_networking=0x7f06000c;
        public static final int test_category_other=0x7f060011;
        public static final int test_category_security=0x7f06000e;
        public static final int test_category_sensors=0x7f06000d;
        public static final int test_category_streaming=0x7f06000f;
        /**  Strings for TestListActivity 
         */
        public static final int test_list_title=0x7f060007;
        public static final int test_results_cleared=0x7f060013;
        public static final int test_results_error=0x7f060015;
        /**  Strings for USB accessory test activity 
         */
        public static final int usb_accessory_test=0x7f0600b3;
        public static final int usb_accessory_test_info=0x7f0600b4;
        public static final int usb_file_descriptor_error=0x7f0600be;
        public static final int usb_message_thread_ended=0x7f0600bc;
        public static final int usb_message_thread_exception=0x7f0600bb;
        public static final int usb_message_thread_started=0x7f0600ba;
        public static final int usb_no_messages=0x7f0600b9;
        public static final int usb_not_available_message=0x7f0600b6;
        public static final int usb_not_available_title=0x7f0600b5;
        public static final int usb_received_messages=0x7f0600b7;
        public static final int usb_sent_messages=0x7f0600b8;
        public static final int usb_test_passed=0x7f0600bd;
        public static final int version_text=0x7f060002;
        public static final int view=0x7f060014;
        public static final int welcome_text=0x7f060001;
    }
    public static final class style {
        public static final int InstructionsFont=0x7f070001;
        public static final int MessageRow=0x7f070003;
        public static final int VersionFont=0x7f070002;
        public static final int WelcomeFont=0x7f070000;
    }
    public static final class xml {
        public static final int accessory_filter=0x7f040000;
        public static final int device_admin=0x7f040001;
    }
}
