/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.shaderstest;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int robot=0x7f020000;
    }
    public static final class raw {
        public static final int depth_fs=0x7f030000;
        public static final int robot=0x7f030001;
        public static final int shaderstest=0x7f030002;
        public static final int vignette_fs=0x7f030003;
    }
}
