/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.providers.calendar;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
    }
    public static final class id {
        public static final int cancel=0x7f060003;
        public static final int confirm=0x7f060001;
        public static final int delete=0x7f060002;
        public static final int text=0x7f060000;
    }
    public static final class layout {
        public static final int dialog_activity=0x7f030000;
    }
    public static final class string {
        /**  Temporary Calendar name to use before we have the calendar name from the server 
         */
        public static final int calendar_default_name=0x7f050002;
        /**  Caption on secret calendar info 
         */
        public static final int calendar_info=0x7f050003;
        /**  Error message for secret calendar info 
         */
        public static final int calendar_info_error=0x7f050004;
        /**  Event count message for secret calendar info 
         */
        public static final int calendar_info_events=0x7f050006;
        /**  Event and dirty event count message for secret calendar info 
         */
        public static final int calendar_info_events_dirty=0x7f050007;
        /**  No calendars message for secret calendar info 
         */
        public static final int calendar_info_no_calendars=0x7f050005;
        /**  Title for the Calendar Storage process. 
         */
        public static final int calendar_storage=0x7f050000;
        /**  Debug tool - dialog - delete file now [CHAR LIMIT=NONE] 
         */
        public static final int debug_tool_delete_button=0x7f050009;
        /**  Debug tool - email body [CHAR LIMIT=NONE] 
         */
        public static final int debug_tool_email_body=0x7f05000e;
        /**  Debug tool - email subject [CHAR LIMIT=NONE] 
         */
        public static final int debug_tool_email_sender_picker=0x7f05000c;
        /**  Debug tool - email subject [CHAR LIMIT=NONE] 
         */
        public static final int debug_tool_email_subject=0x7f05000d;
        /**  Debug tool - Main message shown to the user when starting up the debug tool [CHAR LIMIT=NONE] 
         */
        public static final int debug_tool_message=0x7f05000b;
        /**  Debug tool - dialog - start copying [CHAR LIMIT=NONE] 
         */
        public static final int debug_tool_start_button=0x7f05000a;
        /**  What to show in messaging that refers to this provider, e.g. AccountSyncSettings 
         */
        public static final int provider_label=0x7f050008;
        /**  [CHAR LIMIT=NONE] Boot message while upgrading calendar. 
         */
        public static final int upgrade_msg=0x7f050001;
    }
    public static final class xml {
        public static final int syncadapter=0x7f040000;
    }
}
