/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.providers.drm;

public final class Manifest {
    public static final class permission {
        /**  Allows an application to access DRM content 
         */
        public static final String ACCESS_DRM="android.permission.ACCESS_DRM";
        public static final String INSTALL_DRM="android.permission.INSTALL_DRM";
    }
}
