/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.providers.drm;

public final class R {
    public static final class attr {
    }
    public static final class string {
        /**  Title of the storage activity for DRM content. 
         */
        public static final int app_label=0x7f020000;
        /**  Description of the permission that allows access to DRM content 
         */
        public static final int permdesc_accessDrm=0x7f020002;
        /**  Description of the permission that allows installation of DRM content 
         */
        public static final int permdesc_installDrm=0x7f020004;
        /**  Title of the permission that allows access to DRM content 
         */
        public static final int permlab_accessDrm=0x7f020001;
        /**  Title of the permission that allows installation of DRM content 
         */
        public static final int permlab_installDrm=0x7f020003;
    }
}
