/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.backuprestore;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int bacon=0x7f040001;
        public static final int filling_group=0x7f040000;
        public static final int hummus=0x7f040003;
        public static final int mayo=0x7f040004;
        public static final int pastrami=0x7f040002;
        public static final int restore_button=0x7f040006;
        public static final int tomato=0x7f040005;
    }
    public static final class layout {
        public static final int backup_restore=0x7f020000;
    }
    public static final class string {
        public static final int bacon_label=0x7f030001;
        public static final int extras_text=0x7f030004;
        public static final int filling_text=0x7f030000;
        public static final int hummus_label=0x7f030003;
        public static final int mayo_text=0x7f030005;
        public static final int pastrami_label=0x7f030002;
        public static final int restore_text=0x7f030007;
        public static final int tomato_text=0x7f030006;
    }
}
