/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.fbotest;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int robot=0x7f020000;
    }
    public static final class raw {
        public static final int fbosync=0x7f030000;
        public static final int fbotest=0x7f030001;
        public static final int robot=0x7f030002;
    }
}
