/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.phone.tests;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int button1=0x7f040008;
        public static final int callButton=0x7f040002;
        public static final int dialButton=0x7f040003;
        public static final int itelephonyCallButton=0x7f040004;
        public static final int itelephonyDialButton=0x7f040005;
        public static final int label1=0x7f040000;
        public static final int number=0x7f040001;
        public static final int progress_bar=0x7f040006;
        public static final int result1=0x7f040007;
    }
    public static final class layout {
        public static final int call_dial_test=0x7f020000;
        public static final int otasp_test_activity=0x7f020001;
    }
    public static final class string {
        /**  Application label 
         */
        public static final int app_name=0x7f030000;
        public static final int callCommand=0x7f030002;
        /**  Strings for the CallDialTest activity 
         */
        public static final int callDialTestLabel=0x7f030001;
        public static final int dialCommand=0x7f030003;
        public static final int itelephonyCallCommand=0x7f030004;
        public static final int itelephonyDialCommand=0x7f030005;
    }
}
