/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.email.policy;

public final class R {
    public static final class attr {
    }
    public static final class string {
        public static final int app_label=0x7f020000;
    }
}
