/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.svox.pico;

public final class R {
    public static final class attr {
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int deu_deu_sample=0x7f040004;
        public static final int eng_gbr_sample=0x7f040002;
        public static final int eng_usa_sample=0x7f040001;
        public static final int fra_fra_sample=0x7f040003;
        public static final int installed=0x7f040007;
        public static final int ita_ita_sample=0x7f040005;
        public static final int not_installed=0x7f040008;
        public static final int spa_esp_sample=0x7f040006;
    }
    public static final class xml {
        public static final int tts_engine=0x7f030000;
        public static final int voices_list=0x7f030001;
    }
}
