/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.sip;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int btn_record=0x7f020000;
        public static final int btn_speak_normal=0x7f020001;
        public static final int btn_speak_pressed=0x7f020002;
        public static final int btn_speak_selected=0x7f020003;
        public static final int icon=0x7f020004;
    }
    public static final class id {
        public static final int calladdress_edit=0x7f060001;
        public static final int calladdress_view=0x7f060000;
        public static final int mainlayout=0x7f060002;
        public static final int pushToTalk=0x7f060004;
        public static final int sipLabel=0x7f060003;
    }
    public static final class layout {
        public static final int call_address_dialog=0x7f030000;
        public static final int walkietalkie=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int contactAddress=0x7f050001;
        public static final int talk=0x7f050002;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
