/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.tests.appwidgethost;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int oh_hai_icon=0x7f020000;
    }
    public static final class id {
        public static final int add_appwidget=0x7f060001;
        public static final int appwidget_container=0x7f060000;
        public static final int edit_text=0x7f060003;
        public static final int oh_hai_text=0x7f060002;
        public static final int save_button=0x7f060004;
    }
    public static final class layout {
        public static final int appwidget_host=0x7f030000;
        public static final int test_appwidget=0x7f030001;
        public static final int test_appwidget_configure=0x7f030002;
    }
    public static final class string {
        public static final int add_appwidget=0x7f050001;
        public static final int appwidget_view_title=0x7f050000;
        public static final int delete_appwidget=0x7f050003;
        public static final int oh_hai=0x7f050002;
        public static final int save=0x7f050004;
    }
    public static final class xml {
        public static final int appwidget_info=0x7f040000;
    }
}
