/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.modelviewer;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int robot=0x7f020000;
    }
    public static final class id {
        public static final int display_options=0x7f060001;
        public static final int load_model=0x7f060000;
        public static final int sensor=0x7f060002;
    }
    public static final class menu {
        public static final int loader_menu=0x7f050000;
    }
    public static final class raw {
        public static final int robot=0x7f030000;
        public static final int scenegraph=0x7f030001;
        public static final int simplemodel=0x7f030002;
        public static final int transform=0x7f030003;
    }
    public static final class string {
        public static final int display_options=0x7f040001;
        public static final int load_model=0x7f040000;
        public static final int sensor=0x7f040002;
    }
}
