/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.samplespellcheckerservice;

public final class R {
    public static final class attr {
    }
    public static final class string {
        public static final int app_name=0x7f030000;
        public static final int sample_preference=0x7f030004;
        public static final int sample_settings=0x7f030003;
        public static final int spellchecker_name=0x7f030001;
        public static final int subtype_generic=0x7f030002;
    }
    public static final class xml {
        public static final int spell_checker_settings=0x7f020000;
        public static final int spellchecker=0x7f020001;
    }
}
