/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.nfc3;

public final class Manifest {
    public static final class permission {
        public static final String NFCEE_ADMIN="com.android.nfc.permission.NFCEE_ADMIN";
    }
}
