/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.nfc3;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int p2p_bg=0x7f020002;
        public static final int stat_sys_nfc=0x7f020003;
    }
    public static final class id {
        public static final int back=0x7f060001;
        public static final int calltoaction=0x7f060002;
        public static final int fireflies=0x7f060000;
        public static final int screenshot=0x7f060003;
    }
    public static final class layout {
        public static final int screenshot=0x7f030000;
    }
    public static final class raw {
        public static final int end=0x7f040000;
        public static final int error=0x7f040001;
        public static final int start=0x7f040002;
    }
    public static final class string {
        /**  Content description of the NFC enabled notification icon for accessibility (not shown on the screen). [CHAR LIMIT=NONE] 
         */
        public static final int accessibility_nfc_enabled=0x7f050008;
        public static final int app_name=0x7f050000;
        /**  A notification action string prompting the user to add contact details to the People application [CHAR-LIMIT=64] 
         */
        public static final int inbound_me_profile_text=0x7f050005;
        /**  A notification description string informing the user that contact details were received over NFC [CHAR-LIMIT=64] 
         */
        public static final int inbound_me_profile_title=0x7f050004;
        public static final int nfcUserLabel=0x7f050001;
        /**  A notification action string prompting the user to share their contact details over NFC [CHAR-LIMIT=64] 
         */
        public static final int outbound_me_profile_text=0x7f050007;
        /**  A notification description string asking the user to share their contact details over NFC [CHAR-LIMIT=64] 
         */
        public static final int outbound_me_profile_title=0x7f050006;
        /**  The description for the NFC admin permission 
         */
        public static final int permdesc_nfcAdmin=0x7f050003;
        /**  The label for the NFC admin permission 
         */
        public static final int permlab_nfcAdmin=0x7f050002;
        public static final int touch=0x7f050009;
    }
}
