/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.phasebeam;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int beam=0x7f020000;
        public static final int dot=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int wallpaper_thumb=0x7f020003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int bg_fs=0x7f050000;
        public static final int bg_vs=0x7f050001;
        public static final int bgmesh=0x7f050002;
        public static final int dot_fs=0x7f050003;
        public static final int dot_vs=0x7f050004;
        public static final int phasebeam=0x7f050005;
    }
    public static final class string {
        public static final int wallpaper_author=0x7f060001;
        public static final int wallpaper_description=0x7f060002;
        public static final int wallpaper_label=0x7f060000;
    }
    public static final class xml {
        public static final int wallpaper=0x7f040000;
    }
}
