/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.quicksearchbox.tests.slow;

public final class R {
    public static final class attr {
    }
    public static final class string {
        /**  No need to translate these, they are for testing only. 
         */
        public static final int app_label=0x7f030000;
        public static final int settings_description=0x7f030001;
    }
    public static final class xml {
        public static final int searchable=0x7f020000;
    }
}
