/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

namespace XobotOS.Samples.ListActivity
{

public static class @R {
    public static class @array {
        public const int lemur_string_array=0x7f030000;
        public const int lemurs=0x7f030001;
    }
    public static class @attr {
    }
    public static class @drawable {
        public const int aye_aye=0x7f020000;
        public const int bamboo_lemur=0x7f020001;
        public const int fork_marked_lemur=0x7f020002;
        public const int gray_mouse_lemur=0x7f020003;
        public const int indri=0x7f020004;
        public const int jupiter=0x7f020005;
        public const int mars=0x7f020006;
        public const int mouse_lemur=0x7f020007;
        public const int red_fronted_lemur=0x7f020008;
        public const int ring_tailed_lemur=0x7f020009;
        public const int ring_tailed_lemur_2=0x7f02000a;
        public const int ruffed_lemur=0x7f02000b;
        public const int sahamalaza_sportive_lemur=0x7f02000c;
        public const int sifaka=0x7f02000d;
        public const int silky_sifaka=0x7f02000e;
    }
    public static class @string {
        public const int aye_aye=0x7f04000b;
        public const int bamboo_lemur=0x7f040003;
        public const int fork_marked_lemur=0x7f040005;
        public const int gray_mouse_lemur=0x7f040004;
        public const int indri=0x7f040009;
        public const int mouse_lemur=0x7f040002;
        public const int red_fronted_lemur=0x7f040006;
        public const int ring_tailed_lemur=0x7f040000;
        public const int ruffed_lemur=0x7f040007;
        public const int sahamalaza_sportive_lemur=0x7f040008;
        public const int sifaka=0x7f04000a;
        public const int silky_sifaka=0x7f040001;
    }
}

}
