/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.calendar;

public final class R {
    public static final class anim {
        public static final int slide_left_in=0x7f050000;
        public static final int slide_left_out=0x7f050001;
        public static final int slide_right_in=0x7f050002;
        public static final int slide_right_out=0x7f050003;
    }
    public static final class array {
        public static final int availability=0x7f07000a;
        /**  Strings for buttons in drop down menu 
         */
        public static final int buttons_list=0x7f070012;
        /**  The list of choices displayed in a dialog box when the user wants to
    respond to an invitation that repeats. 
         */
        public static final int change_response_labels=0x7f070011;
        public static final int delete_repeating_labels=0x7f07000e;
        public static final int delete_repeating_labels_no_selected=0x7f070010;
        /**  DO NOT TRANSLATE These values need to correspond to the indices
         defined in DeleteEventHelper.java
         */
        public static final int delete_repeating_values=0x7f07000f;
        public static final int ordinal_labels=0x7f07000c;
        /**  The vibrate notification modes 
         */
        public static final int prefEntries_alerts_vibrateWhen=0x7f070013;
        /**  The vibrateWhen values 
         */
        public static final int prefValues_alerts_vibrateWhen=0x7f070014;
        /**  Choices for the "Reminder minutes" spinner in the settings.
         These must be kept in sync with the preferences_default_reminder_values array.
         [CHAR LIMIT=12]
    
         */
        public static final int preferences_default_reminder_labels=0x7f070004;
        public static final int preferences_default_reminder_values=0x7f070005;
        public static final int preferences_week_start_day_labels=0x7f070006;
        public static final int preferences_week_start_day_values=0x7f070007;
        /**  Choices for the "Reminder method" spinner.
         These must be kept in sync with the reminder_methods_values array.
         [CHAR LIMIT=10]
    
         */
        public static final int reminder_methods_labels=0x7f070000;
        /**  This maps reminder_methods_labels to internal constants. 
 METHOD_SMS 
         */
        public static final int reminder_methods_values=0x7f070001;
        /**  Choices for the "Reminder minutes" spinner.
         These must be kept in sync with the reminder_minutes_values array.
         For consistency, the format should match what
         EventViewUtils.constructReminderLabel() generates.  (TODO: eliminate
         this and just generate the list from reminder_minutes_values?)
         [CHAR LIMIT=15]
    
         */
        public static final int reminder_minutes_labels=0x7f070002;
        public static final int reminder_minutes_values=0x7f070003;
        /**  Invitation responses 
         */
        public static final int response_labels1=0x7f07000d;
        /**  Choices for timezones, must be kept in sync with timezone_values. This
         list was taken from package/apps/Settings/res/xml/timezones.xml
         [CHAR LIMIT=20] 
         */
        public static final int timezone_labels=0x7f070008;
        /**  This list was taken from package/apps/Settings/res/xml/timezones.xml 
         */
        public static final int timezone_values=0x7f070009;
        public static final int visibility=0x7f07000b;
    }
    public static final class attr {
    }
    public static final class bool {
        /**  turn on/off month with agenda view 
 not supported for X-large devices 
 turn on/off month with agenda view 
 not supported for X-large devices 
         */
        public static final int show_agenda_with_month=0x7f090001;
        /**  turn on/off the mini-calendar and calendar picker 
 supported only for x-large devices  
 turn on/off the mini-calendar and calendar picker 
 supported only for x-large devices  
         */
        public static final int show_calendar_controls=0x7f090000;
        /**  when on, shows details of event in month view, when off, shows busy bits 
 the "show details" mode is recommended for devices with large screens 
 when on, shows details of event in month view, when off, shows busy bits 
 the "show details" mode is recommended for devices with large screens 
         */
        public static final int show_details_in_month=0x7f090002;
        /**  when on, shows the event next to the agenda list,
         when off, shows the event on top of the agenda list after it was clicked. 
 when on, shows the event next to the agenda list,
         when off, shows the event on top of the agenda list after it was clicked. 
         */
        public static final int show_event_details_with_agenda=0x7f090003;
        /**  when on, event info is shown in full screen, when off, shown as a popup. 
 when on, event info is shown in full screen, when off, shown as a popup.  
         */
        public static final int show_event_info_full_screen=0x7f090004;
        /**   A global var used to tablet vs phone settings 
  A global var used to tablet vs phone settings 
         */
        public static final int tablet_config=0x7f090005;
    }
    public static final class color {
        /**  Background Color of present/future events in agenda view  
         */
        public static final int agenda_day_bar_background_color=0x7f080033;
        /**  Agenda day item text color  
         */
        public static final int agenda_day_item_text_color=0x7f080037;
        /**  General background color in agenda view  
         */
        public static final int agenda_general_background_color=0x7f080036;
        /**  Text color of declined events in agenda view 
         */
        public static final int agenda_item_declined_color=0x7f080031;
        /**  Text color of the date in the Calendar widget 
         */
        public static final int agenda_item_not_selected=0x7f080030;
        /**  Text color of non-declined events in agenda view 
         */
        public static final int agenda_item_standard_color=0x7f080032;
        /**  Color of the event location's text in an agenda item  
         */
        public static final int agenda_item_where_declined_text_color=0x7f080039;
        /**  Color of the event location's text in an agenda item  
         */
        public static final int agenda_item_where_text_color=0x7f080038;
        /**  Color of the separator between items in the agenda list 
         */
        public static final int agenda_list_separator_color=0x7f08003c;
        /**  Background Color of past events in agenda view  
         */
        public static final int agenda_past_days_bar_background_color=0x7f080034;
        /**  Color of the separator between the past and the present/future in agenda view  
         */
        public static final int agenda_past_present_separator_color=0x7f080035;
        /**  Text color of a selected items in the agenda list - trumps all other text colors 
         */
        public static final int agenda_selected_background_color=0x7f08003d;
        /**  Background color of a selected items in the agenda list 
         */
        public static final int agenda_selected_text_color=0x7f08003e;
        public static final int alert_event_other=0x7f080049;
        public static final int alert_event_title=0x7f080048;
        public static final int alert_past_event=0x7f08004a;
        public static final int appwidget_date=0x7f08004c;
        /**  Text color of declined events in widget view 
         */
        public static final int appwidget_item_declined_color=0x7f08004f;
        /**  Text color of non-declined events in widget view 
         */
        public static final int appwidget_item_standard_color=0x7f080050;
        public static final int appwidget_month=0x7f08004e;
        public static final int appwidget_no_events=0x7f080054;
        public static final int appwidget_row_in_progress=0x7f08004b;
        public static final int appwidget_title=0x7f080051;
        public static final int appwidget_week=0x7f08004d;
        public static final int appwidget_when=0x7f080052;
        public static final int appwidget_where=0x7f080053;
        /**  The app wide background color 
         */
        public static final int background_color=0x7f080003;
        public static final int calendar_ampm_label=0x7f08000d;
        public static final int calendar_date_banner_background=0x7f08000f;
        public static final int calendar_date_banner_text_color=0x7f080010;
        public static final int calendar_date_range_color=0x7f080008;
        public static final int calendar_event_text_color=0x7f080006;
        public static final int calendar_future_bg_color=0x7f08000b;
        public static final int calendar_grid_area_selected=0x7f080011;
        public static final int calendar_grid_line_highlight_color=0x7f080014;
        public static final int calendar_grid_line_inner_horizontal_color=0x7f080012;
        public static final int calendar_grid_line_inner_vertical_color=0x7f080013;
        public static final int calendar_hidden=0x7f08002d;
        public static final int calendar_hour_background=0x7f08000e;
        public static final int calendar_hour_label=0x7f08000c;
        public static final int calendar_owner_text_color=0x7f080007;
        public static final int calendar_secondary_hidden=0x7f08002f;
        public static final int calendar_secondary_visible=0x7f08002e;
        /**  Color of text in the calendar view selection menu 
         */
        public static final int calendar_view_switch_menu_text_color=0x7f08003a;
        /**  Light color of text in the calendar view selection menu 
         */
        public static final int calendar_view_switch_menu_text_color_light=0x7f08003b;
        public static final int calendar_visible=0x7f08002c;
        public static final int chip_selected=0x7f080057;
        public static final int default_chip_background=0x7f080055;
        public static final int edit_event_separator=0x7f08002b;
        public static final int event_background=0x7f080004;
        public static final int event_center=0x7f08002a;
        public static final int event_info_body_color=0x7f080044;
        public static final int event_info_description_color=0x7f080043;
        /**  Event info colors 
         */
        public static final int event_info_headline_color=0x7f080040;
        public static final int event_info_headline_link_color=0x7f080041;
        public static final int event_info_label_background_color=0x7f080046;
        public static final int event_info_label_color=0x7f080045;
        public static final int event_info_organizer_color=0x7f080042;
        public static final int list_item_selected=0x7f080056;
        public static final int mini_month_bg_color=0x7f080015;
        public static final int mini_month_today_outline_color=0x7f080016;
        public static final int month_bgcolor=0x7f080028;
        public static final int month_day_names_color=0x7f08001b;
        public static final int month_day_number=0x7f080017;
        public static final int month_day_number_other=0x7f080019;
        public static final int month_dna_conflict_time_color=0x7f080029;
        public static final int month_event_color=0x7f08001d;
        public static final int month_event_extra_color=0x7f08001e;
        public static final int month_event_extra_other_color=0x7f080020;
        public static final int month_event_other_color=0x7f08001f;
        public static final int month_grid_lines=0x7f080023;
        public static final int month_mini_day_number=0x7f080018;
        public static final int month_other_bgcolor=0x7f080025;
        public static final int month_other_month_day_number=0x7f080024;
        public static final int month_saturday=0x7f080021;
        public static final int month_selected_week_bgcolor=0x7f080026;
        public static final int month_sunday=0x7f080022;
        public static final int month_today_bgcolor=0x7f080027;
        public static final int month_today_number=0x7f08001c;
        public static final int month_week_num_color=0x7f08001a;
        /**  Text color of the "new event" hint in day and week views 
         */
        public static final int new_event_hint_text_color=0x7f08003f;
        public static final int panel_text_foreground=0x7f080005;
        public static final int pressed=0x7f080000;
        public static final int selection=0x7f080001;
        public static final int text_shadow_color=0x7f080047;
        public static final int today_highlight_color=0x7f080002;
        public static final int week_saturday=0x7f080009;
        public static final int week_sunday=0x7f08000a;
    }
    public static final class dimen {
        public static final int action_bar_date_text_size=0x7f0a0012;
        public static final int all_day_bottom_margin=0x7f0a0001;
        public static final int allday_text_size=0x7f0a0006;
        public static final int ampm_text_size=0x7f0a0007;
        public static final int chip_height=0x7f0a0015;
        public static final int chip_padding=0x7f0a0014;
        public static final int chip_text_size=0x7f0a0016;
        public static final int date_header_text_size=0x7f0a0004;
        public static final int day_header_bottom_margin=0x7f0a0003;
        /**  size of day header in day and week views  
 size of day header in day and week views  
         */
        public static final int day_header_height=0x7f0a000f;
        public static final int day_label_text_size=0x7f0a0000;
        public static final int event_min_height=0x7f0a000b;
        public static final int event_text_horizontal_margin=0x7f0a000a;
        public static final int event_text_size=0x7f0a0008;
        public static final int event_text_vertical_margin=0x7f0a0009;
        /**  margins size of hours column in day/week view 
 margins size of hours column in day/week view 
         */
        public static final int hours_left_margin=0x7f0a000d;
        public static final int hours_right_margin=0x7f0a000e;
        public static final int hours_text_size=0x7f0a0005;
        /**  minimum size of hours column in day/week view 
 minimum size of hours column in day/week view 
         */
        public static final int min_hours_width=0x7f0a000c;
        public static final int new_event_hint_text_size=0x7f0a0013;
        public static final int one_day_header_height=0x7f0a0002;
        public static final int widget_day_num_size=0x7f0a0010;
        public static final int widget_day_num_top_padding=0x7f0a0011;
    }
    public static final class drawable {
        public static final int agenda_item_bg_primary=0x7f020000;
        public static final int agenda_item_bg_secondary=0x7f020001;
        public static final int appwidget_header_selector=0x7f020002;
        public static final int bg_event_cal_widget_holo=0x7f020003;
        public static final int bg_separator=0x7f020004;
        public static final int bg_separator_inset=0x7f020005;
        public static final int cal_widget_bg=0x7f020006;
        public static final int cal_widget_date_bg=0x7f020007;
        public static final int calendar_widget_preview=0x7f020008;
        public static final int calendars_item=0x7f020009;
        public static final int calname_bottom_select_underselect=0x7f02000a;
        public static final int calname_bottom_select_underselect_holo_light=0x7f02000b;
        public static final int calname_bottom_select_underselect_pressed_holo_light=0x7f02000c;
        public static final int calname_bottom_select_underunselected=0x7f02000d;
        public static final int calname_bottom_select_underunselected_holo_light=0x7f02000e;
        public static final int calname_bottom_select_underunselected_pressed_holo_light=0x7f02000f;
        public static final int calname_bottom_unselected=0x7f020010;
        public static final int calname_bottom_unselected_holo_light=0x7f020011;
        public static final int calname_bottom_unselected_pressed_holo_light=0x7f020012;
        public static final int calname_bottom_unselected_underselect=0x7f020013;
        public static final int calname_bottom_unselected_underselect_holo_light=0x7f020014;
        public static final int calname_bottom_unselected_underselect_pressed_holo_light=0x7f020015;
        public static final int calname_select_underselect=0x7f020016;
        public static final int calname_select_underselect_holo_light=0x7f020017;
        public static final int calname_select_underselect_pressed_holo_light=0x7f020018;
        public static final int calname_select_underunselected=0x7f020019;
        public static final int calname_select_underunselected_holo_light=0x7f02001a;
        public static final int calname_select_underunselected_pressed_holo_light=0x7f02001b;
        public static final int calname_unselected=0x7f02001c;
        public static final int calname_unselected_holo_light=0x7f02001d;
        public static final int calname_unselected_pressed_holo_light=0x7f02001e;
        public static final int calname_unselected_underselect=0x7f02001f;
        public static final int calname_unselected_underselect_holo_light=0x7f020020;
        public static final int calname_unselected_underselect_pressed_holo_light=0x7f020021;
        public static final int chip_background=0x7f020022;
        public static final int chip_background_invalid=0x7f020023;
        public static final int chip_background_selected=0x7f020024;
        public static final int chip_checkmark=0x7f020025;
        public static final int chip_delete=0x7f020026;
        public static final int dayline_minical_holo_light=0x7f020027;
        public static final int frame_event_color_cal_widget_holo=0x7f020028;
        public static final int header_bg_cal_widget_holo=0x7f020029;
        public static final int header_row_focused_cal_widget_holo=0x7f02002a;
        public static final int header_row_press_cal_widget_holo=0x7f02002b;
        public static final int ic_alarm_dark=0x7f02002c;
        public static final int ic_alarm_white=0x7f02002d;
        public static final int ic_allday_collapse_holo_light=0x7f02002e;
        public static final int ic_allday_collapse_large_holo_light=0x7f02002f;
        public static final int ic_allday_collapse_small_holo_light=0x7f020030;
        public static final int ic_allday_expand_holo_light=0x7f020031;
        public static final int ic_allday_expand_large_holo_light=0x7f020032;
        public static final int ic_allday_expand_small_holo_light=0x7f020033;
        public static final int ic_contact_picture=0x7f020034;
        public static final int ic_menu_add_event_holo_light=0x7f020035;
        public static final int ic_menu_add_field_holo_light=0x7f020036;
        public static final int ic_menu_cancel_holo_light=0x7f020037;
        public static final int ic_menu_compose_holo_dark=0x7f020038;
        public static final int ic_menu_compose_holo_light=0x7f020039;
        public static final int ic_menu_done_holo_light=0x7f02003a;
        public static final int ic_menu_refresh_holo_light=0x7f02003b;
        public static final int ic_menu_remove_field_holo_light=0x7f02003c;
        public static final int ic_menu_search_holo_light=0x7f02003d;
        public static final int ic_menu_select_visible_calendars_holo_light=0x7f02003e;
        public static final int ic_menu_settings_holo_light=0x7f02003f;
        public static final int ic_menu_today_holo_light=0x7f020040;
        public static final int ic_menu_trash_holo_dark=0x7f020041;
        public static final int ic_menu_trash_holo_light=0x7f020042;
        public static final int ic_repeat_dark=0x7f020043;
        public static final int ic_repeat_white=0x7f020044;
        public static final int list_focused_holo=0x7f020045;
        public static final int list_item_background=0x7f020046;
        public static final int list_item_font_primary=0x7f020047;
        public static final int list_item_font_secondary=0x7f020048;
        public static final int list_multi_left_activated_holo=0x7f020049;
        public static final int list_multi_left_focused_holo=0x7f02004a;
        public static final int list_multi_left_pressed_holo=0x7f02004b;
        public static final int list_multi_left_primary_holo=0x7f02004c;
        public static final int list_multi_left_secondary_holo=0x7f02004d;
        public static final int list_pressed_holo=0x7f02004e;
        public static final int list_primary_holo=0x7f02004f;
        public static final int list_secondary_holo=0x7f020050;
        public static final int minical_bg_shadow_holo_light=0x7f020051;
        public static final int panel_month_event_holo_light=0x7f020052;
        public static final int stat_notify_calendar=0x7f020053;
        public static final int timeline_indicator_activated_holo_light=0x7f020054;
        public static final int timeline_indicator_holo_light=0x7f020055;
        public static final int today_blue_week_holo_light=0x7f020056;
        public static final int widget_chip_not_responded_bg=0x7f020057;
        public static final int widget_chip_responded_bg=0x7f020058;
        public static final int widget_show=0x7f020059;
    }
    public static final class id {
        public static final int account=0x7f100004;
        public static final int account_name=0x7f100035;
        public static final int account_status=0x7f100001;
        public static final int account_type=0x7f100005;
        public static final int action_add_account=0x7f1000af;
        public static final int action_cancel=0x7f100080;
        public static final int action_create_event=0x7f1000a8;
        public static final int action_done=0x7f100081;
        public static final int action_hide_controls=0x7f1000ac;
        public static final int action_refresh=0x7f1000a9;
        public static final int action_search=0x7f1000a6;
        public static final int action_select_visible_calendars=0x7f1000aa;
        public static final int action_settings=0x7f1000ab;
        public static final int action_today=0x7f1000a7;
        public static final int add_attendees_label=0x7f10006e;
        public static final int add_attendees_row=0x7f10006d;
        public static final int agenda_event_info=0x7f100010;
        public static final int agenda_events_list=0x7f10000f;
        public static final int agenda_item_color=0x7f100011;
        public static final int agenda_sticky_header_list=0x7f10000e;
        public static final int alert_container=0x7f100018;
        public static final int all_day_row=0x7f10005b;
        public static final int appwidget_date=0x7f100029;
        public static final int appwidget_loading=0x7f10002a;
        public static final int appwidget_no_events=0x7f10002c;
        public static final int attendees=0x7f10006f;
        public static final int attendees_group=0x7f100042;
        public static final int availability=0x7f10007b;
        public static final int availability_row=0x7f100079;
        public static final int badge=0x7f10003a;
        public static final int btn_discard=0x7f1000a1;
        public static final int btn_done=0x7f1000a2;
        public static final int bubble_layout=0x7f10002e;
        public static final int button_date=0x7f100007;
        public static final int button_view=0x7f100006;
        public static final int calendar=0x7f100031;
        public static final int calendar_group=0x7f100046;
        public static final int calendar_list=0x7f100003;
        public static final int calendar_name=0x7f100034;
        public static final int calendar_selector_group=0x7f100044;
        public static final int calendar_textview=0x7f100047;
        public static final int calendar_textview_secondary=0x7f100048;
        public static final int calendars=0x7f100000;
        public static final int calendars_spinner=0x7f100045;
        public static final int color=0x7f100030;
        public static final int color_chip=0x7f100043;
        public static final int color_square=0x7f10001b;
        public static final int contact_remove=0x7f100039;
        public static final int contact_separator=0x7f10003b;
        public static final int d0_label=0x7f100096;
        public static final int d1_label=0x7f100097;
        public static final int d2_label=0x7f100098;
        public static final int d3_label=0x7f100099;
        public static final int d4_label=0x7f10009a;
        public static final int d5_label=0x7f10009b;
        public static final int d6_label=0x7f10009c;
        public static final int date=0x7f10000d;
        public static final int date_bar=0x7f100024;
        public static final int date_group=0x7f100023;
        public static final int day=0x7f10000c;
        public static final int day_names=0x7f100093;
        public static final int day_of_week=0x7f100027;
        public static final int delete=0x7f10008a;
        public static final int desc_expand=0x7f10008e;
        public static final int description=0x7f100072;
        public static final int description_label=0x7f100071;
        public static final int description_row=0x7f100070;
        public static final int dismiss_all=0x7f10001a;
        public static final int edit=0x7f100089;
        public static final int edit_event=0x7f10003d;
        public static final int end_date=0x7f100056;
        public static final int end_date_home_tz=0x7f100059;
        public static final int end_time=0x7f100057;
        public static final int end_time_home_tz=0x7f10005a;
        public static final int event_bg=0x7f100040;
        public static final int event_info_buttons_container=0x7f100088;
        public static final int event_info_headline=0x7f100087;
        public static final int event_info_scroll_view=0x7f100086;
        public static final int event_title=0x7f10001c;
        public static final int events_list=0x7f100028;
        public static final int from_label=0x7f10004e;
        public static final int from_row=0x7f10004d;
        public static final int from_row_home_tz=0x7f100051;
        public static final int header=0x7f100026;
        public static final int home_time=0x7f10001e;
        public static final int info_action_delete=0x7f1000ae;
        public static final int info_action_edit=0x7f1000ad;
        public static final int is_all_day=0x7f10005c;
        public static final int is_all_day_label=0x7f10005d;
        public static final int list=0x7f10009f;
        public static final int loading=0x7f10002b;
        public static final int loading_message=0x7f10003e;
        public static final int location=0x7f10004a;
        public static final int long_attendee_list=0x7f100090;
        public static final int main_frame=0x7f1000a3;
        public static final int main_pane=0x7f10001f;
        public static final int manage_sync_set=0x7f1000a0;
        public static final int mini_month=0x7f100022;
        public static final int mini_month_container=0x7f100021;
        public static final int month=0x7f100091;
        public static final int month_name=0x7f100092;
        public static final int name=0x7f100038;
        public static final int no_events=0x7f10002d;
        public static final int organizer=0x7f10006c;
        public static final int organizer_container=0x7f10008d;
        public static final int organizer_label=0x7f10006b;
        public static final int organizer_row=0x7f10006a;
        public static final int presence_label=0x7f10007a;
        public static final int privacy_label=0x7f10007d;
        public static final int progress_circular=0x7f100037;
        public static final int reminder=0x7f100017;
        public static final int reminder_add=0x7f100078;
        public static final int reminder_icon=0x7f100016;
        public static final int reminder_items_container=0x7f100077;
        public static final int reminder_method_value=0x7f100083;
        public static final int reminder_minutes_value=0x7f100082;
        public static final int reminder_remove=0x7f100084;
        public static final int reminders_group_label=0x7f10007f;
        public static final int reminders_label=0x7f100076;
        public static final int reminders_row=0x7f100075;
        public static final int repeat_icon=0x7f10001d;
        public static final int repeats=0x7f100074;
        public static final int repeats_label=0x7f100073;
        public static final int response_container=0x7f10008f;
        public static final int response_label=0x7f100065;
        public static final int response_maybe=0x7f100068;
        public static final int response_no=0x7f100069;
        public static final int response_row=0x7f100064;
        public static final int response_value=0x7f100066;
        public static final int response_yes=0x7f100067;
        public static final int scroll_view=0x7f10003f;
        public static final int search_results=0x7f10009e;
        public static final int secondary_pane=0x7f100020;
        public static final int selected_marker=0x7f100015;
        public static final int snooze_all=0x7f100019;
        public static final int start_date=0x7f10004f;
        public static final int start_date_home_tz=0x7f100052;
        public static final int start_time=0x7f100050;
        public static final int start_time_home_tz=0x7f100053;
        public static final int status=0x7f100032;
        public static final int switcher=0x7f10003c;
        public static final int sync=0x7f100033;
        public static final int sync_settings=0x7f100002;
        public static final int text1=0x7f100036;
        public static final int text2=0x7f100085;
        public static final int time=0x7f10002f;
        public static final int timezone_button=0x7f100061;
        public static final int timezone_button_row=0x7f100060;
        public static final int timezone_footer=0x7f1000a4;
        public static final int timezone_label=0x7f100063;
        public static final int timezone_textView=0x7f10005f;
        public static final int timezone_textview_row=0x7f10005e;
        public static final int title=0x7f100012;
        public static final int to_label=0x7f100055;
        public static final int to_row=0x7f100054;
        public static final int to_row_home_tz=0x7f100058;
        public static final int top_button_date=0x7f100009;
        public static final int top_button_weekday=0x7f100008;
        public static final int top_divider_past_present=0x7f10000b;
        public static final int top_divider_simple=0x7f10000a;
        public static final int two_pane=0x7f100041;
        public static final int visibility=0x7f10007e;
        public static final int visibility_row=0x7f10007c;
        public static final int visible_check_box=0x7f10009d;
        public static final int week_list=0x7f100094;
        public static final int week_num=0x7f100025;
        public static final int what_label=0x7f100062;
        public static final int when=0x7f100013;
        public static final int when_date=0x7f10008b;
        public static final int when_label=0x7f10004c;
        public static final int when_row=0x7f10004b;
        public static final int when_time=0x7f10008c;
        public static final int where=0x7f100014;
        public static final int where_row=0x7f100049;
        public static final int widget_row=0x7f1000a5;
        public static final int wk_label=0x7f100095;
    }
    public static final class integer {
        /**  The size of the color chip in the agenda view for all day events 
 The size of the color chip in the agenda view for all day events 
         */
        public static final int color_chip_all_day_height=0x7f0b0005;
        /**  The size of the color chip in the agenda view 
 The size of the color chip in the agenda view 
         */
        public static final int color_chip_height=0x7f0b0006;
        /**  The default alpha level of photos of attendees 
         */
        public static final int default_attendee_photo_alpha_level=0x7f0b0003;
        /**  max number of lines in the description without showing More/Less button  
         */
        public static final int event_info_desc_line_num=0x7f0b0001;
        /**  margin between the day number and the edge of the day in month view 
 margin between the day number and the edge of the day in month view 
         */
        public static final int month_day_number_margin=0x7f0b0004;
        /**  The alpha level of photos of attendees that didn't respond 
         */
        public static final int noresponse_attendee_photo_alpha_level=0x7f0b0002;
        /**  size of day date font in month view  
 size of day date font in month view  
         */
        public static final int text_size_month_number=0x7f0b0000;
        /**  The time of day in minutes usually considered the end of the work day, eg. 8pm in the US 
         */
        public static final int work_end_minutes=0x7f0b0008;
        /**  The time of day in minutes usually considered the start of the work day, eg. 6am in the US 
         */
        public static final int work_start_minutes=0x7f0b0007;
    }
    public static final class layout {
        public static final int account_calendars=0x7f040000;
        public static final int account_item=0x7f040001;
        public static final int actionbar_pulldown_menu_button=0x7f040002;
        public static final int actionbar_pulldown_menu_top_button=0x7f040003;
        public static final int agenda_day=0x7f040004;
        public static final int agenda_fragment=0x7f040005;
        public static final int agenda_header_footer=0x7f040006;
        public static final int agenda_item=0x7f040007;
        public static final int agenda_reminder_item=0x7f040008;
        public static final int alert_activity=0x7f040009;
        public static final int alert_item=0x7f04000a;
        public static final int all_in_one=0x7f04000b;
        public static final int appwidget=0x7f04000c;
        public static final int appwidget_day=0x7f04000d;
        public static final int appwidget_loading=0x7f04000e;
        public static final int appwidget_no_events=0x7f04000f;
        public static final int bubble_event=0x7f040010;
        public static final int calendar_sync_item=0x7f040011;
        public static final int calendars_dropdown_item=0x7f040012;
        public static final int calendars_item=0x7f040013;
        public static final int chips_alternate_item=0x7f040014;
        public static final int chips_recipient_dropdown_item=0x7f040015;
        public static final int chips_waiting_for_directory_search=0x7f040016;
        public static final int contact_item=0x7f040017;
        public static final int copy_chip_dialog_layout=0x7f040018;
        public static final int date_range_title=0x7f040019;
        public static final int day_activity=0x7f04001a;
        public static final int edit_event=0x7f04001b;
        public static final int edit_event_1=0x7f04001c;
        public static final int edit_event_2=0x7f04001d;
        public static final int edit_event_custom_actionbar=0x7f04001e;
        public static final int edit_event_single_column=0x7f04001f;
        public static final int edit_reminder_item=0x7f040020;
        public static final int email_autocomplete_item=0x7f040021;
        public static final int email_autocomplete_item_loading=0x7f040022;
        public static final int event_info=0x7f040023;
        public static final int event_info_label=0x7f040024;
        public static final int full_month_by_week=0x7f040025;
        public static final int full_month_header=0x7f040026;
        public static final int mini_calendar_item=0x7f040027;
        public static final int mini_month_header=0x7f040028;
        public static final int month_by_week=0x7f040029;
        public static final int more_item=0x7f04002a;
        public static final int search=0x7f04002b;
        public static final int select_calendars_fragment=0x7f04002c;
        public static final int select_calendars_multi_accounts_fragment=0x7f04002d;
        public static final int simple_frame_layout=0x7f04002e;
        public static final int timezone_footer=0x7f04002f;
        public static final int widget_all_day_item=0x7f040030;
        public static final int widget_item=0x7f040031;
    }
    public static final class menu {
        public static final int all_in_one_title_bar=0x7f0f0000;
        public static final int edit_event_title_bar=0x7f0f0001;
        public static final int event_info_title_bar=0x7f0f0002;
        public static final int search_title_bar=0x7f0f0003;
        public static final int settings_title_bar=0x7f0f0004;
    }
    public static final class mipmap {
        public static final int ic_launcher_calendar=0x7f030000;
    }
    public static final class plurals {
        /**  This is the number of days displayed for a calendar reminder.  For example,
         a reminder of 2 days would be displayed as '2 days'.  The translation
         should use the shortest acceptable abbreviation of 'day' to save space. 
         */
        public static final int Ndays=0x7f0d0003;
        /**  This is the number of hours displayed for a calendar reminder.  For example,
         a reminder of 1 hour would be displayed as '1 hour'.  The translation
         should use the shortest acceptable abbreviation of 'hour' to save space. 
         */
        public static final int Nhours=0x7f0d0002;
        /**  We use the abbreviation "mins" instead of "minutes" to keep the string short.
         This is the number of minutes displayed for a calendar reminder.  For example,
         a reminder of 10 minutes would be displayed as '10 mins'.  The translation
         should use the shortest acceptable abbreviation to save space. 
         */
        public static final int Nmins=0x7f0d0001;
        /**  Reminder format strings 
         */
        public static final int Nminutes=0x7f0d0000;
        /**  Shown in month view next to event icon when additional events exist for that day, but no
        room remaining 
         */
        public static final int month_more_events=0x7f0d0005;
        /**  This is for displaying the week of the year near the date. Eg. "January, 2011 Week 1" 
         */
        public static final int weekN=0x7f0d0004;
    }
    public static final class string {
        /**  Add a new attendee to an event [CHAR LIMIT = NONE]
         */
        public static final int accessibility_add_attendee=0x7f0c0093;
        /**  Add a reminder to an event [CHAR LIMIT = NONE]
         */
        public static final int accessibility_add_reminder=0x7f0c0091;
        /**  Mark this event as an "all day event" [CHAR LIMIT = NONE]
         */
        public static final int accessibility_all_day=0x7f0c0095;
        /**  Pick the ending date for a new event [CHAR LIMIT = NONE]
         */
        public static final int accessibility_pick_end_date=0x7f0c008e;
        /**  Pick the ending time for a new event[CHAR LIMIT = NONE]
         */
        public static final int accessibility_pick_end_time=0x7f0c008f;
        /**  Pick a starting date for a new event [CHAR LIMIT = NONE]
         */
        public static final int accessibility_pick_start_date=0x7f0c008c;
        /**  Pick a starting time for a new event [CHAR LIMIT = NONE]
         */
        public static final int accessibility_pick_start_time=0x7f0c008d;
        /**  Select a time zone for a new event [CHAR LIMIT = NONE]
         */
        public static final int accessibility_pick_time_zone=0x7f0c0090;
        /**  Set the event as private/public/default [CHAR LIMIT = NONE]
         */
        public static final int accessibility_reminder_privacy=0x7f0c009a;
        /**  Select the way you are visible for the event (busy/free) [CHAR LIMIT = NONE]
         */
        public static final int accessibility_reminder_showmeas=0x7f0c0099;
        /**  Set the time for the reminder[CHAR LIMIT = NONE]
         */
        public static final int accessibility_reminder_time=0x7f0c0097;
        /**  Set the type of the reminder (popup/email/sms)[CHAR LIMIT = NONE]
         */
        public static final int accessibility_reminder_type=0x7f0c0098;
        /**  Accessibility Events 
 Strings that describes actions for buttons without text 
 Create a new calendar event [CHAR LIMIT = NONE]
 Remove a name of an attendee from a calendar event [CHAR LIMIT = NONE]
         */
        public static final int accessibility_remove_attendee=0x7f0c008b;
        /**  Remove a reminder from an event [CHAR LIMIT = NONE]
         */
        public static final int accessibility_remove_reminder=0x7f0c0092;
        /**  Refresh the data in the calendar [CHAR LIMIT = NONE]
 Choose the type of repetition for the event (daily, weekly, etc.[CHAR LIMIT = NONE]
         */
        public static final int accessibility_repeats=0x7f0c0096;
        /**  Choose if to sync/unsync this calendar with its server [CHAR LIMIT = NONE]
         */
        public static final int accessibility_sync_cal=0x7f0c0094;
        /**  Label on button that takes user to the Accounts and Sync settings page [CHAR LIMIT=60] 
         */
        public static final int accounts=0x7f0c001d;
        /**  Message displayed to user when an account with Calendars is not being auto-synced
        [CHAR LIMIT=120]
         */
        public static final int acct_not_synced=0x7f0c001c;
        /**  Title of a button shown when there is no account available and the system prompt a user to add one. [CHAR LIMIT=none] 
         */
        public static final int add_account=0x7f0c0038;
        /**  Label for adding guests to an event [CHAR LIMIT=32]
         */
        public static final int add_guests_label=0x7f0c0039;
        /**  This is shown as part of the heading at the top of a list of today's events. 
         */
        public static final int agenda_today=0x7f0c0045;
        /**  This is shown as part of the heading at the top of a list of today's events. 
         */
        public static final int agenda_tomorrow=0x7f0c0047;
        /**  This is a label on a menu item. Pressing this menu item displays the
         Agenda view. 
         */
        public static final int agenda_view=0x7f0c000b;
        /**  This is shown as part of the heading at the top of a list of today's events. 
         */
        public static final int agenda_yesterday=0x7f0c0046;
        /**  the title of the alert/notification activity 
         */
        public static final int alert_title=0x7f0c0029;
        /**  This is the label underneath the icon for Calendar 
         */
        public static final int app_label=0x7f0c0000;
        /**  This is the label for the Guests/Attendees of an event 
         */
        public static final int attendees_label=0x7f0c0005;
        /**  This is a label on a context menu item. Pressing this menu item to initiate
        syncing of your Calendar data with the server. [CHAR LIMIT=11] 
         */
        public static final int calendar_refresh=0x7f0c0009;
        /**  This is the title of a popup dialog that asks for confirmation before
         changing the response to an invitation. 
         */
        public static final int change_response_title=0x7f0c0066;
        /**  Text displayed when there are remote directories not returning results.
         [CHAR LIMIT=50] 
         */
        public static final int chips_waiting_for_directory_result=0x7f0c009e;
        /**  Text displayed when the user long presses on a chip to copy the recipients email address.
         [CHAR LIMIT=200] 
         */
        public static final int copy=0x7f0c009f;
        /**  Send a copy of the database to developers for debugging [CHAR LIMIT="NONE"] 
         */
        public static final int copy_db=0x7f0c0089;
        /**  Body of dialog prompting the user to create an account.[CHAR LIMIT=NONE] 
         */
        public static final int create_an_account_desc=0x7f0c0037;
        /**  Toast message displayed when a new event is created 
         */
        public static final int creating_event=0x7f0c0024;
        /**  Toast message displayed when a new event with guests is created 
         */
        public static final int creating_event_with_guest=0x7f0c0027;
        /**  This is a label for telling the user that this event repeats in
         custom (non-standard) way from the usual repeat rates (such as daily,
         weekly, etc.) and that the user cannot change this on the phone
         (but only on the web). 
         */
        public static final int custom=0x7f0c005e;
        /**  A label in a multiple-choice list for the specifying that an event
         repeats daily 
         */
        public static final int daily=0x7f0c0056;
        /**  This is a label on a menu item. Pressing this menu item displays the
         Day view. 
         */
        public static final int day_view=0x7f0c000c;
        /**  A "new event" hint for the user when selecting a specific hour in the day view [CHAR LIMIT = 30]
         */
        public static final int day_view_new_event_hint=0x7f0c009b;
        /**  The button label for deleting an event 
         */
        public static final int delete_label=0x7f0c004f;
        /**  This is a confirmation message in a popup dialog that appears when the
         user has asked to delete an event. The user still has a chance to cancel
         this operation. 
         */
        public static final int delete_this_event_title=0x7f0c0064;
        /**  This is the title of a popup dialog that asks for confirmation before
         deleting an event. 
         */
        public static final int delete_title=0x7f0c0065;
        /**  Label for the event description 
         */
        public static final int description_label=0x7f0c0031;
        /**  Displayed in email address autocomplete list when searching for contacts
         in corporate directories. Example:  "Searching bigcompany.com..." [CHAR LIMIT=64] 
         */
        public static final int directory_searching_fmt=0x7f0c008a;
        /**  The button label for discarding changes to an event 
         */
        public static final int discard_label=0x7f0c0051;
        /**  The button label for dismissing all the current reminder alarms. This
         causes them to disappear from the notification screen. 
         */
        public static final int dismiss_all_label=0x7f0c0054;
        /**  A label in a multiple-choice list for the specifying that an event does
         not repeat 
         */
        public static final int does_not_repeat=0x7f0c0055;
        /**  Check box label that specifies if this is an all-day event 
         */
        public static final int edit_event_all_day_label=0x7f0c002e;
        /**  Label for choosing one of the calendars 
         */
        public static final int edit_event_calendar_label=0x7f0c002f;
        /**  Events have a start date/time and an end date/time. The display shows
         the start and end times like 'From start date To end date'. This is the
         label before the 'start date'. 
         */
        public static final int edit_event_from_label=0x7f0c002d;
        /**  This is the title of a popup window that is displayed when the user
         edits a repeating event. [CHAR LIMIT=20]
         */
        public static final int edit_event_label=0x7f0c004d;
        /**  Menu item to show all choices [CHAR LIMIT=22]
         */
        public static final int edit_event_show_all=0x7f0c0030;
        /**  Events have a start date/time and an end date/time. The display shows
         the start and end times like 'From start date To end date'. This is the
         label before the 'end date'. 
         */
        public static final int edit_event_to_label=0x7f0c002c;
        /**  This is a menu button for switching into edit mode when viewing an event.
        [CHAR LIMIT=10] 
         */
        public static final int edit_label=0x7f0c004e;
        /**  Toast message displayed when a new event was not saved because it was empty [CHAR LIMIT=30] 
         */
        public static final int empty_event=0x7f0c0026;
        /**  This is a label on a menu item. Pressing this menu item allows the
         user to create a new event. 
         */
        public static final int event_create=0x7f0c0010;
        /**  This is a label on a menu item in a popup window. Pressing this menu
         item allows the user to delete an existing event. 
         */
        public static final int event_delete=0x7f0c0012;
        /**  This is a label on a menu item in a popup window. Pressing this menu
         item allows the user to edit or change an existing event. 
         */
        public static final int event_edit=0x7f0c0011;
        /**  Less label in description button [CHAR LIMIT=6]
         */
        public static final int event_info_desc_less=0x7f0c0043;
        /**  More label in description button [CHAR LIMIT=6]
         */
        public static final int event_info_desc_more=0x7f0c0042;
        /**  Event Info strings
 Time Zone Label [CHAR LIMIT=12]
 Repetition Label [CHAR LIMIT=12]
 Organizer Label [CHAR LIMIT=12]
         */
        public static final int event_info_organizer=0x7f0c0041;
        /**  Reminders label [CHAR LIMIT=15]
         */
        public static final int event_info_reminders_label=0x7f0c0044;
        /**  This is the title of the screen used to view the details of an event 
         */
        public static final int event_info_title=0x7f0c002a;
        /**  This is the title of the screen used to view the details of an invitation
         to a meeting or event 
         */
        public static final int event_info_title_invite=0x7f0c002b;
        /**  This is a label on a menu item. Pressing this menu item displays the
         details of an event. 
         */
        public static final int event_view=0x7f0c000f;
        /**  A label in a multiple-choice list for the specifying that an event
         repeats every weekday (Monday through Friday) 
         */
        public static final int every_weekday=0x7f0c0057;
        /**  Caption to show on gadget when there are no upcoming calendar events 
         */
        public static final int gadget_no_events=0x7f0c0086;
        /**  Title for calendar gadget when displayed in list of all other gadgets 
         */
        public static final int gadget_title=0x7f0c0085;
        /**  DO NOT TRANSLATE the domain to use for auto-completing email addresses
 DO NOT TRANSLATE the domain to use for auto-completing email addresses
         */
        public static final int google_email_domain=0x7f0c003a;
        /**  This is a label on a menu item. Pressing this menu
         item takes the user to the current day (today) in whatever view
         (Day view, Week view, Agenda view, Month view) they are currently in. 
         */
        public static final int goto_today=0x7f0c0013;
        /**  This is a label on a menu item. Pressing this menu item hides
         the navigation controls on the right side. [CHAR LIMIT=20] 
         */
        public static final int hide_controls=0x7f0c0017;
        /**  Default value of Attendees/Guests field (as a hint to the user) [CHAR LIMIT=10] 
         */
        public static final int hint_attendees=0x7f0c0023;
        /**  Default value of Description field (as a hint to the user) [CHAR LIMIT=15]
         */
        public static final int hint_description=0x7f0c0022;
        /**  The title of the screen where the user edits an event [CHAR LIMIT=17] 
 Default value of What field (as a hint to the user) [CHAR LIMIT=15] 
         */
        public static final int hint_what=0x7f0c0020;
        /**  Default value of Where field (as a hint to the user)[CHAR LIMIT=15] 
         */
        public static final int hint_where=0x7f0c0021;
        /**  The button label for importing events from another source to the phone 
         */
        public static final int import_label=0x7f0c0052;
        /**  This is shown while the calendar events are being loading to the screen. 
         */
        public static final int loading=0x7f0c0048;
        /**  This the title of a menu for "About Calendar" Preferences.
         Pressing the menu item lets user to view the current settings
         [CHAR LIMIT=30] 
         */
        public static final int menu_about_preferences=0x7f0c0068;
        /**  This the title of a menu for General Preferences.
         Pressing the menu item lets user to view and edit his general settings
         (or preferences) [CHAR LIMIT=30] 
         */
        public static final int menu_general_preferences=0x7f0c0067;
        /**  This is a label on a menu item. Pressing this menu item allows the
         user to see the list of calendars that he is viewing and to then add
         or remove selected calendars. 
 This is a label on a menu item. Pressing this menu item allows the
         user to view and edit his Settings (or Preferences) 
         */
        public static final int menu_preferences=0x7f0c0014;
        /**  This is a label on a menu item. Pressing this menu item allows the
         user to select the calendars to display [CHAR LIMIT=11] 
         */
        public static final int menu_select_visible_calendars=0x7f0c0015;
        /**  This is a choice in a list that the user sees when he tries to modify
         a repeating event.  This choice says to change all occurrences of
         this repeating event. 
         */
        public static final int modify_all=0x7f0c0060;
        /**  This is a choice in a list that the user sees when he tries to modify
         a repeating event.  This choice says to change this instance and all
         future occurrences of this repeating event. 
         */
        public static final int modify_all_following=0x7f0c0061;
        /**  This is a choice in a list that the user sees when he tries to modify
         a repeating event.  This choice says to change just this one instance
         of this repeating event. 
         */
        public static final int modify_event=0x7f0c005f;
        /**  This is a label on a menu item. Pressing this menu item displays the
         Month view. 
         */
        public static final int month_view=0x7f0c000e;
        /**  The common portion of a string describing how often an event repeats,
         example: 'Monthly (on day 2)' 
         */
        public static final int monthly=0x7f0c005a;
        /**  Example: "Monthly (on day 15)" 
         */
        public static final int monthly_on_day=0x7f0c005c;
        /**  Example: 'Monthly (every first Sunday)' 
   1st parameter is an ordinal number, like 'first' 
   2nd parameter is a day of the week, like 'Sunday' 
         */
        public static final int monthly_on_day_count=0x7f0c0059;
        /**  Text displayed when the recipientedittextview is not focused. Displays the total number of recipients since the field is shrunk to just display a portion 
         */
        public static final int more_string=0x7f0c009d;
        /**  Dialogs 
 This is a label on the dialog for creating a new event. [CHAR LIMIT=30] 
         */
        public static final int new_event_dialog_label=0x7f0c0062;
        /**  This is the button to create a new event in a dialog window. [CHAR LIMIT=30] 
         */
        public static final int new_event_dialog_option=0x7f0c0063;
        /**  Body of alert shown if the user tries to create an event and has no calendars. Users can start adding an account here. [CHAR LIMIT=NONE] 
         */
        public static final int no_calendars_found=0x7f0c0036;
        /**  Title of alert shown if the user tries to create an event and has no calendars 
         */
        public static final int no_syncable_calendars=0x7f0c0035;
        /**  Title of event when no explicit title is specified by the user 
         */
        public static final int no_title_label=0x7f0c0008;
        /**  Not synced status message displayed when the given calendar is not stored/synced on the
        device [CHAR LIMIT=60] 
         */
        public static final int not_synced=0x7f0c001b;
        /**  This is a abbreviation for 'Number of events' and is a label next to
         an input for the user to enter the number of events to import. 
         */
        public static final int num_events=0x7f0c004c;
        /**  The default vibrateWhen value, when none is set 
         */
        public static final int prefDefault_alerts_vibrateWhen=0x7f0c0081;
        /**  The value to use then migrating from old versions for a false vibrate setting 
         */
        public static final int prefDefault_alerts_vibrate_false=0x7f0c0083;
        /**  The value to use then migrating from old versions for a true vibrate setting 
         */
        public static final int prefDefault_alerts_vibrate_true=0x7f0c0082;
        /**  Dialog title for the Vibrate dialog 
         */
        public static final int prefDialogTitle_vibrateWhen=0x7f0c0084;
        /**  This is the title of a section in the Settings screen for "About" this application 
         */
        public static final int preferences_about_title=0x7f0c007f;
        /**  Title of check box label to enable or disable pop-up notifications 
         */
        public static final int preferences_alerts_popup_title=0x7f0c0076;
        /**  Title of ringtone selector dialog 
         */
        public static final int preferences_alerts_ringtone_title=0x7f0c0075;
        /**  Settings check box label to enable or disable notifications 
         */
        public static final int preferences_alerts_title=0x7f0c0073;
        /**  Settings dialog label that specifies when the phone should vibrate 
         */
        public static final int preferences_alerts_vibrateWhen_title=0x7f0c0074;
        /**  Build version of the application 
         */
        public static final int preferences_build_version=0x7f0c0080;
        /**  Summary of the settings item to clear the recent search history [CHAR LIMIT=70]
         */
        public static final int preferences_clear_search_history_summary=0x7f0c0071;
        /**  Title of the settings item to clear the recent search history [CHAR LIMIT=40] 
         */
        public static final int preferences_clear_search_history_title=0x7f0c0070;
        /**  Default value for the number of reminder minutes 
         */
        public static final int preferences_default_reminder_default=0x7f0c0079;
        /**  Title of dialog for setting the default number of reminder minutes 
         */
        public static final int preferences_default_reminder_dialog=0x7f0c0078;
        /**  List item label for setting the default number of reminder minutes 
         */
        public static final int preferences_default_reminder_title=0x7f0c0077;
        /**  This is the title of a section in the Settings screen for settings
         related to viewing calendar events 
         */
        public static final int preferences_general_title=0x7f0c006a;
        /**  Settings check box label to hide events that the user has declined to attend 
         */
        public static final int preferences_hide_declined_title=0x7f0c006c;
        /**  DO NOT TRANSLATE 
         */
        public static final int preferences_home_tz_default=0x7f0c007d;
        /**  Settings title for selecting a 'home' time zone to display Calendar in [CHAR LIMIT = 18] 
         */
        public static final int preferences_home_tz_title=0x7f0c007c;
        /**  This is the title of a section in the Settings screen for settings
         related to reminders for calendar events 
         */
        public static final int preferences_reminder_title=0x7f0c006b;
        /**  Title of the settings item to show week number in week view [CHAR LIMIT=40] 
         */
        public static final int preferences_show_week_num_title=0x7f0c007e;
        /**  This is the title of the screen for setting user preferences. 
         */
        public static final int preferences_title=0x7f0c0069;
        /**  Settings description of what setting Calendar to use a fixed 'home' time
        zone does [CHAR LIMIT = 60]
         */
        public static final int preferences_use_home_tz_descrip=0x7f0c007b;
        /**  Settings check box label to keep Calendar in a fixed 'home' time zone [CHAR LIMIT = 18] 
         */
        public static final int preferences_use_home_tz_title=0x7f0c007a;
        /**  DO NOT TRANSLATE 
         */
        public static final int preferences_week_start_day_default=0x7f0c006f;
        /**  Title of popup for week start day setting
         */
        public static final int preferences_week_start_day_dialog=0x7f0c006e;
        /**  Settings week start label to start week on specific day
         */
        public static final int preferences_week_start_day_title=0x7f0c006d;
        /**  Label for the 'Presence' of an event, which can be either 'busy' (the default)
         or 'available'  [CHAR LIMIT=15] 
         */
        public static final int presence_label=0x7f0c0032;
        /**  Label for the 'Privacy' of an event, which can be either 'private'
         or 'public' [CHAR LIMIT=15] 
         */
        public static final int privacy_label=0x7f0c0033;
        /**  Label for the list of reminders for an event [CHAR LIMIT=20] 
         */
        public static final int reminders_label=0x7f0c0034;
        /**  Some events repeat daily, weekly, monthly, or yearly.  This is the label
         for all the choices about how often an event repeats (including the choice
         of not repeating). 
         */
        public static final int repeats_label=0x7f0c0007;
        /**  This is the label for the Guest Responses and count of an event e.g. Yes (3) 
         */
        public static final int response_label=0x7f0c0006;
        /**  Response for whether attending an event - tentative [CHAR LIMIT=10]
         */
        public static final int response_maybe=0x7f0c003f;
        /**  Response for whether attending an event - declined [CHAR LIMIT=10]
         */
        public static final int response_no=0x7f0c0040;
        /**  Response for whether attending an event - accepted [CHAR LIMIT=10]
         */
        public static final int response_yes=0x7f0c003e;
        /**  A menu item for deleting an event 
 The button label for saving an event 
         */
        public static final int save_label=0x7f0c0050;
        /**  Toast message displayed when an existing event is saved after being modified 
         */
        public static final int saving_event=0x7f0c0025;
        /**  Toast message displayed when an existing event with guests is saved after being modified 
         */
        public static final int saving_event_with_guest=0x7f0c0028;
        /**  This is a label on a menu item. Pressing this menu item allows the
         user to select the calendars to display [CHAR LIMIT=11] 
         */
        public static final int search=0x7f0c0016;
        /**  Message to show in a toast when the history is cleared [CHAR LIMIT=40] 
         */
        public static final int search_history_cleared=0x7f0c0072;
        /**  Title of the search screen [CHAR LIMIT=30] 
         */
        public static final int search_title=0x7f0c004b;
        /**  Select the set of calendars to sync [CHAR LIMIT=60] 
         */
        public static final int select_synced_calendars_button=0x7f0c001f;
        /**  Select Synced Calendars activity 
 Select the set of calendars to sync [CHAR LIMIT=60] 
         */
        public static final int select_synced_calendars_title=0x7f0c001e;
        /**  Title of "My calendars" screen 
         */
        public static final int select_visible_calendars_title=0x7f0c0019;
        /**  This is a label on a menu item. Pressing this menu item shows the
         navigation controls on the right side. [CHAR LIMIT=20] 
         */
        public static final int show_controls=0x7f0c0018;
        /**  This is a label on a context menu item. Pressing this menu item displays the
         Agenda view. 
 This is a label on a context menu item. Pressing this menu item displays the
         Day view. 
         */
        public static final int show_day_view=0x7f0c000a;
        /**  This is shown at the bottom of the agenda view showing the end of the searched range. If the user taps on this string and Calendar will find events later/newer than what is visible and display them to the user 
         */
        public static final int show_newer_events=0x7f0c004a;
        /**  This is shown at the top of the agenda view showing the beginning of the searched range. If the user taps on this string and Calendar will find events older than what is visible and display them to the user 
         */
        public static final int show_older_events=0x7f0c0049;
        /**  The button label for making the reminder alarms go away temporarily.
         The reminder alarms will fire off again in 5 minutes. 
         */
        public static final int snooze_all_label=0x7f0c0053;
        /**  Synced and visible status message 
 Synced but not visible status message 
 not Synced or visible status message 
 Synced status message displayed when the given calendar is stored/synced on the device
        [CHAR LIMIT=60] 
         */
        public static final int synced=0x7f0c001a;
        /**  Text to show on gadget when an event is currently in progress 
 Text to show on gadget when an all-day event is in progress 
 DO NOT TRANSLATE 
         */
        public static final int tardis=0x7f0c0088;
        /** 
      Source: A value for announcing the current event index (example: "Event 2 of 6").
      Description: This is spoken to the user. [CHAR LIMIT="NONE"]
    
         */
        public static final int template_announce_item_index=0x7f0c009c;
        /**  This is the label for the timezone of an event [CHAR LIMIT=30] 
         */
        public static final int timezone_label=0x7f0c0004;
        /**  Text to show on gadget when an event starts on the next day 
         */
        public static final int tomorrow=0x7f0c0087;
        /**  Label for which calendar an event is part of 
         */
        public static final int view_event_calendar_label=0x7f0c003b;
        /**  Label for the event organizer 
         */
        public static final int view_event_organizer_label=0x7f0c003c;
        /**  Label for the local timezone 
 Label for whether the user is attending this event. This is shown when
         a user is invited to a meeting or event.  The possible answers are
         'yes', 'no', and 'maybe' (and, initially, 'no response'). 
         */
        public static final int view_event_response_label=0x7f0c003d;
        /**  This is a label on a menu item. Pressing this menu item displays the
         Week view. 
         */
        public static final int week_view=0x7f0c000d;
        /**  A label in a multiple-choice list for the specifying that an event
         repeats weekly on some day of the week.  For example,
         'Weekly (every Tuesday)'. 
         */
        public static final int weekly=0x7f0c0058;
        /**  This is the label for the title or name of an event 
         */
        public static final int what_label=0x7f0c0001;
        /**  This is the label for the time of an event [CHAR LIMIT=30] 
         */
        public static final int when_label=0x7f0c0003;
        /**  This is the label for the location of an event 
         */
        public static final int where_label=0x7f0c0002;
        /**  Example: "Yearly (on April 15)" 
         */
        public static final int yearly=0x7f0c005d;
        /**  Calendar spinner item, to select that an event recurs every year. 
         */
        public static final int yearly_plain=0x7f0c005b;
    }
    public static final class style {
        public static final int CalendarActionBarStyle=0x7f0e0018;
        public static final int CalendarTheme=0x7f0e0016;
        public static final int CalendarTheme_WithActionBar=0x7f0e0017;
        public static final int CalendarTheme_WithActionBarWallpaper=0x7f0e0019;
        public static final int EditEventCustomActionButton=0x7f0e001c;
        public static final int EditEventCustomActionButtonImage=0x7f0e001d;
        public static final int EditEventCustomActionButtonText=0x7f0e001e;
        public static final int EditEventSeparator=0x7f0e001b;
        public static final int EditEvent_Layout=0x7f0e0014;
        public static final int MinusButton=0x7f0e0000;
        public static final int MonthView_DayLabel=0x7f0e0002;
        public static final int MonthView_MiniMonthLabel=0x7f0e0003;
        public static final int MultiStateButton=0x7f0e001a;
        public static final int PlusButton=0x7f0e0001;
        public static final int RecipientEditTextView=0x7f0e0021;
        public static final int TextAppearance=0x7f0e0004;
        public static final int TextAppearance_AgendaView_ValueLabel=0x7f0e0008;
        public static final int TextAppearance_Date_Range_Title=0x7f0e0015;
        public static final int TextAppearance_EditEvent=0x7f0e000c;
        public static final int TextAppearance_EditEventCalSpinner=0x7f0e000e;
        public static final int TextAppearance_EditEvent_CalSpinnerValue=0x7f0e000f;
        public static final int TextAppearance_EditEvent_Label=0x7f0e0009;
        public static final int TextAppearance_EditEvent_LabelSmall=0x7f0e000a;
        public static final int TextAppearance_EditEvent_Small=0x7f0e000b;
        public static final int TextAppearance_EditEvent_Spinner=0x7f0e0010;
        public static final int TextAppearance_EditEvent_SpinnerButton=0x7f0e0011;
        public static final int TextAppearance_EditEvent_Value=0x7f0e000d;
        public static final int TextAppearance_EditEvent_homeTime=0x7f0e0012;
        public static final int TextAppearance_EventInfo_Label=0x7f0e0013;
        public static final int TextAppearance_MonthView_DayLabel=0x7f0e0007;
        public static final int TextAppearance_MonthView_MiniDayLabel=0x7f0e0006;
        public static final int TextAppearance_SelectCalendar_Name=0x7f0e0005;
        public static final int WidgetDateStyle=0x7f0e0020;
        public static final int WidgetDayOfWeekStyle=0x7f0e001f;
    }
    public static final class xml {
        public static final int about_preferences=0x7f060000;
        public static final int appwidget_info=0x7f060001;
        public static final int calendar_settings_headers=0x7f060002;
        public static final int general_preferences=0x7f060003;
        public static final int other_preferences=0x7f060004;
        public static final int searchable=0x7f060005;
    }
    public static final class styleable {
        /**  MultiStateButton doesn't define any special attributes 
         */
        public static final int[] com_android_calendar_MultiStateButton = {
            
        };
    };
}
