/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package android.accounts.cts;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_cts_minitab_selected=0x7f020000;
        public static final int ic_cts_selected=0x7f020001;
    }
    public static final class string {
        /**  Label for this package 
         */
        public static final int label=0x7f040000;
    }
    public static final class xml {
        public static final int authenticator=0x7f030000;
    }
}
