/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.email;

public final class Manifest {
    public static final class permission {
        /**  Grant permission to system apps to access provider (see provider below) 
         */
        public static final String ACCESS_PROVIDER="com.android.email.permission.ACCESS_PROVIDER";
        /**  Grant permission to other apps to view attachments 
         */
        public static final String READ_ATTACHMENT="com.android.email.permission.READ_ATTACHMENT";
    }
}
