/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.lunarlander;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_lunar_lander=0x7f020000;
        public static final int earthrise=0x7f020001;
        public static final int lander_crashed=0x7f020002;
        public static final int lander_firing=0x7f020003;
        public static final int lander_plain=0x7f020004;
    }
    public static final class id {
        public static final int lunar=0x7f050000;
        public static final int text=0x7f050001;
    }
    public static final class layout {
        public static final int lunar_layout=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int lunar_layout_text_text=0x7f040011;
        public static final int menu_easy=0x7f040005;
        public static final int menu_hard=0x7f040007;
        public static final int menu_medium=0x7f040006;
        public static final int menu_pause=0x7f040003;
        public static final int menu_resume=0x7f040004;
        public static final int menu_start=0x7f040001;
        public static final int menu_stop=0x7f040002;
        public static final int message_bad_angle=0x7f040010;
        public static final int message_off_pad=0x7f04000e;
        public static final int message_stopped=0x7f04000d;
        public static final int message_too_fast=0x7f04000f;
        public static final int mode_lose=0x7f04000a;
        public static final int mode_pause=0x7f040009;
        public static final int mode_ready=0x7f040008;
        public static final int mode_win_prefix=0x7f04000b;
        public static final int mode_win_suffix=0x7f04000c;
    }
}
