/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.gldual;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int gl1=0x7f040001;
        public static final int gl2=0x7f040002;
        public static final int text=0x7f040000;
    }
    public static final class layout {
        public static final int gldual_activity=0x7f020000;
    }
    public static final class string {
        /**  Simple strings. 
         */
        public static final int gldual_activity=0x7f030000;
    }
}
